### ISSUE TITLE
Issue with large screens

### ISSUE THREAD

**Issue by milewski** [wearebraid/vue-formulate#100]
Hi I can see the real inputs on my ultra-wide monitor on the docs site...

![image](https://user-images.githubusercontent.com/2874967/83522779-b94cc800-a513-11ea-9524-4831874c2bb2.png)

**Comment by justin-schroeder** [comment]
Bah! Right you are. We'll patch that in the next version, thanks!

**Comment by justin-schroeder** [comment]
@milewski thanks again. This is now fixed in `v2.3.4`
