### ISSUE TITLE
Is there a way to programatically submit a FormulateForm?

### ISSUE THREAD

**Issue by joel-cunningham** [wearebraid/vue-formulate#105]
I've created a wizard that has several steps. Each step of the wizard is a FormulateForm with FormulateInputs. However no form contains a FormulateInput submit button.

I have designed the wizard footer to have previous/next/submit buttons which are not within the FormulateForm. I would like these buttons in the footer to trigger the submit of each form.

 Is it possible to programatically trigger a submit on a FormulateForm by emitting an event?

**Comment by justin-schroeder** [comment]
Howdy @joel-cunningham 👋. Yes, there are a bunch of ways you could trigger a submit programmatically. Here's probably the easiest, just super simple example I whipped up using `$refs`:

https://codepen.io/justin-schroeder/pen/qBbEZGX

**Comment by joel-cunningham** [comment]
Thanks @justin-schroeder for this. Much appreciated.
