### ISSUE TITLE
Option for fake uploader duration

### ISSUE THREAD

**Issue by huzaifahj** [wearebraid/vue-formulate#106]
**Describe the new feature you'd like**
Is there a way to reduce the duration of the fake uploader for file inputs to 0? I'm using a completely separate system and functions to work with the files, without uploading them somewhere, so it's a bit inconvenient to use the async uploader function. There just needs to be a way to reduce the 'fake time' to 0, it can remain as the default option.

The main issue is that the form submission does not start until that file upload is finished, so I can't validate other fields quickly and work with that file.

**What percentage of vue-formulate users would benefit?**
1% probably

**Comment by justin-schroeder** [comment]
Hmm. makes sense. The fake uploader doesn't have any way to change itself, and honestly its not really intended to be used in production. You could swap out your uploader function globally pretty easily though. Something like this:

```
Vue.use(VueFormulate, {
  uploader: function (file, progress) {
    // optionally handle the `file` for your own purposes here...
    progress(100)
    return Promise.resolve({})
  }
})

**Comment by huzaifahj** [comment]
I agree with your points. Thanks for the snippet, works perfectly!

Added a pull request for updating documentation at https://github.com/wearebraid/vueformulate.com/pull/28
