### ISSUE TITLE
Registering custom group inputs

### ISSUE THREAD

**Issue by kylewallace** [wearebraid/vue-formulate#107]
Apologies for asking questions here as I cannot find a discord or something similar.

Is the process for creating a custom ‘group’ input the same for _field_ (I.e text, file etc) inputs?

I’ve been able to create custom _field_ inputs as per the docs https://vueformulate.com/guide/inputs/custom-inputs/#registering-an-input , however am unable to create a custom group.

To keep it simple, I’ve copied the source from your group input component into my own test component, registered it etc but cannot seem to get it working. It just doesn’t render and there are no errors. 

My use case is that I am seeking more control over the HTML markup of a group. 

I hope that all makes sense.

**Comment by kylewallace** [comment]
I assume I am registering correctly as follows?

```
Vue.use(VueFormulate, {
  library: {
    test: {
      classification: 'group',
      component: 'TestGroup'
    }
  }
})
```

Then using `<FormulateInput type=“test” name=“tests”  :repeatable="true">`

I presume that the registry classification has to be “group”?

**Comment by kylewallace** [comment]
I've inspected a working formulate group and compared it to the test group with dev tools and the difference I see is that MessageRegistry is empty for the 'test' group but contains `formulateGrouping: true` for the default group.

If you check in the DOM you can see that the group is being rendered but the 'formulate-input-group' is empty.

Hope all that helps.

**Comment by justin-schroeder** [comment]
Hi @kylewallace! I totally get needing to occasionally adjust the DOM structure of a group, however I would recommend against trying to use a custom input to do so. There's a tremendous amount of complex logic happening to make input groups work that would need to be completely redone. Trust me, you _really_ don’t want to have to re-create all of that 😂

But — there's good news! Although custom inputs are really for developing your own _custom_ input type, and less for extending or modifying the DOM you should be able to do most of the DOM manipulation you need using scoped slots or slot components to modify the internal DOM structure of a `<FormulateInput>`. These slots are intentionally isolated from the complex logic so you don't have to worry about re-creating any of that.

The slot documentation is can be found here:
https://vueformulate.com/guide/inputs/slots/#available-slots

And the group-specific slots can be found here:
https://vueformulate.com/guide/inputs/types/group/#slots

Good luck!

**Comment by kylewallace** [comment]
@justin-schroeder no worries thanks mate! I think there was some confusion on my part that group, text, select, etc.. were all ‘fields’ in relation to custom input types even though you do specifically mention ‘HTML5 input types’ in the first paragraph on that page... my bad. 

I will stick with exclusively using slots for groups and see how it goes. It’s hard when you obsess over full control of your markup which is why I moved into using custom input types so quickly for my fields 😂

Great package by the way. You can throw together a form so quickly that you blink and it is done!

**Comment by kylewallace** [comment]
@justin-schroeder I had a play with the group slots today and must say that I am impressed. I misjudged the thought you have put into them and have been able to achieve some really nice markup. I did have some trouble overriding the 'grouping' slot (probably due to lack of Vue experience) and was not sure what needed to be included inside the template for that slot to keep the repeatable working. Do you happen to have an example anywhere that I could examine?

Failing that, happy for you to close this issue as my original query has been resolved. Thanks again.

**Comment by justin-schroeder** [comment]
@kylewallace Glad you're getting far along using slots. The `grouping` slot is the hardest one to implement on your own. It's mostly there as an escape hatch for plugin developers...If you choose to override it you're responsible for doing all your own `v-for` iteration and data binding. 

In fact, it's challenging enough to use I might even remove it from the docs. Food for thought...anyway — the rest of it should be pretty straight forward. Glad you're finding success too!
