### ISSUE TITLE
Email input validation error (on mobile) when using 'suggestions' due to added space

### ISSUE THREAD

**Issue by pimhooghiemstra** [wearebraid/vue-formulate#109]
**Describe the bug**
Filling in a form with an email field on an (android) phone with suggestions adds a space after the mailaddress which sometimes triggers the validation error 'no valid email'.

With suggestions I mean, user starts typing an mailaddress and the phone keyboard shows often used mailaddresses. Once you select such a suggestion, a space is automatically added after the mailaddress which sometimes (but not always) triggers a validation error

**To Reproduce**
Steps to reproduce the behavior (on a mobile phone with Android):
1. Go to https://uitvaartutrecht.plint-demos.nl/contact
2. Mailaddress is second field
3. Start typing for the field and select a suggested mailaddress
4. Blur out of the field (using the keyboard, key "->")
5. Sometimes the field is not valid due to the extra space after the address
6. The weird thing is, the error does not always popup.

**Expected behavior**
Well, I expect the error as an extra space makes it non valid I suppose. However, would it be possible to remove the space that is added by the keyboard when choosing a suggested email?

**Device information:**
 - Device: Sony Experia XA2
 - OS: Android 9
 - Browser: chrome
 - Version: 83.0.4103.96

**Comment by justin-schroeder** [comment]
@pimhooghiemstra thanks for the report. This is exactly the kinda stuff I want to help solve for developers cause seriously...wth. I did notice on that form you sent along the email input is actually type `text` I wonder if android is smart enough to not add that space if it is type `email`?

--------

Assuming that doesn't fix it (I don’t have a test android in my home office, thanks covid)...I'm struggling to know exactly what the correct behavior is. We don’t currently have input masking, but its something I'd like to add a hook for (see #67). However even then developers would have to remember to add that to the input. I suppose we could add some special conditional logic...if this is type `email`, and you're using the `email` validation rule...then perform a trim operation?

**Comment by pimhooghiemstra** [comment]
@justin-schroeder thanks for the quick reply. I will have a check with type=email for that field, I am not sure it will fix it though.

I am trying to follow your reasoning about masks and am aware of the other issue with respect to masks and yes, a developer still needs to think about it.

My first thought was to use a watcher myself to trim the field and I hoped that the watcher would run before the validation. I did not try this out though because I hoped there was a better way to do it using the plugin. Anyway, your final remark 'special condition for field email with validation email' makes sense to me.

**Comment by pimhooghiemstra** [comment]
@justin-schroeder I changed the type of the input from text to email and the issue is resolved! Thinking about it makes it quite clear: for input[type=text] the auto suggestion thinks another word will come after it and a space is automatically added: this makes sense.

For input[type=email] it obviously does not make sense and it seems that the browser is clever enough and does not add an additional space after the email address.

Although I haven't test this on other mobile browsers as I only have chrome installed on my phone, I think this marks this issue as resolved, I'll close it.

**Comment by justin-schroeder** [comment]
That’s great news. Thanks for the follow up, it’s just one more thing to think about when form building.

**Comment by ceilfors** [comment]
I've been hitting a similar issue where I'd like to trim an input field value on blur. I needed this not only for email, but for also text in mobile. For example when a user hits a auto suggestion on their zip / post code, there's an extra space added to the value and it'll trigger an error to the regex I use. In vanilla Vue.js, what we could do is to use `v-model.trim`, but I couldn't find an equivalent of this in `vue-formulate`.

The workaround that I'm currently using is this.

```vue
<FormulateInput
  name="fullName"
  @blur="formValues.fullName = formValues.fullName.trim()"
/>
```

Are there better alternatives for such scenario?

**Comment by justin-schroeder** [comment]
So in your case @ceilfors Vue 2 supports a `v-model` `trim` modifier out of the box:

```
<FormulateInput
  name="fullName"
  v-model.trim="name"
/>
```

Unfortunately custom `v-model` modifiers (like `v-model.doWhatever`) are not supported in Vue 2. The plan is for Vue Formulate 3 to support these since [custom modifiers are now allowed in Vue 3](https://v3.vuejs.org/guide/migration/v-model.html#v-model-modifiers) but for now the way you're doing it is fine, or if the [built in v-model modifiers](https://vuejs.org/v2/guide/forms.html#trim) are good you can use those.

**Comment by ceilfors** [comment]
@justin-schroeder Thanks for that. I was using `v-model` on the `<form>` level, and I didn't realise that I could still mix having another `v-model` on the input level!
