### ISSUE TITLE
@input event called twice on select input

### ISSUE THREAD

**Issue by paulogr** [wearebraid/vue-formulate#111]
**Describe the bug**

The @input event on an input of type select is being called twice every time I change the selected value.

**To Reproduce**

1. Choose a pizza.
2. See the browser's console.

**Reproduction**

https://codepen.io/paulogr/pen/BajoQzW

**Expected behavior**

The event should be called once.

**Comment by justin-schroeder** [comment]
Right you are....certainly something worth getting cleaned up...

I'll mark this as a bug and something to address soon. Thanks for the report.

**Comment by justin-schroeder** [comment]
Should be good to go now in `v2.3.8` thanks for the quality bug report!
