### ISSUE TITLE
how to work with nuxt?

### ISSUE THREAD

**Issue by thunderwin** [wearebraid/vue-formulate#113]
I m wondering what is the right way to make it work with nuxt perfect.

**Comment by hmaesta** [comment]
#### plugins/vue-formulate.js

```js
import Vue from 'vue'
import VueFormulate from '@braid/vue-formulate'

Vue.use(VueFormulate)
```

#### nuxt.config.js

```js
export default {
  plugins: [
     '~/plugins/vue-formulate',
  ]
```

There's even a really nice [running example](https://codesandbox.io/s/vue-formulate-test-8segh?file=/components/Attending.vue) made by @SuddenDev.

**Comment by hmaesta** [comment]
Instructions added to the docs → https://github.com/wearebraid/vueformulate.com/pull/30

**Comment by BitzyLabs** [comment]
Hey guys, sorry for bringing this back from the dead.

I've been trying to set up VUE FORMULATE with Nuxt.js - I've followed all the instructions to the letter but I just can't get it to work :(

Used yarn to install, then added the relevant entries to the config file but just keeps throwing errors on "yarn dev"

:(

Love what you've done and can't wait to use it in my project...

**Comment by justin-schroeder** [comment]
@lakshitha129 gonna need a little more detail to help. You could start with your exact configuration, version of nuxt, version of Vue Formulate, error messages etc. A codesandbox reproduction would be best of all. Thanks 👍

**Comment by BitzyLabs** [comment]
Hey @justin-schroeder thanks a lot for reaching out!

After fiddling around a bit managed to get this beautiful beast working!!

I uploaded my webkit version from 4 - 5 and all of a sudden it's all working fine!!

Don't think it's connected but it fixed whatever was going on!!

Ps. Thanks heaps for the work you put towards Vueformulate 👍👍

Cheers,
