### ISSUE TITLE
Document undefined after a refresh when using additional code

### ISSUE THREAD

**Issue by Rednas83** [wearebraid/vue-formulate#114]
Besides the emit to the data of the form I also would like to add additional code to be executed after changing an input
Something like:
```
    <FormulateForm v-if="debug" v-model="data">
      <FormulateInput name="name" label="Set name" type="text" />

      <FormulateInput
        name="type"
        label="Select type"
        type="select"
        :options="types"
      />

      <FormulateInput
        name="color"
        label="Select color"
        type="select"
        :options="colors"
        @input="SetValue('T01_washer.color', $event)"
      />
    </FormulateForm>

```

This works as expected. Only problem is that after a refresh I get document undefined. The only place where I use document is inside the SetValue method.

**Log after changing color once**
![image](https://user-images.githubusercontent.com/25219229/84378190-0bf94480-abe4-11ea-9918-1b963ef3fbc6.png)

**Log after refreshing without the additional code**
![image](https://user-images.githubusercontent.com/25219229/84377933-b02ebb80-abe3-11ea-81c1-c39a01cc70b3.png)

**Log after refreshing with the additional code**
![image](https://user-images.githubusercontent.com/25219229/84376922-229e9c00-abe2-11ea-95f7-482eb5afdf69.png)

Not sure if this is related to a bug somehow or if I am doing something wrong here.

**Comment by justin-schroeder** [comment]
Can you provide the code in SetValue? I don’t think this is a Vue Formulate issue, but I can’t confirm without your code

**Comment by Rednas83** [comment]
Hereby:

```
    SetValue(iReference, iValue) {
      console.log(`SetValue(iReference=${iReference} and iValue=${iValue})`)
      if (document) {
        console.log(`iReference=${iReference} and iValue=${iValue} `)
        const [itemx, element] = iReference.split('.')
        const item = document.querySelector(`#${itemx}_svg__${element}`)
        switch (element) {
          case 'color':
            if (item != null) {
              item.style.fill = this.data.color = iValue
            }
            break
          case 'tooltip':
            this.description = iValue
            break
        }
      }
    },
```
The strange thing is that the method works, but stops working when the page is refreshed.
I need to restart the server or temporary remove the event calling the method to make the page work again.

**Comment by justin-schroeder** [comment]
You must be using Nuxt? In Nuxt you cannot use window based elements like `document` because when server side rendering (that happens on refresh) there is no `document` element on the server (node context).

This isn't related to Vue Formulate at all actually, where you have your conditional check for document, just do this:

```
// change:
if (document) {
// to:
if (typeof window !== 'undefined')
```

That should do it! Good luck 🚀

**Comment by Rednas83** [comment]
Wow! Nice rocket icon. I can confirm that you're fix is working for me.
