### ISSUE TITLE
Proposal: expose logic through renderless components

### ISSUE THREAD

**Issue by bbugh** [wearebraid/vue-formulate#116]
This is a continuation from https://github.com/wearebraid/vue-formulate/issues/66, where I originally proposed this as a possibility for solving the CSS map, but that seems to have reached a different resolution. I think this is really important for adoption and want to continue the discussion.

**Describe the new feature you'd like**

The markup of Formulate built-in components are too strict to cover advanced or strict use cases for existing projects/opinionated businesses. 

As a simple example, the current `FormulateErrors` uses `ul` and `li`, which is a very strong opinion about how to display errors. Aside from business needs, I can't personally imagine ever wanting a `ul` for errors per field. Usually we've selected either the first error, or made a sentence like "must be longer than 10, shorter than 15, and only lowercase letters".

To solve this, you might change `FormulateErrors` to a component doesn't render anything, but handles the error logic, and returns a slot with the errors. For example, `FormulateErrors` can be extended to simply add a `render` function and removing the template: 

```javascript
  render() {
    return this.$scopedSlots.default(formErrorContext)
  },
```

We can use it in our own custom component to write whatever kind of error display we want:

```vue
<formulate-errors v-slot="{ dirty, visibleErrors, label }">
  <div v-if="dirty && visibleErrors.length">
    {{ label }} {{ visibleErrors.join(", ") }}
  </div>
</formulate-errors>
``` 

Internally, `FormulateInput` would be composed of these renderless components, and people can use the built in components and slots when it is possible. For other cases that won't work for, they can build their own `SomeInput` that is composed partially or entirely out of the renderless components. Perhaps like this:

```vue
<slot
  name="errors"
  v-bind="context"
>
  <formulate-errors v-slot="{ visibleErrors, type }">
    <ul
      v-if="visibleErrors.length"
      :class="`formulate-${type}-errors`"
    >
      <li
        v-for="error in visibleErrors"
        :key="error"
        :class="`formulate-${type}-error`"
        v-text="error"
      />
    </ul>
  </formulate-errors>
```

The way `FormulateInput` works is  very markup dependent, even using slots. But the form *behavior* itself is ***really*** useful and the most important part. 

**What percentage of vue-formulate users would benefit?**

Based on using simple_form for almost a decade, I'd say 40-60% because every project I've used it on has needed to customize the built-in markup at some point.

**Comment by bbugh** [comment]
@justin-schroeder [last comment from #66](https://github.com/wearebraid/vue-formulate/issues/66#issuecomment-642779759):

> also @bbugh somehow I missed your helpful conversation on here.
>
> I've considered including renderless too. It would be pretty easy to implement, but I'm slightly concerned about it undermining the main the goals of this project: to make form authoring really easy, fast, and high quality (best practices, accessibility out of the box, etc) so markup is actually a pretty important part of what we're trying to do here — and getting people to conform to a system that allows those features to be improved over time is really valuable for the community at large. For example, if we get some good accessibility feedback an update could help hundreds of sites improve accessibility at the same time.
>
> That said, I understand that occasionally people need to deviate from that or their use case really doesn't need those features. I was hoping slots, and slot components would suffice.

I agree! I think the goals of this project are awesome, and have no desire to undermine them. I've wanted to build a library very much like this for ages. I really miss `simple_form` from Rails and wish we had something in the same ballpark with Vue. `VueFormulate` is great so far. I really want to be able to use this library for our future forms.

Unfortunately, I don't think there's any way you're going to be able to get away with forcing specific markup. HTML is just too much of a variety show, and different frameworks are different enough, that it won't be possible to hit every use case for forms and form setups.

The proposal I'm making is only to add one extra layer of "escape hatch" for cases where the default markup isn't sufficient. The recommended behavior for end users of vue-formulate could be:

1. Use the built in `FormulateForm` and `FormulateInput`
2. Or, if you need extra customization, make your own wrapper component and specify the slots
3. (proposed) or, if you need deep customization we didn't account for, here's the basic building blocks and you can build your own markup while keeping all of the super useful functionality.

If internally VueFormulate used renderless components as the foundation even for slot construction, it would allow this extra escape hatch when needed, which would allow large business-opinionated projects (like ours) to adopt it without worrying about hitting a dealbreaker opinion. "Convention over configuration" is *great*, as long as the configuration is still configurable!

**Comment by justin-schroeder** [comment]
Hey @bbugh. Thanks for the detailed write up! There's a lot of value to making sure people are _able_ to use their own markup if they really need to. I agree with you there. I've thought about this a lot 😉 so I want to make sure we're all on the same page about how the slot-components in Vue Formulate are essentially renderless already now — but there might need to be more added (like one internal to the FormulateError might be nice).

We're using a custom renderless slot-forwarding component, kind of similar to portal-vue, to provide expose slots to `FormulateInput` that are deeply nested. The effect is generally the same as a renderless component, but we have the advantage that we can replace all instances of `FormulateErrors` with your own component globally, locally and both.

So where this was your example:

```vue
<slot
  name="errors"
  v-bind="context"
>
  <formulate-errors v-slot="{ visibleErrors, type }">
    <ul
      v-if="visibleErrors.length"
      :class="`formulate-${type}-errors`"
    >
      <li
        v-for="error in visibleErrors"
        :key="error"
        :class="`formulate-${type}-error`"
        v-text="error"
      />
    </ul>
</formulate-errors>
```

This is the actual implementation:

```vue
<slot
  name="errors"
  v-bind="context"
>
      <component
        :is="context.slotComponents.errors"
        v-if="!context.disableErrors"
        :type="context.slotComponents.errors === 'FormulateErrors' ? 'input' : false"
        :context="context"
      />
</slot>
```
Now, you're correct that if you want the default merging behavior of the `FormulateErrors` component with your own markup, we're missing a slot in that location. The way we would implement that with this model is by modifying the `FormulateErrors` to include that slot:

```vue
<template>
<FormulateSlot
  name="errorList"
  :context="context"
  :visible-errors="visibleErrors"
>
  <component
    :is="context.slotComponents.errorList"
    :context="context"
    :visible-errors="visibleErrors"
  />
</FormulateSlot>
</template>

// Then in our new errorList component

<template>
<ul
    v-if="visibleErrors.length"
    :class="outerClass"
  >
    <li
      v-for="error in visibleErrors"
      :key="error"
      :class="itemClass"
      v-text="error"
    />
  </ul>
</template>
```

That `FormulateSlot` effectively makes the component renderless, but also exposes the `errorList` slot to the top most `<FormulateInput>`, and we retain the `slotComponent` super power.

I think this is an important feature actually because it lets people hoist their slots over time and improves code reuse. Lets say you had some special error rendering logic, like you said, you want to only render the first error:

```vue
<div
  class="my-first-error"
  v-if="context.visibleValidationErrors.length"
  v-text="context.visibleValidationErrors[0]"
/>
```

You could use this via slot (I know, you know this part 😀):

```vue
<FormulateInput
  type="text"
  validation="required"
>
<template #errors="{ visibleValidationErrors }">
  <div
    class="my-first-error"
    v-if="context.visibleValidationErrors.length"
    v-text="context.visibleValidationErrors[0]"
  />
  <!-- look mom! no <ul> -->
</template>
</FormulateInput>
```

Or if we want to use that on our custom input type ("brr-money") only, make it into a component `FirstError` and register it with your custom input:

```js
Vue.use(VueFormulate, {
  library: {
    'brr-money': {
      component: 'BrrMoneyInput'
      slotComponents: {
        error: 'FirstError'
      }
    }
  }
})
```

Then you can share it with multiple inputs, even the built in inputs. If you decide it's just so amazing you need it everywhere — you can replace all inputs at once:

```js
Vue.use(VueFormulate, {
  library: {
    'brr-money': {
      component: 'BrrMoneyInput'
    }
  },
  slotComponents: {
    error: 'FirstError'
  }
})
```

The only element (i think) that does not currently have these super powers is the top most wrapper. Adding this capability for the root `<FormulateInput>` would allow for a 100% renderless implementation. I'm pretty open to adding that.

I very much want people to avoid wrapping `<FormulateInput>` components as it generally leads to unpredictable api implementation and generally adds technical debt pretty quickly.

So I think continuing to add few more of these slots effectively solves your issue and maintains a consistent api — am I correct on that?

**Comment by bbugh** [comment]
Hey @justin-schroeder, thanks for the great write-up and examples. After getting burned by a couple of other vue "form" libraries I appreciate how seriously y'all are taking VueFormulate. 

I would have to test it a bit more, but that does *seem* like it would cover most of the cases that we found in our spike. 

One thing that still stands out is that in our style system, help text is below error text on form validations. Some of our form fields by necessity have long, live-updating help text because it's explaining math that affects other things. Is there a simple way to change the order of slots like this? It would definitely be preferable to have all of this stuff built in rather than having to write our own versions!

> I very much want people to avoid wrapping <FormulateInput> components as it generally leads to unpredictable api implementation and generally adds technical debt pretty quickly.

I agree, though I'm not clear on the benefits of creating a replacement component (like `FirstError` in your example) vs creating a minimal functional wrapper component that allows implicit props to be passed through. I think it would help to see an example of what this would look like. Perhaps the `MyLabel` example in [the documentation](https://vueformulate.com/guide/inputs/slots/#slot-components) could be expanded to show the `MyLabel` implementation? And/or if you're feeling generous, can you show what the `FirstError` component would look like?

**Comment by justin-schroeder** [comment]
Oh interesting...so your input "stack" looks like:

**L**abel
**I**nput
**E**rrors
**H**elp

This would be a pretty unique API, but what if we let people configure that stack for themselves by defining them:

```vue
<FormulateInput
  stack="label, input, errors, help"
/>
```
and globally

```js
Vue.use(VueFormulate, {
  stack: 'label, input, errors, help'
})
```

I dont think we want to go crazy with that and use it on anything deeper, only for the top level `FormulateInput` sub components, but that would solve your problem and potentially other people's.

As for the "Slot Component" example, yeah, I think we have more examples. Writing docs is just time consuming, especially when this isn't a full time job, but the idea behind the `MyLabel` example is to illustrate how you could add new features to the label that the core package can't forsee — for example, an info tooltip like in the [slot example](https://vueformulate.com/guide/inputs/slots/#scoped-slots). The `FirstError` example was just contrived to illustrate how _your_ organization might want to modify FormulateInput element’s markup across the board so you're not doing it over and over. If you do it the same way on lots of projects then its even worth bundling into a plugin that can easily be added to new projects.

So — what do you think about that "stack" idea? I could see it being handy for others too I think.

**Comment by bbugh** [comment]
@justin-schroeder the stack idea seems great! That would solve our issue with ordering.

The reason I asked for the specific code of `MyLabel` or `FirstError` is the heart of why I created this issue!

While I generally agree with your assertion "*avoid wrapping components as it generally leads to unpredictable api implementation*" I'm not seeing how that would actually work in practice in this situation. The documentation references creating custom slot components, but as far as I can find doesn't actually show the example of how to do it. (Bless you for writing docs, not my favorite thing either.)

I will run down the solutions that we explored that resulted in this issue proposal, I think that might help clarify.

Assuming we want to do this:

```javascript
Vue.use(VueFormulate, {
  slotComponents: {
    error: 'FirstError'
  }
})
```

I am not clear how `FirstError` would be defined. Here are the ways I can imagine it:

1. something like an functional wrapper, can be quite complicated:

```typescript
const FirstError = Vue.extend<FormulateErrorProps>({
  name: 'CustomErrors',
  functional: true,
  render (createElement, context) {
    // I think this might be injected, not a prop, but I'm sure you get the gist
    const body = context.props?.visibleErrors?.[0] ?? ''

    return createElement(
      FormulateErrors,
      {
        props: context.props
        // ...etc...
      },
      [body]
    )
  }
})
```

2. vs something like extending the `FormulateErrors`:

```typescript
// This works very badly with TypeScript 👎
const FirstError = FormulateErrors.extend({
  // override the computed functions, yuck
})
```

3. vs copying and pasting `FormulateErrors` complete with almost all of the same logic (which I don't think anyone would suggest is a good solution):

> https://github.com/wearebraid/vue-formulate/blob/master/src/FormulateErrors.vue

4. vs finally, the proposal from this issue - creating the custom `FirstError` component if you expose them to be renderless:

```vue
<template>
  <formulate-errors v-slot="{ label, visibleErrors }">
    <div v-if="visibleErrors.length">
      {{ label }} {{ visibleErrors[0] }}
    </div>
  </formulate-errors>
</template>

<script lang="ts">
import Vue from 'vue'
import FormulateErrors from 'vue-formulate'

export default Vue.extend({
  name: 'FirstError',
  components: {
    FormulateErrors 
  }
})
</script>
```

What is the vue-formulate expected way of creating these derived custom components like `FirstError`? Thanks!!

**Comment by justin-schroeder** [comment]
Ok gotchya, thanks for that explanation. So I want to make sure first I communicate that currently we do not have a slot component exposed to the internals of the `FormulateError` the way you're expecting — so my solution wouldn't work till that is implemented. Currently there's a slot name (`errors`) available to replace the entire `FormulateErrors` but there is a tad bit of logic inside the `FormulateErrors` that is missing if you do that — so I agree with you that we need to extend into that component — but let’s say we had done that already (I'll shoot to do that in `2.4`) and the slot name was `errorList`.

Then we would create a new component `FirstError` that will only ever show the first error 🤷‍♂️. The component does not need to extend anything at all, you can just use any simple component:

```vue
<template>
<div v-if="error" class="first-error-list">
  <div class="first-error-list-item">{{ error }}</div>
</div>
</template>

<script>
export default {
  props: {
    context: {
      type: Object,
      required: true
    },
    {
       visibleErrors: {
         type: Array,
         required: true
       }
    }
  },
  computed: {
    error () {
      return this.visibleErrors.length ? this.visibleErrors[0] : false
    }
  }
}
</script>
```

The only magic here is that the slot component will be passed the [context object](https://vueformulate.com/guide/inputs/#context-object) as well as any “extra props” specific to that slot. These ”extra props“ are detailed in the slot docs when applicable, but they're kinda rare as most only need the context object — but an example of some with extra props are the [group slots](https://vueformulate.com/guide/inputs/types/group/#slots).

When using these slots as scoped slots, the "extra props" (in this case "visibleErrors") are merged into the context object, when using slot components the "extra props" are available as distinct props (that should probably explained ~~better~~ _at all_ in the docs).

So now we have a component that can render errors ✅

We just need to register it with Vue Formulate — you can do this per `type` or for all inputs. In your case, I assume you want it applied on all inputs:

```js
import vue from Vue
import VueFormulate from 'vue-formulate'
import FirstError from '~/components/FirstError'

// Register it globally, you can also do this with options.components
Vue.component('FirstError', FirstError)

Vue.use(VueFormulate, {
  slotComponents: {
    errorList: 'FirstError'
  }
})
```

-------------------

So just to make sure we're all on the same page, the way you would do this same thing directly as a slot:

```vue
<FormulateInput
  type="text"
  name="^required|matches:/^justin$/"
>
  <template #errorList="{ visibleErrors }">
    <div v-if="visibleErrors.length" class="first-error-list">
      <div class="first-error-list-item">{{ visibleErrors[0] }}</div>
    </div>
  </template>
</FormulateInput>
```

The above slot would be ported inside the `FormulateErrors` component and passed a context object with the visibleErrors merged in with it.

-------------------

Phew — ok, I hope that makes it more clear how it works today? Again, the `errorList` slot does not currently exist, but you can use the `error` slot today to replace the `FormulateErrors` completely.

**Comment by bbugh** [comment]
@justin-schroeder Hi! 👋 I apologize for the slow response, it's been a busy week. Thank you for the thorough explanation and background about my missing piece. A single `context` object as a prop for the form state makes sense and I can see how that would reduce the amount of "subclassed props" (so to speak) that the custom components would have to implement. 

I tentatively believe you that this is a better solution than renderless components. 😄 If you'd like to close this issue for now, we can try our spike again when the `errorsList` slot and the `stack` feature lands. Is there anything I can do to support your effort with these features?

**Comment by justin-schroeder** [comment]
@bbugh awesome, please let me know how it plays out for you and your team on a build, and if there are ways we need to adjust — we will. I actually don’t think adding the component slot to the `errorList` should be too hard, I wanted it to be in the `2.4` push but there were so many moving parts it seemed better to just get that out the door first.

On a related note though, `2.4` did introduce the concept of `slotProps` so our slot component `errorList` could have custom props passed directly into it. Also, per your recommendation, I added an example of a slot component to the documentation.

Pertinent deets here: https://vueformulate.com/guide/inputs/slots/#a-slot-component-example

**Comment by bbugh** [comment]
Hey again. 👋 We're giving this another shot and finding it very difficult (without a **lot** of customizing) to use this library with Bootstrap. 😢 This is mostly due to Formulate's opinionated markup that we've discussed before. Bootstrap requires a lot of specific markup in specific places, and breaks when it's not in the right order or wrappers are present, etc. Before I take the time to make an issue(s) about all the problems we're facing, I wanted to check your intentions with this library. 

Is it intended to be framework-agnostic (e.g. the Bootstrap problems are bugs), or is the intent to use it *only* with utility libraries like Tailwind? Or perhaps is the intent that we would create a full set of custom components for a framework like Bootstrap? Thanks!

**Comment by andrew-boyd** [comment]
Hey @bbugh I can speak to this. The intent of the library is to make form authoring with a Vue component-driven API as easy as it can be. While we don't want to do things to deliberately make libraries such as Tailwind and Bootstrap difficult to use with Vue Formulate, the library is not authored to solve "building forms in Vue with Bootstrap" or any other specific presentational framework. 

Neither @justin-schroeder or I are heavy Bootstrap (or Tailwind) users ourselves, so anything you can provide to help us understand the issues you and your team are facing would be greatly appreciated.
