### ISSUE TITLE
Input event and model sync

### ISSUE THREAD

**Issue by paulogr** [wearebraid/vue-formulate#120]
**Describe the bug**

The model data when used inside a @input callback doesn't have the latest value.

**To Reproduce**

https://codepen.io/paulogr/pen/LYGRbRQ

**Reproduction**

Take a look at the console output and compare the value with the output at screen.

The screen has the latest value, console shows previous value.

Looks like the model is updated after @input event callback is called.

**Expected behavior**

The event callback should be called after model update, with the latest value.

**Information:**
 - Formulate Version 2.3.8

Thank you.

**Comment by justin-schroeder** [comment]
Hey @paulogr.

I _believe_ this is working as intended, but its possible Im wrong — either way its a bit pedantic, although there's no way around it. In your example you're outputting the values of the form's value of a field when the `@input` event fires on that field. At that exact moment the form's value has not yet been updated — it will be changed on `$nextTick` though. Instead, if you use the event payload from the `@input` event you should have the correct value. Or you can watch the form's v-modeled value.

Here's your example using the `$event` payload:

https://codepen.io/justin-schroeder/pen/WNrGZeq?editors=1111

Does that fit what you were expecting a bit better?

**Comment by justin-schroeder** [comment]
@paulogr Ok I think this is now working the way you were expecting in `v2.4.2` 🎉

Here's your codepen updated to `v2.4.2`: https://codepen.io/justin-schroeder/pen/pogdrzY?editors=1111

Thanks!
