### ISSUE TITLE
Being able to add a class to the wrapped input, button, select or textarea

### ISSUE THREAD

**Issue by pimhooghiemstra** [wearebraid/vue-formulate#121]
**Describe the new feature you'd like**
We are using a general set of style rules in our project for buttons. However, at the moment, it seems not possible to add a class to the button[type=submit] when using <FormulateInput> of type 'submit'.

I guess this could be interesting to all wrapped input types such as input, select and textarea.

**Current workaround**
For the moment we could fix this by adding a class on <FormulateInput> itself and add some styling rules by creating a new selector. Or we could drop <FormulateInput> for the submit button and create a button ourselves.

Any thoughts on this matter are much appreciated

**What percentage of vue-formulate users would benefit?**
80%

**Comment by justin-schroeder** [comment]
Hey @pimhooghiemstra.

This feature is nearing release in `2.4`! Checkout this issue #66 which addresses this in depth and includes early documentation about it — in the meantime I'll close this so we can carry on the communication in that issue. If you want to use the early preview for testing a build is available for on the `release/2.4.0` branch

**Comment by pimhooghiemstra** [comment]
@justin-schroeder thanks again for the quick reply. I started reading on issue #66 and it seems your proposal is exactly what we are looking for. The discussion leans a bit to much to Tailwind from my perspective, but if it works for Tail wind, our much simpler situation will be solved also.

I'll just wait for the 2.4.0 release!

Keep up the great work, I love this plugin.
