### ISSUE TITLE
Custom style

### ISSUE THREAD

**Issue by YuliaDimina** [wearebraid/vue-formulate#124]
Hello! I would like to know how to add custom style to input on invalid or true? And one more question - how to add characters @ - . to validation rules?
Thank!

**Comment by justin-schroeder** [comment]
@YuliaDimina you'll be able to add custom classes in `2.4` which is going to be released very soon, see #66. Today you can target styles [via data attributes](https://vueformulate.com/guide/theming/#data-attributes), but you'll have much better control after 2.4 ships.

Not sure what you mean by add `@ -` to validation rules? Which rules?

**Comment by YuliaDimina** [comment]
> via data attributes
Thank you very much for the information! I did not notice this in the manual %) And I already understood a question of validation)
