### ISSUE TITLE
Implement a FormulateForm context object

### ISSUE THREAD

**Issue by hmaesta** [wearebraid/vue-formulate#127]
By default I want the submit button to be `disabled` – and, on a form change, enable it. 

On a native `<form>` all I have to do is `v-on:change="button_disabled = false"`, but that approach doesn't work on `<FormulateForm>`.

**Demo** → https://codesandbox.io/s/vue-formulate-form-onchange-fm9ci

[feature request]

**Comment by justin-schroeder** [comment]
@hmaesta Yeah, so the formulate solution to this we be to have a `context` object for forms that would make this super easy. The idea is you could do this:

**Future:**

```vue
<FormulateForm
  #default="{ hasErrors }"
>
  <FormulateInput
    type="button"
    :disabled="hasErrors"
  />
</FormulateForm>
```

**Today:**

You can do this today though, its just not quite as nice of an API. Here’s your example wired up:

https://codesandbox.io/s/vue-formulate-form-onchange-jp1uf?file=/src/components/Formulate.vue

**Comment by hmaesta** [comment]
Your code example is more than good for me, Justin. Thank you!

**Comment by zenners** [comment]
@justin-schroeder your code example just made my day. I've been trying to sync the vue-formulate form state with a parent component and its children (FormulateForm and MyOwnComponent) with vuex and vue-router (route changes load a different form)

This might help out other people so I'll share relevant code in using the context in FormulateForm
My FormulateForm.vue
```
<template>
  <FormulateForm
    class="login-form"
    v-model="formValues"
    @submit="submitHandler"
    @input="handleDataFc" //
  >
...
</template>
export default {
  name: "CampaignForm",
  props: ["formValues"],
  data() {
    return {
      formValues: this.formValues,
    };
  },
  methods: {
    handleDataFc: function() {
      console.log("handling!!!!");
      this.$emit("interface", this.formValues); // handle data and give it back to parent by interface
    },
  },
};
```
Parent.vue
```
<template>
 <Form
          @interface="changeForm"
          :formValues="getCurrentCampaign"
        />
</template>
created() {
    
    this.$store.dispatch("fetchCurrentCampaign", this.$route.params.id);
  },
 computed: {
    ...mapGetters(["getCurrentCampaign"]),
  },
watch: {
    $route(to, from) {
      this.$store.dispatch("fetchCurrentCampaign", to.params.id);
    },
  },
methods: {
    changeForm(event) {
      this.$store.dispatch("editCurrentCampaign", event);
    },
  },
```

Parent Store.vue
```
const actions = {
...
  fetchCurrentCampaign: ({ commit, state }, data) => {
    CampaignService.getCampaignById(data)
      .then((res) => {
        commit("setCurrentCampaign", res.data);
      })
      .catch((err) => {
        console.log("error", err);
      });
  },
  editCurrentCampaign: ({ commit, state }, data) => {
    commit("editCurrentCampaign", data);
  },
};

const mutations = {
  ...
  setCurrentCampaign: (state, data) => {
    console.log("in set current campaign", data);
    state.currentCampaign = data;
  },
  editCurrentCampaign: (state, data) => {
    console.log("in set edit campaign", data);
    state.currentCampaign = data;
  },
};

**Comment by justin-schroeder** [comment]
Nice work! you know its funny, the original genesis for vue formulate was syncing forms to vuex (several years ago). I had a very very early version of Vue Formulate (still in production on a number of sites) that was entirely built around that vuex syncing. It turned out the best features of that package were not the vuex sync but the inputs and data flow, so thats got re-written into what is Vue Formulate today.  Someday i may revist the vuex sync idea. If youre interested in that history haha, here's the original ancient version of Vue Formulate: https://github.com/wearebraid/vue-formulate-legacy

**Comment by zenners** [comment]
yeah i saw the old repo but i couldn't put the two together. The @input really was the missing link. I've been at it for 2 days and was opening every issue to look for possible clues.

**Comment by justin-schroeder** [comment]
This is now in `release/2.5`, early docs here:

https://vueformulatecom-git-release-250.braid.now.sh/guide/forms/#context-object
