### ISSUE TITLE
How to use slot components to customise an element/input slot

### ISSUE THREAD

**Issue by axwalker** [wearebraid/vue-formulate#130]
**Describe the new feature you'd like**
Documentation on how to use slot components to customise an element/input slot

**What percentage of vue-formulate users would benefit?**
10%

**Context**

I have some plain HTML markup with tailwind classes for an email input that I want to use with vue-formulate. I've successfully used slot components to handle label/help slots - ie setting `slotComponents` when in the initial configuration to my custom components that use the `context` prop. I'm a bit unsure of the best approach when it comes to the actual input element slot though. This is the initial markup I have:

```html
<div class="mt-1 relative rounded-md shadow-sm">
  <input
    id="email"
    class="form-input block w-full sm:text-sm sm:leading-5"
    placeholder="you@example.com"
    aria-describedby="email-description"
  />
</div>
```

If it weren't for the containing div I could consider globally setting the input classes. However, I'm also likely to want to add other things alongside the input element itself - for example, an svg icon inside the containing div. It seems like slot components are the right approach here. I'm just not sure of a few things:

- should I be looking at the element slot or the input slot here?
- do I use a different `slotComponent` entry for each of the email/text/etc input types that I'll be doing this for? Or do I look at `context.type` within my single input component? 
- are slot components even the right thing to use here?

Seems like something that may fit well in the documentation? If not, is this the best place for me to be asking this or is there somewhere else I can get some guidance?

---

Thanks a lot - enjoying the library overall so far.

**Comment by axwalker** [comment]
Another example of something I'd want to do involving a slot component for the `element` slot:

![input-prepend-text](https://user-images.githubusercontent.com/6277658/85208054-4fab2700-b325-11ea-9552-eee87750b9b0.png)

To be able to get this with something like:

```html
<FormulateInput
  label="Company Website"
  prepend-text="http://"
/>
```

**Comment by justin-schroeder** [comment]
Solid questions @axwalker. A few things that might be helpful.

1. The slot `context` object contains a `classes` object with the prepared classes to use on your custom slots, so if you want to continue to use the Vue Formulate class mechanism on custom slots you can. For example:

```vue
<div :class="context.classes.element">
  <input
    id="email"
    :class="context.classes.input"
    placeholder="you@example.com"
    aria-describedby="email-description"
  />
</div>
```

2. As for putting things alongside your custom input. I'm still trying to determine the best way to do this in core itself. I might look like #98 with prefix/suffix slots, or it might look something like your `prepend-text`. However, if you wanted to do this on your own custom components you could implement your own `slotProps` to implement this functionality today on your own projects. I love the idea of having a super easy api like `prepend-text` or `prepend-icon` assuming expose some way to load an icon library, but I know people are going to want to put literally anything in those slots — dropdowns and other complex UI elements so I know it can't stop at just props.

Does this help answer your questions? I'd be interested to hear any suggestions you might have for a prefix/suffix API.

**Comment by axwalker** [comment]
1. Are you referring to a scoped slot here or a slot component? I wasn't able to actually to set the slot component for either the `element` or `default` slot , ie:

```js
Vue.use(VueFormulate, {
  slotComponents: {
    element: 'my-element-component',
    input: 'my-input-component',
  },
}
```

From digging through the source a bit, I wasn't sure that this was meant to be available or not. [There is no no `:is="context.slotComponents.element"`](https://github.com/wearebraid/vue-formulate/blob/master/src/FormulateInput.vue#L35), for example. Should I be able to make an `element` slot component?

2. I'd be happy to implement my own `slotProps` for stuff like `prepend-text` and `prepend-icon` if I'm able to get the `element` slot working. As far as a more a general `prepend-icon` API, I also happen to have recently being working on a Vuetify project like the author of the issue you linked. Part of the reason I moved over to Tailwind here was because I wanted more control over UI aspects. You can see Vuetify's API [here](https://vuetifyjs.com/en/components/text-fields/#api) - they have both props and slots for prepending/appending stuff. I think the awkward part could be loading the icon library. For some reason, I've had enough trouble just getting a decent icon setup in isolation of everything else, let alone in conjunction with other libraries.

**Comment by justin-schroeder** [comment]
Ah yeah, sorry, this might not be well detailed in the documentation, but to override the core element for an input type, you override the component in the library option itself:

```js
Vue.use(VueFormulate, {
  library: {
    text: {
      component: 'CustomInput'
    }
  }
})
```

That said, if you're doing this you might consider just creating a custom input for yourself:

```js
Vue.use(VueFormulate, {
  library: {
    mytext: {
      classification: 'text',
      component: 'CustomInput'
    }
  }
})
```

When using the default component slot, you cannot define `slotProps` but you'll find any undefined props you pass in available in `context.attributes`. 

-------

As for the API — thanks for the pointers. Im going to keep stewing on it. I'd like it to be even easier to use the vuetify...

**Comment by axwalker** [comment]
Ah, great. That's opened up a lot for me.

For anyone else in my position - with buttons I'm now able to just use my own button component I'd already created (`t-button`):

(partially taken from [the original `FormulateInputButton`](https://github.com/wearebraid/vue-formulate/blob/master/src/inputs/FormulateInputButton.vue))
```html
<!-- source for t-input-button -->
<template>
  <t-button
    :data-type="context.type"
    :type="context.type"
    v-bind="attributes"
    @click="$emit('click', $event)"
  >
    {{ context.value || context.label || context.name || 'Submit' }}
  </t-button>
</template>

<script>
import FormulateInputMixin from '@braid/vue-formulate/src/FormulateInputMixin'

export default {
  mixins: [FormulateInputMixin],
}
</script>
```
with config:

```js
Vue.use(VueFormulate, {
  library: {
    submit: {
      component: 't-input-button',
    },
    button: {
      component: 't-input-button',
    },
  },
}
```

And now I'm able to do things like:

```html
<FormulateInput type="button" label="Create something" color="white" />

<FormulateInput
  type="submit"
  label="Something else"
  color="secondary"
  trailing-icon="cog"
/>
```

Which uses my own `t-button` props like `color` and `trailing-icon`. Results:

![Button images](https://user-images.githubusercontent.com/6277658/85393722-5ca66100-b545-11ea-950f-79cc3f74507f.png)

---

Will see if any further issues arise when doing similar things for other input types. Thanks a lot for your help!

**Comment by justin-schroeder** [comment]
That’s awesome @axwalker. Love what you’ve come up with there.

**Comment by justin-schroeder** [comment]
One other thing to note on this @axwalker is the button type actually uses the default slot for internal content:

https://vueformulate.com/guide/inputs/types/button/
