### ISSUE TITLE
Not able to set the full width of the input field directly on the class (wrapper-class/outer-class)

### ISSUE THREAD

**Issue by Rednas83** [wearebraid/vue-formulate#133]
Not sure whether this is a bug or expected behavior. But I at least think it requires explanation to make things a little bit more clear.

**Expected to set the input field to max width directly**
class="w-full"
input-class="w-full"
class="w-full max-w-full"

**...but in fact I had too change the element-class instead**
element-class="w-full"

What is the idea of the element-class and why is not set to full width on default?

**Comment by justin-schroeder** [comment]
I think you're probably mixing the snow theme and tailwind. Can you produce a reproduction in a codepen please?

Here's a ready-to-use VueFormulate one: https://codepen.io/boyd/pen/YzyJPor

**Comment by Rednas83** [comment]
Hereby:
https://codepen.io/rednas83/pen/ExPXyyK

I am indeed using the snow theme and tailwind. 

Perhaps also an extra question. How can you set the font of the input field to bold (class="font-bold")?

**Comment by justin-schroeder** [comment]
Hmm, that codepen didn't have tailwind on it. I don't recommend mixing tailwind and the snow theme. Those two themes are "philosophically" opposed. Once you install the tailwind stylesheet I think you'll see things are working the way you expect.

**Comment by Rednas83** [comment]
Where can I download the tailwind stylesheet?
The only theme that I can find is the snow theme of 9 months old.

**Comment by justin-schroeder** [comment]
The snow theme is the only theme vue formulate ships with. Tailwind is not a theme, its a ui library that you can use to create your own theme. You can read about how to use it here and download style sheets here:

https://tailwindcss.com

Here's my article on the subject:

https://dev.to/justinschroeder/tailwind-vue-formulate-24k1

**Comment by Rednas83** [comment]
I have no time to write my own theme.
For now I wil mix with snow and wait for other themes.

**Comment by andrew-boyd** [comment]
@Rednas83 the idea behind Tailwind is that you wouldn’t write your own theme. You’d apply their pre-existing classes to create your desired look. The article @justin-schroeder linked provides some great examples of that approach. 

Good luck!
