### ISSUE TITLE
Tabbing form fields on mobile device skips dropdowns and radio buttons groups

### ISSUE THREAD

**Issue by pimhooghiemstra** [wearebraid/vue-formulate#134]
**Describe the bug**
On mobile (e.g., android phone) 'tabbing' with the device's keyboard '->' button skips `<select>` and `<input type="radio">` form elements

**To Reproduce**

0. On a mobile (Android) device
1. Go to https://dev.plint-sites.nl/diensten/webdesign
2. Scroll to bottom of page, click on green button 'offerte aanvragen'
3. Focus on first field (naam *) => the device's keyboard pops up
4. At the bottom right corner of the device's keyboard click the -> button to jump to the next form field
5. Both the radio button group (Hoe kunnen we je bereiken) and the dropdown (onderwerp) are skipped

**Reproduction**
It's hugely helpful if you can isolate the bug in a CodePen. You can use VueFormulate via CDN to show the issue. This isn't a requirement just a big productivity boost.

I am sorry I don't have a pen ready.

**Expected behavior**
Tabbing using the tab key on the device's keyboard I would expect to be able to jump from one field to the next without fields being skipped. Please note I am using tabindices on my form fields.

**Device information:**
 - Device: Sony Xperia XA2
 - OS: Android 9
 - Browser: Chrome
 - Version: 83.0.4103.106

**Comment by justin-schroeder** [comment]
I checked it out on another android device, and confirm it's an issue. However, its not a Vue Formulate specific issue. From what I can gather android's "next" key is not a "tab" key, and doesn't follow proper flow. It only moves to the "next" keyboard enabled field, which select lists and checkboxes are not. Pretty lame.

Not sure there's much we can do about this, but if you have a proposed solution to the android issue feel free to propose it here and I'll open this back up. Sorry mate!
