### ISSUE TITLE
Set the default value in "select"-FormulateInput ?

### ISSUE THREAD

**Issue by egwald** [wearebraid/vue-formulate#136]
It is possible to set the default "selected" value in the FormulateInput  type="select"

**Comment by justin-schroeder** [comment]
Hi @egwald,

Yep no problem. There are a number of ways to set the default value. You can use:

- v-model
- value prop
- [FormulateForm](https://vueformulate.com/guide/forms/#setting-initial-values)

Documentation about this is here:

https://vueformulate.com/guide/inputs/#setting-an-initial-value

This works for all input types.

```vue
<FormulateInput
  type="select"
  :options="{
    apple: 'Apple',
    pear: 'Pear',
    strawberry: 'Strawberry'
   }"
  value="pear"
/>
```

**Comment by egwald** [comment]
Thanks a lot.
"Using the |value| prop", it helps if you can read. ;-)

Am 26.06.20 um 15:36 schrieb Justin Schroeder:
