### ISSUE TITLE
JSON-Schema support?

### ISSUE THREAD

**Issue by goschtl** [wearebraid/vue-formulate#144]
**Describe the new feature you'd like**
Hey,

what do you think of generating forms out of an standard JSON-Schema.
I think we could maybe extend the Generator to use this Format.
I am not sure how we could deal with UI stuff for fields like placeholder, title, description etc.. in that
solution.

What do you think about it.?

Christian

**What percentage of vue-formulate users would benefit?**
40%

**Comment by justin-schroeder** [comment]
@goschtl I think its a great idea! Especially a great idea for a user-contributed plugin. Right now the schema parser does not have an explicit hook system to allow realtime schema modification but I'd like this to change based on work happening in #135.

Would you be interested in producing a plugin to support the spec?

**Comment by justin-schroeder** [comment]
I'm going to close this for now, but follow #135 and once that's complete I'd love to see a plugin for this 😉
