### ISSUE TITLE
Error behavior like "live" mode but only after the value has changed

### ISSUE THREAD

**Issue by bbugh** [wearebraid/vue-formulate#150]
**Describe the new feature you'd like**

Hi 👋 we have an app that has a lot of calculator-like utility forms. Our users use these forms to play with numbers and get immediate feedback about how it will affect their financials. During UX discovery, we found that people strongly prefer immediately live validation (oninput instead of onblur), but only after the user has interacted with the field. This is how Excel works and most of our users are coming from spreadsheets. 

We don't want the user to load a page with a bunch of red exclamations on it, so something between `'error-behavior': 'blur'` and `'error-behavior: 'live'` would be useful. Maybe something like `'error-behavior': 'has-validated'`?

Thanks for considering!

**Comment by justin-schroeder** [comment]
Not a bad idea @bbugh. I’ll look into that. In the meantime you could use error-behavior live and hide the errors when the field has no value. This would be trivial with a dash of css using the already existing `data-has-value` attribute.

**Comment by bbugh** [comment]
Thanks for the idea. Since we use bootstrap there's a lot of edges we'd have to disable (like an icon, and a red highlight when selecting the input) so it's not feasible for us, though. 

![image](https://user-images.githubusercontent.com/438465/86533085-2695a500-be94-11ea-81ac-20fd6dc1d529.png)

**Comment by justin-schroeder** [comment]
@bbugh this is now implemented in `release/2.5.0` as a new `error-behavior` named `value`. This will show errors immediately if the input _has_ an initial value. If it does not have an initial value, it waits to the field has been blurred or has had a value.
