### ISSUE TITLE
How to "V-model". repeatable group type ? 

### ISSUE THREAD

**Issue by thunderwin** [wearebraid/vue-formulate#154]
**Describe the new feature you'd like**

If I would edit a form who is include a group type form field.    how can I inject multiple group fields for editing?  should I use a v-model?   cause it only shows one field. when you edit it.

also. group type field submit a wired look obj key..    what is the  "group_formulate--admin-landingPage-edit-55" ???   
 
     {
        backgroundColor: "#3eaf7c",
        subTitle: "1212",
        title: "1212",
        "group_formulate--admin-landingPage-edit-55": [
          {
            title: "水电费水电费",
            subTitle: "水电费水电费",
            content: "水电费水电费"
          },
          {
            title: "水电费水电费",
            subTitle: "水电费水电费",
            content: "水电费水电费"
          }
        ]
      };

**Comment by justin-schroeder** [comment]
@thunderwin Yes, make sure the group `FormulateInput` has the prop `:repeatable="true"`. In you example I can see the group does not have a `name` prop either, I would really encourage you use that. Then you can use either `v-model` or `:values` (either is fine) to apply an array of fields to your.

For example: 

https://codepen.io/justin-schroeder/pen/pogaXdw

Also @thunderwin, if you'd like to contribute a Chinese translation I would be forever grateful 😉
