### ISSUE TITLE
Using Vue.Draggable (or allow for dragging) for groups

### ISSUE THREAD

**Issue by engram-design** [wearebraid/vue-formulate#156]
**Describe the new feature you'd like**
Please steer me in the right direction is this is possible now, but from my testing, I don't believe so. I'm using the group input as a table field, something similar to the:

<img width="758" alt="Screen Shot 2020-07-07 at 1 21 07 am" src="https://user-images.githubusercontent.com/1221575/86610056-27434e00-bff0-11ea-9340-b6c38934b497.png">

Everything works fine apart from dragging items. I've been using [Vue.Draggable](https://github.com/SortableJS/Vue.Draggable) in the past which works fine. I'd rather use Formulate's add-new behaviour and validation, so I'm using it purely for dragging. Something like this won't work:
```
<FormulateInput
    #remove="{ removeItem }"
    v-model="context.model"
    name="options"
    type="group"
    :repeatable="true"
>
    <draggable handle=".move.icon">
        <div class="flex">
            <FormulateInput type="text" name="label" />
            
            <slot name="remove">
                <a class="move icon"></a>
                <a class="delete icon"></a>
            </slot>
        </div>
    </draggable>
</FormulateInput>
```
Because its wrapping each row in a draggable item, essentially only providing drag functionality with itself. Placing it outside the `FormulateInput` won't work either, because that just wraps all repeater items.

Ideally, it'd be great to be able to wrap the repeatable content as per the below output from a repeating group field:
```
<div data-classification="group" data-has-value="true" data-type="group" class="item flex formulate-input">
  <div class="formulate-input-wrapper">
    <div data-is-repeatable="true" class="formulate-input-element formulate-input-element--group formulate-input-group">
      <div force-wrap="true" class="formulate-input-grouping">

        <!-- Add draggable wrapper here -->
        <div class="formulate-input-group-repeatable"></div>
        <div class="formulate-input-group-repeatable"></div>
        <!-- Add draggable wrapper here -->

        <div class="formulate-input-group-add-more">
          Add an option
        </div>
      </div>
    </div>
  </div>
</div>
```
I'm not sure on your desired approach here - I'd assume keeping out dragging functionality from the library, as its pretty specialised. Can you think of a way to wrap the repeatable items? I've tried messing around with the available slots, without much luck. Just interested to know if its just not possible at all. I also considered a custom group input type, but from other issues, that's been advised against.

**Comment by justin-schroeder** [comment]
As far as I can tell, there are 2 challenges to making this work:

1. You need direct access to the model so you can slice the array at will.
2. You need to wrap the repeatable providers.

The slot provided to handle both of these is `grouping`. As you already found out from another issue, it's not the easiest to use, but its here for this exact reason if someone is up for the task :) If you take a look at the `FormulateGrouping.vue` file you'll see that the root element of the template is a `<FormulateSlot>`. So you by defining the `grouping` slot you remove all the `<FormulateRepeatableProvider>` logic. This allows you to easily wrap the repeatable items, but also requires you re-implement/define the `<FormulateRepeatableProvider>` logic. This could be done though! It's just a chunk of work to make it happen.

**Comment by engram-design** [comment]
I think point 1. will be okay - at least in theory for my setup. I'll give the `grouping` slot another go - I did try it initially without much luck, but with your pointers, I'll give it another crack!

Either way, I think this can potentially be achieved through custom development - unless you see any issues otherwise? If so, happy to close this issue, and I can share a hopefully final working result.

**Comment by engram-design** [comment]
Okay @justin-schroeder you're totally right, this is possible as-is!

For anyone else maybe looking for a solution:
```
<FormulateInput
    v-model="context.model"
    name="options"
    type="group"
    :repeatable="true"
>
    <template v-slot:grouping>
        <draggable v-model="context.model" handle=".move">
            <FormulateRepeatableProvider
                v-for="(item, index) in items"
                :key="item.__id"
                :index="index"
                :set-field-value="(field, value) => setFieldValue(index, field, value)"
                :context="context"
                @remove="removeItem"
            >
                <slot></slot>
            </FormulateRepeatableProvider>
        </draggable>
    </template>

    <template v-slot:repeatable="{ removeItem: removeRow }">
        <div class="flex">
            <FormulateInput type="text" name="label" />

            <a class="move">Move</a>
            <a class="delete" @click.prevent="removeRow">Delete</a>
        </div>
    </template>
</FormulateInput>
```

As @justin-schroeder mentions, you'll need to rip out a few functions from `FormulateGrouping.vue` such as `items()` `getAtIndex()`, `setFieldValue()` and `removeItem()` (possibly more).

Maybe I'm just a JS noob, but it seems the only way to get `setId` is to import it like:
```
import { setId } from '../node_modules/@braid/vue-formulate/src/libs/utils';
```

Is that correct, or is there a better way?
