### ISSUE TITLE
Docs: working example of custom validation rules 

### ISSUE THREAD

**Issue by codekiln** [wearebraid/vue-formulate#162]
After reading [Custom validation rules](https://vueformulate.com/guide/validation/#custom-validation-rules), I was still struggling to get custom validation rules working in my project. I searched around Justin's codepens, and sure enough, I found [a codepen "Vue Formulate — Validation Dependencies"](https://codepen.io/justin-schroeder/pen/ExPagor) that helped me put together how it works if you aren't ready to add a new rule to the global config. 

Please consider adding a working example to the docs for [Custom validation rules](https://vueformulate.com/guide/validation/#custom-validation-rules) for field-specific dependencies, or just link to [a codepen "Vue Formulate — Validation Dependencies"](https://codepen.io/justin-schroeder/pen/ExPagor)!

**Comment by justin-schroeder** [comment]
@codekiln isn't this a working example? Or did you have something more detailed in mind?

![image](https://user-images.githubusercontent.com/1950463/86835658-6b733480-c06a-11ea-8a63-46f9b14c425a.png)

**Comment by codekiln** [comment]
Indeed, you are right; now that I see how to do it, I understand that everything's put together in your quoted example.

I didn't immediately see how to translate that into what I needed to do to pass a reference to one of my component's `methods` functions, which was clearer to me in "Vue Formulate — Validation Dependencies." Also, having an example of using the function arguments to more completely customize the message and rules was useful to me there. 

It would be helpful to have a few examples, to know what's possible. For example, how would I reference the label of a field whose name was given in an argument in a message, e.g. "This value must be less than ${compareToLabel}." ?

**Comment by justin-schroeder** [comment]
We now have a more fleshed out community page, including a (hopefully growing) list some examples:

https://vueformulate.com/guide/community
