### ISSUE TITLE
Add phone input

### ISSUE THREAD

**Issue by EugeneVaida** [wearebraid/vue-formulate#167]
please add this input type for phone validation, use your forms for my project but it will be ideal instrument for me if there will be input for phone as it made with email. 
Some examples of implementations https://github.com/LouisMazel/vue-phone-number-input
Or have a possibility to integrate custom elements to your forms

**Comment by gahabeen** [comment]
@EugeneVaida I'd recommend you to check out the doc to use your custom input.
https://vueformulate.com/guide/inputs/custom-inputs/#structure-of-an-input

**Comment by justin-schroeder** [comment]
@EugeneVaida. I agree it would be awesome to see a phone number input! However Vue Formulate's core doesn't expose any non-native inputs. Phone numbers inputs are not natively supported by HTML, and there's actually some debate as to the best way to implement them ([for example, this article](https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/)).

However, like @gahabeen mentioned its quite easy to create your own input types, you could even use vue-phone-number-input with Vue Formulate. Best of luck!
