### ISSUE TITLE
Inside input group, formValues, getFormValues params to custom validation functions return empty objects

### ISSUE THREAD

**Issue by codekiln** [wearebraid/vue-formulate#168]
**Describe the bug**
When a custom validation rule or message function is executed within the context of `<FormulateInput type="group"`, that function is passed `getFormValues()` or `formValues`, however the return value from `getFormValues()` and the value of `formValues` is `{}`.

**To Reproduce**
Bug reproduced: https://codepen.io/codekiln/pen/MWKGxrj 
* go to console
* note that both `getFormValues()` and `formValues` supplied to custom validation are `{}`

Normal behavior: https://codepen.io/codekiln/pen/JjGvzxZ
* Without using a `<FormulateInput type="group"`, both the return value `getFormValues()` and `formValues` are the anticipated values.

Codesandbox with more involved example, closer to how I discovered this: [MinMaxGroup](https://codesandbox.io/s/vue-formulate-nested-groups-m18ff?file=/src/components/MinMaxGroup.vue:384-430)

**Expected behavior**
* `getFormValues()` should return the values in the group or the entire form
* `formValues` should contain the form values in the group or the entire form

**Screenshots**
![image](https://user-images.githubusercontent.com/140930/87077180-bdde5d80-c1f0-11ea-841d-8593ff41d8be.png)

**Device information:**
https://assets.codepen.io/15253/formulate-latest-bootstrap.js

**Comment by justin-schroeder** [comment]
Hmm. They should return the value of the items in the group itself. I'll take a look at this.

**Comment by justin-schroeder** [comment]
This is now fixed and published in `v2.4.3`. Thanks @codekiln.
