### ISSUE TITLE
Library does not work in IE11

### ISSUE THREAD

**Issue by onelifenyc** [wearebraid/vue-formulate#17]
Library breaks in IE 11 - See screenshot

**To Reproduce:** 
Visit vueformulate.com > Open F12

![image](https://user-images.githubusercontent.com/4038782/76106302-922e3b00-5fa4-11ea-9b43-bdedc909ceb1.png)

**Comment by onelifenyc** [comment]
Seems related to: https://github.com/vuejs/vue/issues/6917
Please advise of possible patch please.

**Comment by justin-schroeder** [comment]
Hi @onelifenyc. As of today, Vue Formulate does not support IE11. With Vue3 on the way (and not supporting IE11) we're weighing the pros/cons of adding polyfills for all of the missing features in IE11, and the impact that would have on bundle size for all the other users who dont need IE11 support.

There is a legacy version of Vue Formulate with quite different bindings (exclusively uses vuex) that does support IE11 here: https://github.com/wearebraid/vue-formulate-legacy#readme

I'll leave this ticket open for now as we investigate those edge cases.

**Comment by Christoph-Wagner** [comment]
Okay, I need IE11 support (1-3% IE11 depending on if it’s a work day), so I had a look.

As far as I can see the only problem with IE11 is a [longstanding vue bug](https://github.com/vuejs/vue/issues/8379) that you can’t use dynamic type fields and use both `value` and `v-model`.

So changing in `FormulateInputbox.vue`

```vue
<input
      v-model="context.model"
      :type="type"
      :value="context.value"
      v-bind="attributes"
      @blur="context.blurHandler"
    >
```

to the slightly more verbose 

```vue
<input
      v-if="type === 'radio'"
      v-model="context.model"
      type="radio"
      :value="context.value"
      v-bind="attributes"
      @blur="context.blurHandler"
    >
<input
      v-else
      v-model="context.model"
      type="checkbox"
      :value="context.value"
      v-bind="attributes"
      @blur="context.blurHandler"
    >
```

seems to fix the IE11 compatibility.

**Comment by justin-schroeder** [comment]
@Christoph-Wagner ok, looking into this, thanks for digging that issue up.

**Comment by justin-schroeder** [comment]
@Christoph-Wagner so i've got this working in a branch, although polyfills were still required for IE11 (you might already have them since you're supporting them) I used:

https://polyfill.io/v3/polyfill.min.js?features=es2015

And that worked with the fix you indicated, I've pushed this on the [bugfix/ie11 branch](https://github.com/wearebraid/vue-formulate/tree/bugfix/ie11).

The issue i'm having with that build is error messages/locales don't appear to be working ie11. It's always using the fallback ("The field is invalid"). Unfortunately – no errors.

![ie-vs-chrome](https://user-images.githubusercontent.com/1950463/77179880-8449e100-6a9f-11ea-998d-2dbd3e0e84a2.png)

**Comment by Christoph-Wagner** [comment]
Okay, IE11 

a) doesn’t support `function.name` 
b) even with string parsing sees `required: function(…` as nameless and requires `required: function required (…` instead.

So unless there is some kind of configurable function-name expander plugin, I’d say it’s not worth it. My personal IE11 support level is "The site doesn’t break and is somewhat usable". Which is the level it’s at with the current fix.

**Comment by justin-schroeder** [comment]
Haha, so as you were replying I was just pushing up a fix for the `function.name` to the branch. You were 100% right, thanks for digging into that too. The validation messages are now working properly in ie11 🎉

To make it work I removed `function.name` completely and instead now pass around the validation rule name explicitly.

**Comment by justin-schroeder** [comment]
This is fixed in [`v2.2.5`](https://github.com/wearebraid/vue-formulate/commit/fa26a24fa7999e39b48d9da359794d7051f53d91)

**Comment by onelifenyc** [comment]
Thanks for fixing this 
But when testing this fix, did you guys notice this issue with the icon for upload CSS / has to be svg issue in IE11.

![image](https://user-images.githubusercontent.com/4038782/77487223-48e54480-6e08-11ea-9b1a-ac817a881028.png)

**Comment by justin-schroeder** [comment]
Yes, and there are a few other css/snow theme related issues in ie11. Open to a PR for those!
