### ISSUE TITLE
Global class keys: is `fileImage` really being used?

### ISSUE THREAD

**Issue by hmaesta** [wearebraid/vue-formulate#170]
On [Inputs > File > Custom class keys](https://vueformulate.com/guide/inputs/types/file/#custom-class-keys) there are:

- `fileImage`
- `fileImagePreview`

Both using `formulate-file-image-preview` class as default.

First of all... What's the difference between them? And is `fileImage` really being used somewhere? I can't find it.

### 👍 Expected behavior 
I expected that the classes pointed on `fileImage` would be applied to the preview image `<img>`

### 👎 What really happens 
I can't find the classes I pointed on `fileImage`

### 🔍 How to reproduce 
1. On Vue Formulate global classes set `fileImage` with the content: `"WHERE_IS_THIS_APPLIED"`, like:

```js
Vue.use(VueFormulate, {
  classes: {
    fileImage: "WHERE_IS_THIS_APPLIED"
  }
});
```

2. Create a `FormulateInput` type `image`
3. Upload it and look for the `WHERE_IS_THIS_APPLIED` class

Or just click below:

⚒  **Sandbox** →  https://codesandbox.io/s/vue-formulate-fileimage-used-7j0lg

**Comment by justin-schroeder** [comment]
You're spot on @hmaesta I think that's a documentation oversight. There is no `fileImage` — it looks like you've got `fileImagePreview` working, but ya. That should be removed from the documentation!

**Comment by justin-schroeder** [comment]
Ok, I removed `fileImage`. Thanks! 👍

**Comment by hmaesta** [comment]
I was about to make a PR but you already did it 👏 

Ps: opened a feature request related to this, but **totally not** a priority since there's a _not so bad_ workaround. https://github.com/wearebraid/vue-formulate/issues/172
