### ISSUE TITLE
On a repeatable group, "Remove" should be translated

### ISSUE THREAD

**Issue by hmaesta** [wearebraid/vue-formulate#173]
If using [vue-formulate-i18n](https://github.com/wearebraid/vue-formulate-i18n), the **Remove** label of a repeatable group should be translated to current locale.

Right now it's hardcoded.

https://github.com/wearebraid/vue-formulate/blob/c6ffe1995be0df608c9c735186f4158662449fc8/src/slots/FormulateRepeatableRemove.vue#L2-L9

And, maybe as a breaking change, `<a>` should be replaced by a  `<button>` – since there isn't a change of page or view.

**Comment by justin-schroeder** [comment]
That's true @hmaesta...currently we don't have any non-message language strings at all (except this one apparently). I really want to avoid adding one, but for accessibility it's important. Maybe we should just make this label a prop value so people can change it using their own `$i18n` instance?

**Comment by hmaesta** [comment]
The PR was accepted and the docs were updated. Closing. 

For people of the future: use `remove-label` 🙂
