### ISSUE TITLE
Custom Validation rule works only with `:validation-rules={...}`

### ISSUE THREAD

**Issue by leorossi** [wearebraid/vue-formulate#178]
**Describe the bug**
Following the example at https://vueformulate.com/guide/validation/#custom-validation-rules I cannot reproduce the behavior

**To Reproduce**
1. Go to https://codepen.io/leonardorossi/pen/ExPeYwM
2. Remove `:validation-rules={}` (line 9)
3. See error in console

**Expected behavior**
`myFunction` should be called as the example

**Screenshots**

It is not clear where to put the custom function. I put that in `methods` but it doesn't work without using `:validation-rules`
![Screenshot 2020-07-14 at 09 18 36](https://user-images.githubusercontent.com/604220/87396422-1c218c80-c5b3-11ea-83ac-465f6e106ee3.png)

**Comment by andrew-boyd** [comment]
Hey @leorossi! I agree that the docs could be more clear in this case. The introduction to validation rules is being rather abstract in its explanation. If you want to register a validation rule without including its definition inline on the form element (as you are doing in your Codepen example) then you’ll need to register it globally. If you follow the structure in the docs around registering global validation rules you should be set.

https://vueformulate.com/guide/validation/#global-custom-validation-rules

**Comment by leorossi** [comment]
Thanks @andrew-boyd now it is more clear 👍
So it is not possible to define a validation rule in the current component (like in `methods` object?)

**Comment by codekiln** [comment]
@leorossi You can define a validation rule in the current component in the `methods` object; you just have to pass that method to the `validation-rules` prop as well. See [Custom validation rule (multi-field)](https://codepen.io/justin-schroeder/pen/ExPagor) for an example.  This example comes from the [Examples in the docs](https://vueformulate.com/guide/community/#examples). If you don't want to use `validation-rules` prop, then you have to define it globally.

**Comment by leorossi** [comment]
Ok now it's clear, thanks @codekiln !
