### ISSUE TITLE
Extend FormulateErrors for formErrors classes

### ISSUE THREAD

**Issue by malydok** [wearebraid/vue-formulate#180]
Hey, thanks for the lib, feels great to use so far.

I'm using it with Tailwind and stumbled upon the issue where I cannot style `FormulateErrors` for form errors.

Looking at `src/FormulateErrors.vue` it looks like the context classes are only used in case of input errors.
Could we perhaps extend the context classes to include `formError` and `formErrors` and add support for those here?

I might file a PR later when I have some time to set up the test env.
Edit: can't figure this out on my own, help appreciated.

Cheers!

**Comment by hacknug** [comment]
I'd also like to be able to add classes to `FormulateForm` and corresponding slots.

**Comment by justin-schroeder** [comment]
`FormulateForm` should just inherit classes like normal `<FormulateForm class="my-class">`. I agree that `FormulateErrors` needs some targeting for tailwind. I'll mark this on the roadmap.

**Comment by hacknug** [comment]
> `FormulateForm` should just inherit classes like normal `<FormulateForm class="my-class">`.

Yeah but it'd be super useful to be able to keep all of formulate's classes on the same file and then only use `[class]` for instance-specific styling. This has also been requested in #235 so I'll leave this issue for `FormulateErrors` and we can continue discussing the form there.

**Comment by justin-schroeder** [comment]
I agree actually. we'll try to do this.

**Comment by justin-schroeder** [comment]
This is now ready in `release/2.5.0`. Early WIP docs here:

https://vueformulatecom-git-release-250.braid.now.sh/guide/theming/customizing-classes/#class-keys

**Comment by hisuwh** [comment]
@justin-schroeder the docs seem to wrong for this.  I had to specify `formErrors` rather than `form-errors` in my global config to make this work

**Comment by justin-schroeder** [comment]
Yeah, @hisuwh I agree it's kinda confusing how vue does this imo. The class key is `form-errors` because that is the prop prefix, but vue automatically camelCases all props, so when used in configuration it's `formErrors`. Would be happy to accept a docs PR for a note about that if you think it warrants it.

**Comment by hisuwh** [comment]
I can do that.  Should the main example be changed though?  Global config seems like the more common use case here, then can caveat the other way?

**Comment by justin-schroeder** [comment]
it's a good question — honestly im not sure which people use more often, but I would suspect props. Honestly though im fine with either/or — I'll leave it up to you 👍

**Comment by hisuwh** [comment]
if you set this everywhere with props rather than globally once you're a psychopath in my opinion 🤣
But happy to do whatever

**Comment by hisuwh** [comment]
@justin-schroeder done.  Followed the pattern for state-keys below it
https://github.com/wearebraid/vueformulate.com/pull/112
