### ISSUE TITLE
Add `getGroupValues` to retrieve siblings for validation functions in groups.

### ISSUE THREAD

**Issue by codekiln** [wearebraid/vue-formulate#181]
Currently (v2.4.3), when making [custom validation rules](https://vueformulate.com/guide/validation/#custom-validation-rules) that will operate upon inputs inside of groups, the validation functions are only passed `value`, `getFormValues` and the `name` of the input. This information alone is insufficient to triangulate where the `value` and `name` parameters come from inside of the dict returned from `getFormValues` in the case of a nested group. 

For example, consider this test case - [Codesandbox - Vue Formulate Min Max Groups](https://codesandbox.io/s/vue-formulate-nested-groups-m18ff?file=/src/components/MinMaxGroup.vue). When the validation is fired, the `compare` and `compareMessage` function are passed a value of "1" and a name of "min" and formValues of: 

```
formValues: {
  "g": [
    {
      "min": "1",
      "max": "5",
      "g": [
        {
          "min": "1",
          "max": "3"
        }
      ]
    }
  ]
}
```
There's no way to know whether it's the "min" of "1" in the outer or inner group. Or, if formValues was much larger, whether it was a value in any nested array.

One proposal would be to hand an address to the function. For example, say that this particular validation is for the inner 1. Then it would be passed [`jsonPath`](https://goessner.net/articles/JsonPath/) of `$.formValues.g[0].g[0].min`. 

I tried to work around this by obtaining the index from the group, but this index number is not exposed to the component in any way I can find. Do you have any suggestions / workarounds for this limitation? My actual use case is quite similar to the one listed in the code sandbox.

**Comment by justin-schroeder** [comment]
Totally a limitation, I agree. Originally the plan was to only pass the siblings of the group, but then that seemed like a bad idea because you wouldn't have access to the greater form. An index might be possible, although you still don't really know which group it is (assuming a global rule).

There is a workaround though, you can get the index from the group slot and pass it in as an argument to your rule. This makes your rule tightly bound to your logic, but for custom rules that can be acceptable:

```vue
<template>
  <FormulateInput
    type="group"
    name="mygroup"
    #default="{ index }"
  >
    <FormulateInput
      validation-rules="{ customRule }"
      :validation="[
        ['^required'],
        ['customRule', index]
      ]"
    />
  </FormulateInput>
</template>

<script>
  methods: {
    customRule ({ getFormValues }, index) {
      const values = getFormValues()
      const siblings = values.mygroup[index]
      // evaluate the siblings...
    }
  }
</script>
```

**Comment by justin-schroeder** [comment]
This is now supported in `release/2.5.0`. Within a validation rule you can run `getGroupValues()` and get the group values of the current group.
