### ISSUE TITLE
Include ability to add refs to input components with schema forms

### ISSUE THREAD

**Issue by LinnaeK** [wearebraid/vue-formulate#182]
We have several lengthy forms for our users to fill out and we are really excited about creating them with Vue Formulate Schemas. There is one UI case I am stumped on, though. If a validation error occurs when a user submits the form I would like to automatically scroll to the first field with an error and focus on it so they can see where the issue occured. In the past I have done this via `refs` and `focus()` . I tried adding `ref=refName` into the schema but it wasn't applied to the component as a `$refs.` Would it be possible to add ref integration into formulate in order to support programmatically  focusing on certain elements? Or is there a different way to accomplish the end goal that I haven't figure out yet?

**Comment by spAnser** [comment]
That wouldn't solve the ability to focus the input.

I am looking for a way to focus an input not based on any kind of validation errors. Being able to setup refs would be very helpful for this.

It looks like refs work but we reference the component not the input. But it appears we can access the refs of the component so if the inputs got refs defined we could grab a few predefined refs from the component refs if they were available.

**Comment by justin-schroeder** [comment]
Any reason to not use `querySelector` on the component ref $el property?

**Comment by justin-schroeder** [comment]
I think the suggestion here is to just use a normal query selector on the outer ref, something like:

```vue
<template>
  <FormulateInput ref="myinput" />
</template>

<script>
export default {
  methods: {
    focusYourInput () {
      this.$refs.myinput.$el.querySelector('input').focus()
    }
  }
}
</script>
```
