### ISSUE TITLE
Bind context to the default slot of button inputs

### ISSUE THREAD

**Issue by atharva3010** [wearebraid/vue-formulate#185]
**Describe the new feature you'd like**

Vue Formulate is amazing! Thank you for creating it!

When we pass in custom component to the children of button input in the schema declaration of VueFormulate, the context object is not available. Looks like the context isn't bound to the [default slot of the input type "button"](https://github.com/wearebraid/vue-formulate/blob/b57a3274ddcfa96bd4310fcd474d250ab38b2918/src/inputs/FormulateInputButton.vue#L11).

Additionally, if it can just be made into a `slotComponent` it would be even better!

**Comment by justin-schroeder** [comment]
Thanks for filing this! Agree we should make this into a `slotComponent` probably.

**Comment by justin-schroeder** [comment]
@atharva3010 this is also resolved now in the `release/2.5.0` branch. The default slot should now receive the context object, and there is a slotComponent `buttonContent` to allow global replacement of that slot 👍
