### ISSUE TITLE
Sliders won't take floats as inputs

### ISSUE THREAD

**Issue by adamsmietanka** [wearebraid/vue-formulate#186]
**Make the Slider accept floats!**

Unfortunately the only way it operates right now is with integers.

**Comment by andrew-boyd** [comment]
Hey @adamsmietanka I'm able to use float values just fine. If you want the range slider to increment by a decimal value you need to supply it with the `step` attribute, same as native HTML. Take a look at this Codepen and see if it helps.

https://codepen.io/boyd/pen/bGEOvpB

If I'm missing what you're saying feel free to let me know, but I'm going to close this for now.

**Comment by adamsmietanka** [comment]
That's exactly what I needed.
Thanks!
