### ISSUE TITLE
File upload field does not trigger validation message on incorrect mime type when upload behavior is set to immediate

### ISSUE THREAD

**Issue by andrew-boyd** [wearebraid/vue-formulate#19]
**Describe the bug**
The file uploader does display errors when an incorrect mime type file is provided based on the field's validation rules.

**To Reproduce**
1. Go to vueformulate.com
2. scroll to the file upload field
3. upload a .pdf or other incorrect file
4. the file does not upload, but error messages are also not displayed

 - Device: MacBook Pro
 - OS: MacOS mojave
 - Browser: Chrome
 - Version: latest

**Comment by justin-schroeder** [comment]
Technically, this isn’t a bug because the behavior is occurring due to `error-behavior` being set to `blur` and the field not blurring, but think the heuristics of that field type make it acceptable for us to swap the blur behavior for live behavior in this one instance.

**Comment by andrew-boyd** [comment]
That makes sense. The behavior was unexpected as an end user, hence the report. I’d also be in favor of an override in this case.
