### ISSUE TITLE
:validation-rules, delay

### ISSUE THREAD

**Issue by edwingromero** [wearebraid/vue-formulate#191]
I want to do a unique email validate.
I need a delay when writing the email in the input

**Comment by justin-schroeder** [comment]
Just use a debounced function like you would for anything else you would want to debounce

**Comment by sebastianlp** [comment]
> Just use a debounced function like you would for anything else you would want to debounce

Sorry @justin-schroeder but, what I've to debounce if I like to make an API call after the user stop writing an input? Could you share some code about how to debounce a custom rule that makes an API request? I'm not sure if I've to debounce the function that's make the api call or the function of the custom rule

**Comment by justin-schroeder** [comment]
This is just a Vue/JavaScript question so I'll refer you to the handy-dandy ol StackOverflow :)

https://stackoverflow.com/questions/42199956/how-to-implement-debounce-in-vue2

Closing this for now. Good luck 👍

**Comment by sebastianlp** [comment]
Thank you, I know what is a debounce and how to make in a method that handles input. My question was about using it in the validation rules, as in the documentation:

> Internally, Vue Formulate does not debounce validation rules, so if you need to perform an expensive asynchronous validation (like an http request) it is recommended that you debounce your validation rule.

I imagine that if I have a rule like

```
{
  rules: {
    myBeautifulRule: () => {
      return true
    }
  }
}
```

I have to convert it to something like

```
{
  rules: {
    myBeautifulRule: debounce(() => { return true }, 500)
  }
}
```

And it will work, the thing is that the field get validated before this function executes. That's why me previous question

**Comment by mercs600** [comment]
@sebastianlp we had the same issue, your debounce function must returns promise, just use https://github.com/sindresorhus/p-debounce

**Comment by sebastianlp** [comment]
Thank you @mercs600 I've noticed that one week later I post my last comment. That's the explanation I was looking for when I asked @justin-schroeder 👍

**Comment by saadmomin** [comment]
Can someone please give me an example code. I am trying via lodash and its not working. Not sure how to do it via pdebounce. Appreciate it

**Comment by mercs600** [comment]
@saadmomin it should like something like this:
```vue
 <FormulateInput
    ...otherProps
    :validation-rules="{
                  asyncRule: pdebounce(yourvalidatorfunction, 400)
                }"
              />
```

in our case `yourvalidatorfunction` returns promise

**Comment by arunpir** [comment]
I have added pDebounce and still not working. there is no delay in the call 
bsbValid() {
      return pDebounce(productApiService.getFinancialInstitutionFromBsb(this.step3Values.BSB), 2000);
    },
productApiService.getFinancialInstitutionFromBsb is returning a promise
