### ISSUE TITLE
FormulateInput - Groups - won't reflect/sync - keep initialValues

### ISSUE THREAD

**Issue by gahabeen** [wearebraid/vue-formulate#192]
**Describe the bug**
When updating passed object/array, the group items won't sync properly.

**To Reproduce**
1. Create a FormulateInput, type=group
2. Create a second FormulateInput, type=group
3. Use v-model (for ex) for both on the same array
4. Add/edit items in the group, it won't sync when the other is changed

**Reproduction**
Available there:
https://codesandbox.io/s/vue-formulate-groups-dont-sync-efljd?file=/src/App.vue

**Expected behavior**
That updates in the model data is properly updated in the group items.

@justin-schroeder Let me know if you have any hint on where to look for. I've quickly looked at the source but I lost track trying to follow the data lifecycle.

**Comment by justin-schroeder** [comment]
Ive read this issue several times now haha. I haven't had time to dig into it in depth though, so im not totally sure whats going on here yet.

**Comment by gahabeen** [comment]
@justin-schroeder Sorry if I made a new issue if others on the same subject existed.
So far I can handle it without using group/repeated, but I'll need them soon enough (in generated forms).
I'll try to have another look at it when the time comes (a week or so maybe).
I also have to prioritize on the money macking job 😄

**Comment by last-partizan** [comment]
I think there is simpler reproduction:

- Add group.
- Modify value in group programmatically, like `this.values.grouName[0].fieldName = "New value"`
- Value is changed, but input doesn't reflect it's state.

https://codesandbox.io/s/vue-formulate-groups-dont-sync-forked-rgm1j?file=/src/App.vue

**Comment by justin-schroeder** [comment]
@last-partizan that is just a side effect of vue [change detection caveats](https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats). You need to issue a new object. For example: 

https://codesandbox.io/s/vue-formulate-groups-dont-sync-forked-ofinz

**Comment by last-partizan** [comment]
@justin-schroeder i don't see any changes in that code.

btw, in plain vue this is working fine:

https://codesandbox.io/s/vue-formulate-groups-dont-sync-forked-5iedj?file=/src/App.vue

**Comment by justin-schroeder** [comment]
Ahh, sorry, didnt hit save here's my edit again.

https://codesandbox.io/s/vue-formulate-groups-dont-sync-forked-ofinz?file=/src/App.vue

You're correct it works in plain vue because the value is pre-defined, we have to proxy that value in vue formulate so a direct mutation doesn't typically work. still, ill leave this open as it might be something I'd be interested in tackling too.

**Comment by justin-schroeder** [comment]
Well, this was a really tricky one to sort out...but in the `release/2.5.0` branch it is finally synced and working. and @last-partizan — your specific use case should be working without needing to do an object re-assignment in 2.5 as well. Excited to get this one out there!

**Comment by last-partizan** [comment]
@justin-schroeder Great, thank you!
