### ISSUE TITLE
"cannot read property" error of :value binding when inside deeply nested groups, although it displays correctly

### ISSUE THREAD

**Issue by titusdecali** [wearebraid/vue-formulate#193]
**Describe the bug**
When groups are nested more than 1 deep, `:value` binding throws an error, even though the data value is actually binding correctly.

I also think that nested groups should automatically return a v-model for their `name` values, but I'm currently forced to use :value to get the data to appear. This was fine, and not an issue until I needed to add a second group within the first, which is when this strange error occurred.

I am nesting groups in order to match the backend spec of a current project which requires nested object data.

Is my only option to destructure the data in my submit method and then send to the server in the format it wants?

**To Reproduce**
https://codesandbox.io/s/vue-formulate-reproduction-template-vbx3i?file=/src/components/Reproduction.vue

**Expected behavior**
There should not be any errors in console and the v-model values should be returned simply by assigning the correct name.

**Screenshots**
![CleanShot 2020-07-25 at 17 17 44](https://user-images.githubusercontent.com/4532534/88452566-ceeac800-ce9a-11ea-8e46-bcd09c7b7841.jpg)

**Comment by justin-schroeder** [comment]
@titusdecali Gotchya, yeah you're 95% there  to soliving both issues (model binding and the errors) with your example. The issue you're having here is that `groups` are _always_ arrays, even if they are not repeatable. There's an option issue about possibly introducing an object `mode` (#145). I've tweaked your example to use an array syntax and model binding here:

https://codesandbox.io/s/vue-formulate-reproduction-template-00vc8?file=/src/components/Reproduction.vue

I'll close this for now (back from vacation and there's a lot of stuff to read through), but if feel free to continue to comment here.

**Comment by titusdecali** [comment]
Thanks Justin,
Hope your vacation was pleasant. Indeed, `mode="object"` would be a huge time saver.
