### ISSUE TITLE
Custom components are displayed as text input

### ISSUE THREAD

**Issue by Rednas83** [wearebraid/vue-formulate#196]
Custom components are displayed as text input
https://codepen.io/rednas83/pen/PoZgXVp

**Comment by justin-schroeder** [comment]
This is not a supported feature. Please read about [custom inputs](https://vueformulate.com/guide/inputs/custom-inputs/)in the docs. Or if you want an H3, just use `<h3>` right?

**Comment by Rednas83** [comment]
According to the doc it actually is supported
https://vueformulate.com/guide/forms/generating-forms/#schemas
![image](https://user-images.githubusercontent.com/25219229/88543441-3da16000-d018-11ea-8efa-88e892387d38.png)

I want to use the props for form generation so using h3 directly will not be an option for me. I am also planning on writing a couple of custom components like 'CancelOk'

Something like:
login:
  [
    { 'component': 'h3', 'children': 'Login' },
    { 'type': 'text', 'name': 'name', 'label': 'Name', 'validation': 'required' },
    {
      'type': 'password',
      'name': 'password',
      'label': 'Password',
      'validation': 'required|between:8,20,length',
    },
    { 'component': 'CancelOk' },
  ]

**Comment by justin-schroeder** [comment]
That is documentation for schemas not a FormulateInput. 

Since there is no bug here, this conversation would be better asked in a code help kind of setting. You might check out the code-help channel on the Vue discord server.

**Comment by Rednas83** [comment]
I thought that schemes is FormulateInput in a v-for loop. Simular to form generation

Something like:
```
    <FormulateInput
      v-for="item in items"
      :key="item.name"
      :value="value ? value[item.name] : undefined"
      v-bind="item"
      @input="$emit(item.name, $event)"
    />
```

Is this not correct?

**Comment by justin-schroeder** [comment]
If you take a look at that documentation page, you'll see there are 2 ways to generate, a simple loop (non schema based) and a schema based one. The schemas are not a simple for loop and allow for advanced features like custom elements (your h3 example). Those features only work in that context. Good luck 👍

**Comment by Rednas83** [comment]
But in the document there is only the json. How can this be attached to a form?

**Comment by justin-schroeder** [comment]
It's in the docs.
![Screen Shot 2020-07-27 at 9 28 16 AM](https://user-images.githubusercontent.com/1950463/88547411-b3db9d80-cfeb-11ea-820f-7a2c9b776e32.png)

**Comment by Rednas83** [comment]
That's awesome! Thank you very much
