### ISSUE TITLE
Adding variable support for generating forms

### ISSUE THREAD

**Issue by Rednas83** [wearebraid/vue-formulate#197]
Adding variable support for generating forms.

Something like:
  [
    { 'component: 'h3', 'children': 'Delete {{user}}'}
    { 'type': 'CancelOk' },
  ]

Whereby {{user}} is the variable

**Comment by justin-schroeder** [comment]
You can do this, just use regular JavaScript to concatenation a value 👍

**Comment by Rednas83** [comment]
Do you mean selecting the element in the dom and replace with a different attribute value?
It's a solution of course, but not a very nice one.
Could you consider making an update for this?
This would make form generation even more powerfull🦾

**Comment by justin-schroeder** [comment]
I dont mean that. The schema is reactive, so just use a computed property for the schema, and add in your variables at will. we cannot possibly make it any easier than that. Heck you can even do it in your template if you really want.
