### ISSUE TITLE
File type has full of bugs and has misconcept

### ISSUE THREAD

**Issue by beytarovski** [wearebraid/vue-formulate#199]
I don't understand how "File" component works at all. 

* There is no "remove" event or any example about it when you click "x" 
* There is no reactivity if you're using forms and v-model together
* Returning FileList is just useless if your server using Amazon S3 with unique ID

 I had to remove vue-formulate from the project.

**Comment by justin-schroeder** [comment]
Ok.

Did you read the docs?

You can totally use this with an S3 and a unique id by defining an `uploader`. I'm all about constructive criticism, but this issue sounds more like an attempt to shame the maintainers for not conforming to your needs (although it probably does). The docs for the file input are rather extensive: https://vueformulate.com/guide/inputs/types/file

I'd recommend reading them entirely before creating these kinds of reports.

**Comment by screets** [comment]
Hey Wearebraid/vue-Formulate,

We got your help request!
One of our agents will respond to you, asap (usually in *1 business day*).

Note that we don't work on weekends.
However, if we release a major update recently, we are following the
issues.

For support questions, please also email us *s**creets API key* which is
required for support questions.
If you already included in your message, you don't need to do anything else.

Best,
screets
{#HS:1237174077-6687#}

**Comment by justin-schroeder** [comment]
Since there's nothing reported or suggested here im closing this. Feel free to re-open another issue if there is a specific bug or suggestion you're proposing.

**Comment by screets** [comment]
Hey Wearebraid/vue-Formulate,

We got your help request!
One of our agents will respond to you, asap (usually in *1 business day*).

Note that we don't work on weekends.
However, if we release a major update recently, we are following the
issues.

For support questions, please also email us *s**creets API key* which is
required for support questions.
If you already included in your message, you don't need to do anything else.

Best,
screets
{#HS:1238467663-6695#}

**Comment by screets** [comment]
I read even Changelog. But, I want to apologize for the language I used. 
It was too direct unnecessarily.

I think Vue Formulate doesn't suit for our current project at the moment because of some specific requirements I need. I will reopen this if we find any way to implement it.

Thank you for your all effort to create Vue Formulate guys ❤️
