### ISSUE TITLE
Form generation from schema: Dynamic fields break form

### ISSUE THREAD

**Issue by gmw-web** [wearebraid/vue-formulate#200]
**Describe the bug**
I have a form with a schema defined as computed property. 
When form fields are added at the end of the form, the rendering and model are updated correctly. However, adding form fields somewhere in the middle of the schema causes incorrect rendering and does not trigger a model update.

**Reproduction**
Form fields are added at the end of a form, **_working_**:
https://codepen.io/gmw-web/pen/WNrWBBW

Form fields are added somewhere in the middle, **_not working_**:
https://codepen.io/gmw-web/pen/gOPyyym

**Expected behavior**
When a form field is dynamically added to the schema, anywhere, it should be rendered correctly and (optionally) have it's initial value set to the model.

**Device information:**
 - Device: Recent Dell laptop
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version 84.0.latest

**Comment by justin-schroeder** [comment]
Hmm, this is a really interesting bug actually and might be related to #117, but it's a simpler reproduction. Thanks for isolating it, i'll definitely take a look.

**Comment by gmw-web** [comment]
No problem. My first guess was that Vue is reusing elements, due to missing `key` fields on the `FormulateInput` components.

The issue seems similar to what is described here in the Vue docs:
https://vuejs.org/v2/guide/conditional.html#Controlling-Reusable-Elements-with-key

**Comment by justin-schroeder** [comment]
Thanks for the good report @gmw-web 👍 This issue is fixed in `release/2.4.4` due out very soon :)
