### ISSUE TITLE
Proposal: functions to define validation rules

### ISSUE THREAD

**Issue by justin-schroeder** [wearebraid/vue-formulate#201]
**Describe the new feature you'd like**

Occasionally it makes sense to have variable validation rules. Currently we support doing this by with a simple `v-bind` on the `validation` prop:

### Currently:
```vue
<FormulateInput
  :validation="someCondition ? 'required' : 'optional'"
/>
```

However, typically `someCondition` is derived from other values in your form, in this case you v-model the form and create an appropriate computed prop to define someCondition. This works just fine, but there are some occasions where you may not have easy access to the instance (like when using schemas from an external source). Either way it requires a bunch of boilerplate for a simple conditional rule.

### Proposal:

Allow the `validation` prop to accept a function that when called defines the validation rules to run. This function would be passed a (simple) context object similar to the one passed to validation rules and messages (note, the full context object here would be too large and incur a performance penalty)

```vue
<FormulateInput
  name="zip"
  :validation="({ formValues }) => formValues.country === 'US' ? 'required' : 'optional'"
/>
```

**Comment by justin-schroeder** [comment]
2.5 now includes a context object for `FormulateForm` that includes a `values` property reflecting the values of the current form state. This allows us to basically have the same functionality as described here without needing to model bind explicity and is a much more performant general-solution than this proposal. This same example could be written:

```vue
<FormulateForm
  #default="{ values }"
>
  <FormulateInput
    name="inputA"
  />
  <FormulateInput
    :validation="values.inputA === 'yes' ? 'required' : 'optional'"
  />
</FormulateForm>
```

**Comment by eyleron** [comment]
How is this expressed in the schema?
