### ISSUE TITLE
API to expose all form errors (validation and external)

### ISSUE THREAD

**Issue by henryaj** [wearebraid/vue-formulate#204]
Hi! New to Vue and Vue Formulate, so apologies if this is already something that's easy to do.

I'm using both the built-in form validations _and_ external validations on my form. At the end of the form, I want to be able to show a list of all the errors on the form, both external validations and the ones that come from Formulate.

Is this something that's possible at the moment?

Thanks!

**Comment by justin-schroeder** [comment]
Vue Formulate’s validation errors are always shown contextually (generally a better UX), although you could catch them and manually collate/display them using the `@validation` event on the form. That said, you can show your own errors wherever you want using `<FormulateErrors>`. There is a whole section on error handling and how you can display your own form and field level errors here: https://vueformulate.com/guide/forms/error-handling

There's an open issue for automatically showing some kind of message using `FormulateErrors` on really long forms #78. Good luck 👍
