### ISSUE TITLE
Proposal: Change submit to be a prop instead of an event.

### ISSUE THREAD

**Issue by thekonz** [wearebraid/vue-formulate#205]
I propose to change the submit event to be a prop.

So this...
```vue
<FormulateForm @submit="submitHandler">
```

...would become this:
```vue
<FormulateForm :submit="submitHandler">
```

But why?

In order to prevent double submissions when sending data to a server, developers will have to implement this pattern in their `submitHandler` in one way or another:

```js
async submitHandler() {
  if (this.isLoading) return
  this.isLoading = true
  await this.sendData()
  this.isLoading = false
}
```

And then based on `isLoading` optionally you disable inputs to stop them being modified .

If you don't have a submit event but a submit prop, you can await the call to `this.submit()` in the `FormulateForm` and abstract away the `isLoading` and input disable logic, which prevents double submissions.

What do you think?

**Comment by justin-schroeder** [comment]
Cool idea @thekonz! I like it. I wonder if we could just do this with the submit handler. Either way we would need to leave the submit event, but this functionality could be additive for sure

**Comment by thekonz** [comment]
No you cannot await an event listener sadly. Events are fire-and-forget.

**Comment by thekonz** [comment]
Then I'll prepare a PR and check back with you.

**Comment by justin-schroeder** [comment]
Well...technically you can await an event listener, you just don't `$emit` the event but call it manually from the `$listeners`. It's not the normal way of doing things but sometimes as library authors we use some non standard internals to create a great DX.

However it's far enough out of line with standard expectations I'm not sure if developers would understand what is going on or not.

Also, it's unclear to me what exactly happens in the loading state? The fields get locked? Form submission is locked? Would everyone want that behavior? Is it opt in or are can you choose to not have anything happen but make your own modifications via slots etc.

**Comment by thekonz** [comment]
Ah true, technically possible and that would also be a good idea also for backwards compatibility. So maybe in this case, I'll implement it using `$listeners`.
In the loading state, the `submit` event does not get triggered again and I would also expose `isLoading` as a slot property so people can animate their loading states as they wish.

I personally don not see a case where I would not want that feature, but theoretically if I do not return a `Promise`, the feature does not get used.

```js
// submit waits for it to be done
async submit() {
  await this.sendData()
}

// does not wait
submit() {
  this.sendData()
    .catch(error => alert('yo, there is an error')
}
```

**Comment by thekonz** [comment]
Have a look at #211 and tell me what you think.

**Comment by OperKH** [comment]
Alternative not to use `isLoading` - it's to use [v-promise-btn](https://stukh.github.io/vue-promise-btn/) directive

Perfectly works in real project, code like that:
```ts
<FormulateForm
    class="create-member-form"
    name="createMemberForm"
    v-model="formValues"
    @submit="createMemberFormSubmitHandler"
    v-promise-btn="{ action: 'submit' }"
    v-bind="{ ...serverErrors }"
>
    <FormulateInput name="firstName" label="First name" validation="required" validation-name="first name" />
    <FormulateInput name="lastName" label="Last name" validation="required" validation-name="last name" />
    <FormulateInput type="submit" label="Create" />
    <FormulateErrors />
</FormulateForm>
```
```ts
async createMemberFormSubmitHandler(formData: CreateUserModel) {
  this.serverErrors = new ServerErrorAdapter();
  try {
    await createUser(formData);
  } catch (e) {
    this.serverErrors = new ServerErrorAdapter(e);
  }
},
```

![workflow](http://g.recordit.co/vHBQA3eG4J.gif)

**Comment by thekonz** [comment]
Oh I did not know v-promise-btn.

One other thing. If you want to use the new `isLoading`, here is an example to disable every input and button in a form while loading:

```vue
<FormulateForm>
    <template #default="{ isLoading }">
        <fieldset :disabled="isLoading">
            <FormulateInput name="firstName" label="First name" />
            <FormulateInput name="lastName" label="Last name" />
            <FormulateInput type="submit" label="Create" />
            <FormulateErrors />
        </fieldset>
    </template>
</FormulateForm>
```

**Comment by frknasir** [comment]
how do you use it with schema?
