### ISSUE TITLE
datalist

### ISSUE THREAD

**Issue by wduandy** [wearebraid/vue-formulate#206]
Is there a way to insert a datalist on a text input field?

An example below:

https://www.w3schools.com/tags/tag_datalist.asp

**Comment by justin-schroeder** [comment]
There's nothing preventing you from doing this, but it's also not something that's any different than normal html.

Here's a simple datalist example:
https://codepen.io/justin-schroeder/pen/vYLqNOW

Good luck @wduandy 👍

**Comment by wduandy** [comment]
Hey Justin! Thanks for answering me! It is possible to do this with https://vueformulate.com/guide/forms/#generating-forms method?

**Comment by justin-schroeder** [comment]
Yeah thats not a problem at all, just define your datalist as one of the components in your schema and make sure you define the `list` property and matching `id` in the datalist.
