### ISSUE TITLE
Add method to change locale after it has been memoized.

### ISSUE THREAD

**Issue by jan-thoma** [wearebraid/vue-formulate#209]
**Describe the bug**
When used together with the vue-i18n plugin. The locale is only set at the initialization of the app. Subsequent changes of the locale with vue-i18n is ignored. Neither setting the locale manually with `$formulate.options.locale = 'en'` has no effect.

**Expected behavior**
The locale should change

**Comment by justin-schroeder** [comment]
That's true actually. We memoize the locale so we don't have to constantly look it up. The active locale is memoized in `$formulate.selectedLocale`. Open to suggestions on how to address without needing to check it on every key stroke. Are there `vue-i18n` events we could tap into (im no expert on that plugin)?

Would it be acceptable to also create a new function on `$formulate` maybe `$formulate.setLocale('zh')` for those times when you want to use a language selector or some such?

**Comment by jan-thoma** [comment]
`vue-i18n` doesn't emit any events as far as i know. A common pattern is to change the locale in a `vue-router` hook for example:

```
router.afterEach((to, from) =>
{
    router.app.$i18n.locale = to.meta.locale
})
```

The proposed method `$formulate.setLocale('zh')` would absolutely fit that scenario.

**Comment by justin-schroeder** [comment]
Sounds good. In that case I'll mark this as a feature request to add that method. In the meantime:

## Today

```js
$formulate.options.locale = 'zh'
$formulate.selectedLocale = 'zh'
```

## Soon

```js
$formulate.setLocale('zh')
```

**Comment by justin-schroeder** [comment]
this is added in release/2.4.4

**Comment by atharva3010** [comment]
Yes. Yes. YES.
Thank you!
