### ISSUE TITLE
Proposal: Discord for VueFormulate?

### ISSUE THREAD

**Issue by justin-schroeder** [wearebraid/vue-formulate#210]
**Describe the new feature you'd like**

After some conversations with people on the Vue Land discord server, @atharva3010 suggested we create a VueFormulate specific Discord server. I'm curious if others would find this useful or not. My main hesitation is that while Vue Formulate's usage is growing quickly it is pretty new and still a relatively "small" package by usage, and I hate to add to the clutter of discord servers Vue Developers might already be involved in, not to mention adding just one more place monitor conversations.

On the otherhand, having a dedicated place for people to get help sounds really nice, especially if people in the community step up to help so it isn't just on the maintainers. Does anyone have thoughts on this?

**Comment by atharva3010** [comment]
A lot of my conversations with @justin-schroeder are either on VueLand’s #code-help or in DM, on Discord. These conversations do cover a lot of interesting use cases which others might benefit from, having a dedicated space to talk can enable us to learn from other people’s experiences and also grow the community!

We can help each other when stuck and talk about new features that we can build. Just like Justin said, this can help take some load off the maintainers’ shoulders.

**Comment by gustojs** [comment]
I'd say go for it.  In such cases, the sooner the better cause you won't have to move away the community from one place to another later. Now before Vue 3 release and library update is a good time for that.

The "discord servers clutter" is not a thing imho. From my discussions with both users and maintainers, it's easier for them this way.

**Comment by christianechevarria** [comment]
Agree with @gustojs, setting up a place where everyone in the community knows to go is valuable in and of itself. Also, I'm new to the community for instance and wasn't aware that there was a place to chat -- not sure if I missed that in the docs / README

**Comment by Rednas83** [comment]
A dedicated discord chatroom would be great. In my experience this is the fastest way for getting help.

**Comment by chadwtaylor** [comment]
+1 

Or consider using Slack?

**Comment by hacknug** [comment]
Discord is the way ✨

**Comment by christianechevarria** [comment]
Hey! Just circling back on this, was hoping to make use of this today but seems like it's not ready yet :(

Having a Discord for the community would be awesome

**Comment by justin-schroeder** [comment]
Yep. I'll make it happen. Stay tuned!

**Comment by justin-schroeder** [comment]
This will be announce in the next few days with the release of version 2.5 🚀

**Comment by andrew-boyd** [comment]
Hey all, `2.5` is being launched as we speak and the link to the new Discord community is in the updated docs. 

https://vueformulate.com/guide/community/#vue-formulate-discord-generalized-help-discussion
