### ISSUE TITLE
Unknown custom component when used in schema

### ISSUE THREAD

**Issue by Rednas83** [wearebraid/vue-formulate#212]
For some reason I can't use custom components inside a schema.
{ 'component': 'h3', 'children': 'Login user' } ==> Working as expected
{ 'component': 'vinput', 'type': 'CancelOk' } ==>
![image](https://user-images.githubusercontent.com/25219229/88896270-e97dc200-d249-11ea-81ba-a741922c4574.png)

vinput is globally registered and can be used everywhere else!

Tried:
*Lazy loading 
*Global registration
*Local registration

Not sure what to try anymore. Could it be related to vue-formulate somehow?

**Comment by justin-schroeder** [comment]
Can you provide a code sandbox reproduction? It's not possible to debug from the provided information.


https://codesandbox.io/embed/vue-formulate-reproduction-template-p5c1i?file=/src/components/Reproduction.vue&codemirror=1

**Comment by Rednas83** [comment]
Hereby
https://codesandbox.io/s/vue-formulate-reproduction-template-6bzi1?file=/src/App.vue
        { component: "h3", children: "h3" }, //Returns h3
        { component: "Reproduction" } // Returns unknown custom component

**Comment by justin-schroeder** [comment]
Thanks for the reproduction. You're very close, just need to register your component globally and is well:

https://codesandbox.io/s/vue-formulate-custom-component-8krhh?file=/src/main.js

Note the `Vue.component("Reproduction", Reproduction);`

**Comment by justin-schroeder** [comment]
Currently no. although global registration is not heavier. in fact some performance tests show it to be slightly higher performance. You can always code split the global registration if you want to lazy load your component too. Someday we might add support for local registration, but not super soon.
