### ISSUE TITLE
Multi-Select

### ISSUE THREAD

**Issue by c-myers1** [wearebraid/vue-formulate#215]
**Describe the new feature you'd like**

It would be great to have a `multiple: "true"` configuration option to the select input type so it can be used as a multi-select field.

**Comment by justin-schroeder** [comment]
This works fine as it's just part of standard HTML: https://codepen.io/justin-schroeder/pen/vYLoqXx

Good luck 👍

**Comment by c-myers1** [comment]
Thanks. I modified as per section below:

      `<FormulateInput
        name="example"
        type="select"
        :options="{first: 'First', second: 'Second'}"
        label="Reproduction template!"
        help="Click 'Use This Template' and reproduce your issue!"
        multiple
        size=1
      />`
     
I get the attached result
![image](https://user-images.githubusercontent.com/42839510/89127333-b4d96700-d4e4-11ea-8036-681a82b3c99a.png)

Is there no way to (1) get rid of the down-pointing icon as well as (2) make input section smaller (so it shows only 1 line on blur?) 

For (2), I fiddled around with input-class padding but it has no effect.

I was excited seeing this tool but if such things are not made easy, then it would only be appropriate for very simple forms.

**Comment by justin-schroeder** [comment]
To be clear, this is not a UI library like vuetify, and it assumes you know how to write styles. In which case it's nice and easy to remove the dropdown arrow :) If styling is challenging for you, I suggest you use a UI library.

If you feel there should be some default styling for multiple inputs in the snow theme, great! Feel free to open a pull request with those styles. Good luck 👍

**Comment by c-myers1** [comment]
If you position the product as "The easiest way to build forms with Vue" without a qualifier to be experienced at styling, then it's expected there should be a baseline of ready-to-use common form elements working out of the box. My 50 cents.

**Comment by andrew-boyd** [comment]
@c-myers1 The snow theme that ships with Vue Formulate covers all the basic input types that Vue Formulate supports. I can see where you're coming from that multi-select inputs are native HTML and should be covered by the base theme.

Like @justin-schroeder said we're not aiming to be a UI framework, but I think adding these styles to the snow theme is something we should do. Now, if users depart from the snow theme (or any future theme that ships with Vue Formulate) they would understandably be on their own.

**Comment by jn151** [comment]
Any update on this? This library has been perfect for me except this one thing I need.

**Comment by andrew-boyd** [comment]
Thanks for the bump. No progress as of yet. Should have time this week to handle it though.

**Comment by andrew-boyd** [comment]
@jn151 @c-myers1 changes in #233 and #234 add support for the above requests to the snow theme that ships with Vue Formulate. They'll be released with 2.4.4.

**Multiple attribute:**
![multiple](https://user-images.githubusercontent.com/2946356/91892592-ee76cc80-ec60-11ea-8759-0a111367ba33.jpg)

**Multiple attribute with `size=1` attribute set:**
![size-1](https://user-images.githubusercontent.com/2946356/91892593-ee76cc80-ec60-11ea-8d1d-4e7090e8ffcd.jpg)

**Comment by c-myers1** [comment]
👍 super

**Comment by justin-schroeder** [comment]
Fixed in release/2.4.4 (as of this comment not quite published yet)
