### ISSUE TITLE
Deselection Option In Select 

### ISSUE THREAD

**Issue by kalimulhaq** [wearebraid/vue-formulate#218]
**Select: Dropdown should allow deselection**

If the dropdown does not have required validation then it should allow the user to deselect the value after selecting a value from the dropdown.

**Comment by justin-schroeder** [comment]
That would be nice, but this isn't a feature of native select lists. The select list in Vue Formulate is intentionally the standard select list. However, you could pretty easily create a [custom input type](https://vueformulate.com/guide/inputs/custom-inputs/) to add this functionality for your project 👍
