### ISSUE TITLE
New tag type for entering simple array's

### ISSUE THREAD

**Issue by Rednas83** [wearebraid/vue-formulate#219]
I am pretty happy with all the current input types. One that really could make a nice addition i think is tags.

Something like:
![image](https://user-images.githubusercontent.com/25219229/89774811-d222bc80-db06-11ea-8b94-cead1ac1b7dd.png)
https://codepen.io/rednas83/pen/mdPJGaq?editable=true&editors=101%3Dhttps%3A%2F%2Fbuefy.org%2Fdocumentation%2Ftaginput

**Comment by justin-schroeder** [comment]
Yep, would be super cool! I'd recommend making a custom input type as a plugin to support this. Core will not be extended to include synthetic inputs, but i'd love to see plugins developed like this.

**Comment by Rednas83** [comment]
I wil try adding some extensions sometime.
Do you perhaps have an example for this?
That would greatly help.

**Comment by Rednas83** [comment]
I was able to write a basic taginput component based on tailwind and vue-formulate.
![image](https://user-images.githubusercontent.com/25219229/89907723-4cc60780-dbed-11ea-9a06-f6eeac99e487.png)
But how can I turn this into a plugin?
I don't think https://vueformulate.com/guide/plugins/#creating-a-new-plugin is providing enough information for how to do this. I think an example/guidelines would help a lot for this.

**Comment by justin-schroeder** [comment]
Great! You found the correct docs. Checkout the example plugin: https://vueformulate.com/guide/plugins/#example-autocomplete-plugin

That's a pretty comprehensive example of how to do it.

**Comment by Rednas83** [comment]
That was easy enough.

Is there a official classification for 'array' or 'object'? ...I will need this to be able to push/delete items into the model.
```
Vue.use(VueFormulate, {
  library: {
    autocomplete: { classification: 'text', component: 'autocomplete' },
    tags: { classification: 'text', component: 'tags' },
  },
})
```
Should there be global classes for everything or can plugins have some specific styles like the ones below?
```
<template>
  <div
    :class="`formulate-input-element formulate-input-element--${context.type} flex px-2 items-center`"
    :data-type="context.type"
  >
    <div v-for="item in context.model" :key="item" class="flex">
      <div>{{ item }}</div>
      <div class="mx-2 font-black cursor-pointer" @click="remove(item)">x</div>
    </div>
    <input
      v-model="iValue"
      type="text"
      v-bind="context.attributes"
      autocomplete="no"
      class="ml-2"
      @keydown.enter="add(iValue)"
      @keydown.tab="add(iValue)"
      @blur="context.blurHandler"
    />
  </div>
</template>
<script>
```
You mentioned **context.rootEmit** in the guide, but it wasn't in the example code. Perhaps add it to autocomplete.vue?

**Comment by Rednas83** [comment]
First version:
**The call**
`<FormulateInput v-model="data" type="tags" name="tags" label="Enter tags" />`
Whereby data is something like { First: 'First', Second: 'Second' },

**The component**
```
<template>
  <div
    :class="`formulate-input-element formulate-input-element--${context.type} flex px-2 items-center`"
    :data-type="context.type"
  >
    <div v-for="item in context.model" :key="item" class="flex">
      <div>{{ item }}</div>
      <div class="mx-2 font-black cursor-pointer" @click="remove(item)">x</div>
    </div>
    <input
      v-model="iValue"
      type="text"
      v-bind="context.attributes"
      autocomplete="no"
      class="ml-2"
      @keydown.enter="add(iValue)"
      @keydown.tab="add(iValue)"
      @blur="context.blurHandler"
    />
  </div>
</template>
<script>
export default {
  props: {
    context: {
      type: Object,
      required: true,
    },
  },
  data() {
    return {
      items: this.context.model,
      iValue: undefined,
    }
  },
  methods: {
    add(iValue) {
      if (iValue) {
        this.items[iValue] = iValue
        this.iValue = undefined
        this.context.rootEmit('input', this.items)
      }
    },
    remove(iValue) {
      const tValue = { ...this.context.model }
      delete tValue[iValue]
      this.items = tValue
      this.context.rootEmit('input', tValue)
    },
  },
}
</script>
```
**The result**
![image](https://user-images.githubusercontent.com/25219229/90334870-eec06800-dfd0-11ea-98d8-e62cc7290522.png)
