### ISSUE TITLE
Use language tags on locales

### ISSUE THREAD

**Issue by hmaesta** [wearebraid/vue-formulate#22]
As mentioned on https://github.com/wearebraid/vue-formulate/pull/21, we should move to [language tags](https://en.wikipedia.org/wiki/Language_localisation#Language_tags_and_codes) while it's early.

If this project gets big, using two letter language identifications (i.e. `en` `fr` `pt`) would generate regional issues. We should move to `en-US` `en-UK` `pt-BR` `pt-PT`.

In English some words can be a little different...
| en-US   	| en-UK   	|
|---------	|---------	|
| meter   	| metre   	|
| fiber   	| fibre   	|
| center  	| centre  	|

... but in Portuguese the sentence can change a lot.
| pt-BR                      	| pt-PT                      	|
|----------------------------	|----------------------------	|
| Me **dá** um presente?         	| **Dá**-me um presente?         	|
| Vou **na** escola hoje.        	| Vou **à** escola hoje.         	|
| Estou prepara**ndo** o almoço. 	| Estou **a** preparar o almoço. 	|

**Comment by justin-schroeder** [comment]
@hmaesta This is now a supported feature in the `2.2.0` branch. Tags will fall back through their sub-groups until they hit the base language tag, if they miss there too they fall back to `en`. However the locales themselves have been moved over to [`vue-formulate-i18n`](https://github.com/wearebraid/vue-formulate-i18n).

I’d love to see better localization in general — and for translators to feel empowered to re-write the messages to sound very natural in their own language and culture, hopefully that sub-package will give us the opportunity to do that better and faster than the main package.

I'm pretty sure this solves the language tag issue, but if you think the implementation should be improved feel free to open another issue. Thanks again!
