### ISSUE TITLE
Default prop in schema not working for all types

### ISSUE THREAD

**Issue by Rednas83** [wearebraid/vue-formulate#220]
### Actual behaviour
From the 3 types I tried only **select** is getting the default value from the schema
![image](https://user-images.githubusercontent.com/25219229/89781567-e5885480-db13-11ea-8136-67119d51dde7.png)

### Expected behaviour
All types loaded with the default value from the schema

**Comment by justin-schroeder** [comment]
Gonna need more details than this. Would help to include at least the schema.

**Comment by Rednas83** [comment]
The schema is in the picture. With a text, a select and a checkbox

**Comment by justin-schroeder** [comment]
oh you literally have a prop named `default` and it's value is `error`? default isn't even a valid prop in vue formulate. I honestly need more context here. 🤷‍♂️

**Comment by Rednas83** [comment]
Thanks for pointing this out.

Is there no way to set the default/initial value within the schema then?

For me this would make much more sense then doing it on mount afterwards. 

Sometimes I use a more simplified schema like which also holds the default value:
```
labeling:
  { label: '', help: '', error: 'error', error-behavior: 'blur || submit || live', disabled: true }
```
And then convert it by a simple scheme function with only the name (as key) and the default value / options (as value). 
```
    scheme(iActuals) {
      const ctable = []
      for (const key in iActuals) {
        switch (typeof iActuals[key]) {
          case 'boolean':
            ctable.push({
              type: 'checkbox',
              name: key,
              label: key,
              default: iActuals[key],
            })
            break

          case 'string':
            const iOptions = this.optionsx(iActuals[key])
            // FERE Object.keys(iOptions).length > 1
            Object.keys(iOptions).length > 1 && key != 'options'
              ? ctable.push({
                  type: key == 'options' ? 'tags' : 'select',
                  name: key,
                  label: key,
                  // default: Object.keys(iOptions)[0],
                  options: iOptions,
                })
              : ctable.push({
                  type: 'text',
                  name: key,
                  label: key,
                  // FERE default: iActuals[key],
                  default: key != 'options' ? iActuals[key] : JSON.stringify(iActuals[key]),
                  placeholder: 'Enter text',
                })
            break
        }
      }
      return ctable
    },
```

For me it would be very convenient to be able to setup the default value there.

Currently busy with finalizing an interactive version of the cheat sheet for vue-formulate. Hereby a little sneak preview
![image](https://user-images.githubusercontent.com/25219229/89802355-b84a9f00-db31-11ea-94ab-5397d3b36199.png)

**Comment by justin-schroeder** [comment]
You can. The schema props are identical to normal vue-formulate props. So what you're looking for is the `value` prop 👍

**Comment by Rednas83** [comment]
Thanks. That is working for me. For some reason I thought it was not working before.
