### ISSUE TITLE
Breaks using object/array syntax for `class` in schema-generated forms

### ISSUE THREAD

**Issue by hacknug** [wearebraid/vue-formulate#222]
Just another small _bug_ I've encountered while working on these forms I'm building.

**Describe the bug**
It would be great if we could use the array/object syntax for `class`es on our schema. Right now it treats both of them as if they were strings instead of making everything work the Vue way.

**To Reproduce**
1. Open the CodePen provided in this issue
2. Right-click the buttons and check the className for the wrapping divs

**Reproduction**
https://codepen.io/hack_nug/pen/OJNMQBB

**Expected behavior**
I'd expect Formulate to _do nothing_ (as in, make everything work the way it does in Vue). This might mean we need to manually handle this on `vue-formulate` or fix the _bug_ (I feel like there's an explanation why this doesn't work as I expected already or it would require us to consider other scenarios).

**Device information:**
 - Version latest

**Comment by justin-schroeder** [comment]
Ahh great find, thank you. Currently classes are not extracted as their own property in the `leaf` of the render function:

https://github.com/wearebraid/vue-formulate/blob/master/src/FormulateSchema.js#L8

And they are a top level item the vue render function options object, so currently they must be treated as a simple attribute and not a "magic" class attribute. Should be an easy fix.

**Comment by justin-schroeder** [comment]
Ok, this is fixed in `release/2.4.4`. Thanks again for the good report 👍
