### ISSUE TITLE
confirm-rule always fails in groups

### ISSUE THREAD

**Issue by Christoph-Wagner** [wearebraid/vue-formulate#226]
**Describe the bug**
When using the `confirm` validation-rule with grouped fields, it always fails. I tried manually naming the field with `confirm:otherfield` but that makes no difference.

**To Reproduce**
1. Group 2 Textfields, the 2nd with the `confirm` validation.
2. Give both the same value
3. Try to submit: "fieldname_confirm does not match"

**Reproduction**
https://codepen.io/cwagner/pen/vYGKKxd

**Expected behavior**
Not getting an error when the values match.

**Device information:**
Tested with current versions of FF, Chrome, Edge

**Comment by Christoph-Wagner** [comment]
Looking at the code, after having played with groups, it is clear why it’s not working:  
`return formValues[confirmationFieldName] === value`

essentially it would need to be something like this:
`formValues[groupNameOfCurrentField][groupIndexOfCurrentField[confirmationFieldName]`

Luckily (for me) the field where I needed the rule didn’t actually need to be in a group ;)

**Comment by justin-schroeder** [comment]
thats correct. we've discussed this for custom validation rules in #181. I'll leave this open as a reminder to fix the confirm validation rule once that's live. I assume people are ok with the fact that if you use `confirm` inside a group it can/will only validate against the current group. So you couldn't "confirm" a field outside the group (at least not without a custom validation function). That seems acceptable/expected to me, but are there outlier conditions im not considering?

**Comment by Christoph-Wagner** [comment]
That sounds good. And I can’t think of a reason to do cross-group validation either (outside of really abusing groups for styling). I’ll add a PR to the docs to mention this.

**Comment by justin-schroeder** [comment]
This is now fixed in the `release/2.5.0` branch! Validation rules are now given a `getGroupValues` function which returns only the values of their local group. For some rules (like confirm) this makes sense.
