### ISSUE TITLE
composition api supported?

### ISSUE THREAD

**Issue by fbraem** [wearebraid/vue-formulate#227]
I'm trying to use the composition api to make the step to upgrade to Vue 3 easier in the future.

When I create a form object in the setup function with reactive and set the values of the current record in the onMounted callback, the new values aren't shown in the form. It seems that reactivity is lost somewhere...

````
setup() {
  const teams = useTeams();
  const form = reactive({
    name: 'Team 1'
  });
  onMounted(async() => {
    await teams.read(props.id);
    form.name = teams.current.value.name;
  });
  return {
    teams,
    form
  };
````
Is the composition api supported in vue-formulate?

When I write the code for the form as Vue 2 then the code works: i.e. creating the form in data() and loading in mounted().

**Comment by justin-schroeder** [comment]
@fbraem honestly I haven't checked it out with the Vue 2 composition API, but we're looking to support Vue 3 in the not too distant future. I think I've seen @gahabeen use the Vue 2 Composition API in some examples though? Gabin, any thoughts on this one?

**Comment by gahabeen** [comment]
I'm indeed successfully using Vue Composition API with Vue-Formulate within some quite deep intricate scenarios so it should be all good!

A small repro on codesandbox would be nice @fbraem to see how you bind **vue-formulate** with your data.

**Comment by fbraem** [comment]
I think I'm struggling with the ref/reactive part of the composition api.
In this sandbox it works: https://codesandbox.io/s/floral-star-k2ddu?file=/src/main.js
It's still a mystery to me why it doesn't work in my project... I'm closing this issue for now.

**Comment by malydok** [comment]
Here's a simple example I can't get to work: https://codesandbox.io/s/cranky-bouman-3xbqs?file=/src/components/HelloWorld.vue

When using a `reactive` object as a model for the whole form the values update just fine but cease to fire any watchers (a simple `computed` in the above case). Putting `v-model` on the whole form seems to be the root cause here, because doing `v-model="form.name"` on the input itself works just fine.

Appreciate any help, and hope you forgive me if I ping you @gahabeen. Cheers!

**Comment by gahabeen** [comment]
@malydok @fbraem I never use `reactive` and always use `ref`. That may be why it fails. Had so many troubles with it in past experiments.

**Comment by fbraem** [comment]
Indeed with ref it works. Sample: https://github.com/fbraem/kwai-ui/blob/develop/src/apps/teams/TeamForm.vue
