### ISSUE TITLE
Initial value not working for checkbox when set by value proportie

### ISSUE THREAD

**Issue by Rednas83** [wearebraid/vue-formulate#229]
**Describe the bug**
Checkbox is not set to true when the value proportie is set to true

**Reproduction**
https://codepen.io/rednas83/pen/poyRVeM

**Comment by justin-schroeder** [comment]
Correct, we follow standard HTML in this regard. Checkout the note at the top of this documentation page for clarity:

https://vueformulate.com/guide/inputs/types/box/
