### ISSUE TITLE
Add ability to customize classes for FormulateForm

### ISSUE THREAD

**Issue by christianechevarria** [wearebraid/vue-formulate#235]
**Describe the new feature you'd like**

Customizing styles for FormulateInput components is easy and follows a nice structure, is there something similar at the form level?

It would be nice to take advantage of the global configuration ability of VueFormulate like so:

```
Vue.use(VueFormulate, {
  classes: {
    form: 'bg-white py-10 ...more-custom-styles',
  },
})
```

**Comment by christianechevarria** [comment]
There is a really interesting use-case to making every piece of VueFormulate available to globally configure with custom styles. I've been playing with using Tailwind to style forms automatically and now by just dropping VueFormulate inputs I have beautiful consistently styled forms:

![super-easy-forms](https://user-images.githubusercontent.com/23618650/92140775-66123c00-edc6-11ea-81a1-f5f724fc7937.png)

There's a clear architectural pattern that can emerge from taking this approach, here is some of the code that is styling those forms automatically:

```
import Vue from 'vue'
import VueFormulate from '@braid/vue-formulate'

const inputTextStyle = [
  'block',
  'w-full',
  ...
  'transition',
  'duration-150',
  'ease-in-out',
  'sm:text-sm',
  'sm:leading-5',
  'text-black',
]

const inputGroupStyle = []

const inputSelectStyle = []

const inputBoxStyle = ['mr-2']

const inputButtonStyle = [
  'w-full',
  'flex',
  'justify-center',
  'py-2',
  'px-4',
  ...
  'transition',
  'duration-150',
  'ease-in-out',
]

const inputStyleFn = function (ctx, classes) {
  if (ctx.classification === 'text') return classes.concat(inputTextStyle)
  if (ctx.classification === 'box') return classes.concat(inputBoxStyle)
  if (ctx.classification === 'group') return classes.concat(inputGroupStyle)
  if (ctx.classification === 'button') return classes.concat(inputButtonStyle)
  if (ctx.classification === 'select') return classes.concat(inputSelectStyle)
}

const wrapperTextStyle = ['mt-5', 'text-sm']

const wrapperBoxStyle = [
  'flex',
  'items-center',
  'justify-center',
  'mt-5',
  'text-sm',
]

const wrapperStyleFn = function (ctx, classes) {
  if (ctx.classification === 'text') return classes.concat(wrapperTextStyle)
  if (ctx.classification === 'box') return classes.concat(wrapperBoxStyle)
}

Vue.use(VueFormulate, {
  classes: {
    wrapper: wrapperStyleFn, // Make into fn that detects first element
    label: 'block text-sm font-medium leading-5 text-gray-700',
    element: 'mt-1 rounded-md shadow-sm',
    input: inputStyleFn,
    help: 'mt-2 text-xs text-gray-500',
    error: 'mt-2 text-xs text-red-600',
  },
})
```

The idea here is you can compose different styles from functions that return arrays for all of the permutations of classes / error state / etc. etc. 

I think this could evolve into a visual form-builder playground where you define your styles and drop form components visually then the tool spits out the appropriate config and markup code for you.

Super abstracted super productive.

**Comment by justin-schroeder** [comment]
Agreed @christianechevarria. In fact we've even thrown around the idea of having a theme builder on the site itself 🤫. Look for form and form error class support in an upcoming release

**Comment by christianechevarria** [comment]
> Agreed @christianechevarria. In fact we've even thrown around the idea of having a theme builder on the site itself 🤫

@justin-schroeder, excellent! Please let me know if there's any way to get involved, I'd love to see this become a reality and am curious about where this could lead

**Comment by justin-schroeder** [comment]
I think one of the coolest ways to get involved would be to produce theme plugins. Because you can override those class functions with a plugin you could easily create themes downloadable via npm. The install would be crazy easy:

```sh
npm install @your-org/vue-formulate-dark
```

```js
import DarkTheme from '@your-org/vue-formulate-dark'
import VueFormulate from '@braid/vue-formulate'

Vue.use(VueFormulate, {
  plugins: [DarkTheme]
})

```
