### ISSUE TITLE
Custom input types and attribute-hyphenation

### ISSUE THREAD

**Issue by bingo-ingo** [wearebraid/vue-formulate#237]
Is attribute hyphenation not support in the context.attributes?

https://eslint.vuejs.org/rules/attribute-hyphenation.html

**Comment by justin-schroeder** [comment]
Should be. Can you provide a reproduction of it not working?

**Comment by bingo-ingo** [comment]
I am using:
```
            <FormulateInput
              v-model="data"
              modal-options-name="toms"
              type="multiselect"
              label="example"
              validation="^required"
            />
```

in the registered component i don't hav a this.context.attributes.modalOptionsName but i have a this.context.attributes['modal-options-name']

**Comment by andrew-boyd** [comment]
@bingo-ingo would you mind creating a minimal reproduction using either Codepen or Codesandbox? We have helpful starter templates available here: https://vueformulate.com/guide/community/#code-playgrounds

**Comment by justin-schroeder** [comment]
@bingo-ingo I believe what you're describing is prop hyphenation. Attributes are always hyphenated in HTML, so attributes will never camelCase by default. I think what you're actually looking to do is use a `slotProp`:

https://vueformulate.com/guide/inputs/slots/#declaring-slot-props

These slot props currently don't work for the main content element, but there is a pull request to add support for that: #231
