### ISSUE TITLE
Google Address Autocomplete Component

### ISSUE THREAD

**Issue by christianechevarria** [wearebraid/vue-formulate#240]
**Describe the new feature you'd like**

 I noticed that there is no address example within the docs, these days it's pretty much a given that you'll have autocomplete on an address field within a website. I was wondering if VueFormulate would ever include an address auto-complete like the popular https://www.npmjs.com/package/vue-google-autocomplete ? 

It would certainly be handy to have a component that behaved like the other inputs but had that functionality out of the box. For now I'll just be mixing and matching, but it's less than ideal

**Comment by andrew-boyd** [comment]
@christianechevarria Vue Formulate aims to "smooth out" the API for all _native_ HTML input types. What you're describing is what we would categorize as a _synthetic_ input. While we'd love to see a Vue Formulate input to support this use-case it would be done as a separate [plugin](https://vueformulate.com/guide/plugins/) and not something we would include in Vue Formulate core.

**Comment by justin-schroeder** [comment]
I've taken note of this, but agree with @andrew-boyd on it. For now these types of inputs wont be coming to core.
