### ISSUE TITLE
Form values won't update/reset when switching pages

### ISSUE THREAD

**Issue by sergeyfilimonov** [wearebraid/vue-formulate#247]
Two pages:
1. https://next.edmarket.ru/w/become-a-techadmin-of-online-school/#order
2. https://next.edmarket.ru/w/childrens-education/#order

If you type anything in the form on page 1 and switch to page 2 — all the data (`values` object in v-model) from the previous page will be transferred into the page 2 form. Here is the code:

```js
<template>
  <FormulateForm
    :name="name"
    @submit="handleSubmit"
    v-model="values"
    :schema="schema">
  </FormulateForm>
</template>

<script>
import Vue from 'vue'
import VueFormulate from '@braid/vue-formulate'
import { ru } from '@braid/vue-formulate-i18n'

import qs from 'qs'
import axios from 'axios'

Vue.use(VueFormulate, {
  plugins: [ ru ],
  locale: 'ru'
})

export default {
  props: {
    name: {
      type: String,
      default: ''
    },

    schema: {
      type: Array,
      required: true
    },

    zapier: {
      type: Object
    },

    redirectUrl: {
      type: String,
      default: '/thanks'
    },

    theme: {
      type: String,
      default: 'light'
    }
  },

  data: () => ({
    values: {},
  }),
}
</script>
```

The schema looks like:
```js
{
          type: 'hidden',
          name: 'product',
          value: $page.page.slug
        },
        ...forms.register.fields,
        {
          type: 'submit',
          label: forms.register.buttonText
        }
```

So the problem is that the crucial `product` field is not updated. So if you visited page 1, then switched to page 2 and submitted the form — the form data will have product from page 1.

I tried to add this:

```js
mounted() {
    this.$formulate.reset(this.name)

   this.values.product = this.name
  },
```

But the console shows a warning `[Vue warn]: Error in mounted hook: "TypeError: undefined is not an object (evaluating 'e.hideErrors')"` so `reset()` is not working. It's working only within methods if you manually call it.

Note sure if it's a bug but I couldnt' find any information on this in the docs and my attempts to resolve the issue didn't have success.

**Comment by andrew-boyd** [comment]
@sergeyfilimonov a couple of things.

- It sounds like you have multiple forms, correct? Could you give them unique names? eg `name="foo"` and `name="baz"`.
- When using `this.$formulate.reset()` you pass in the form name as a string. `this.name` is undefined based on the code you posted. Given your example form is `name="name"` you should try `this.formulate.reset('name')`.

Does that help?

**Comment by sergeyfilimonov** [comment]
@andrew-boyd the `name` variable is defined in the props so it does give a unique name to a form.

I solved the issue another way. It turned out that as the two pages have similar root — `/w/` in this case — vue-router didn't re-render the form component and the mounted() and created() hooks were not called by design.

So to update the product field I'm now using a watcher for $route:

```js
watch: {
    $route(to, from) {
      this.values.product = this.name
    }
  }
```

More about this: https://router.vuejs.org/guide/essentials/dynamic-matching.html

Thanks for your time!

**Comment by andrew-boyd** [comment]
Glad you got it figured out, thanks for reporting back!
