### ISSUE TITLE
Select input with array options buggy

### ISSUE THREAD

**Issue by Yiddishe-Kop** [wearebraid/vue-formulate#250]
I have a select input, where I pass an array of objects to the `options` prop, as described in the [docs](https://vueformulate.com/guide/inputs/types/select/#select-2).

My object looks like this:
```js
[
  {
    label: 'Option 1',
    value: 1
  },
  // ...
]
```

But the behaviour is wierd. I can select any option, but just before I submit the form, it reverts to the initial value. When inspecting in Vue devTools I see that selecting another option never updated the component state.

**Comment by justin-schroeder** [comment]
This might be related to #244 which will be fixed in 2.4.4, but in the meantime try adding an `id` to each option object.

**Comment by Yiddishe-Kop** [comment]
I solved it by converting the `value`s to a `String`...

Wierd and undocumented, but seems like using a `number` as the `value` causes issues.
