### ISSUE TITLE
Class Prop Extension

### ISSUE THREAD

**Issue by jtabalujan2** [wearebraid/vue-formulate#251]
Hi,

I was wondering if it would be a good idea to allow users to extend current base styles that are applied in the options when they apply another class? I am currently using Tailwind + Formulate and would like some inputs to be slightly different to the base.

Currently I have a setup similar to this:
```javascript

export const formulateOptions = {
  classes: {
    errors: "px-4",
    error: "text-red-700",
    input: context => {
      switch (context.type) {
        case "text":
        case "password":
          return (
            "border-pf-lighter-grey border-2 rounded-md password-input mt-2 w-7/12 h-32"
          );
    }
  }
};
```

And in a component, I'd implement it like this:
```html
<div>
        <FormulateForm v-show="show">
          <FormulateInput
            type="text"
            label="Card Nickname (Optional)"
            input-class="w-full"
          />
          <FormulateInput type="button" label="Save" />
        </FormulateForm>
</div>
```

Unfortunately the entire input-class gets overwritten with only w-full and none of the original input-class settings in my formulateOptions variable are there.

Perhaps, we could add a prop like ```extend-class``` w/ a similar key in the ```context```  that is passed in the options.

That way, the final implementation would look something like this? And in the ```<FormulateInput />``` we have a 'extend-class' prop that is always available?

```javascript
//formulateOptions.js
        case "password":
          return "border-pf-lighter-grey border-2 rounded-md password-input mt-2 w-7/12 h-32 " + context.extendClass
```

**Comment by justin-schroeder** [comment]
@jtabalujan2 thanks for a well described issue. I believe Vue Formulate already supports exactly what you want to do. Props can be 1 of 3 value types:

- Strings (these override as you described)
- Arrays (these extend, like you want to do)
- Functions (these give you the power to mix/match with additional logic)

In your case just use an array:

```vue
<FormulateInput
  type="text"
  label="Card Nickname (Optional)"
  :input-class="['w-full']"
/>
```

The docs describe this functionality here:

https://vueformulate.com/guide/theming/customizing-classes/#arrays-to-append-to-base-classes
