### ISSUE TITLE
Raw help text output

### ISSUE THREAD

**Issue by jdcifuentes** [wearebraid/vue-formulate#253]
There is a way to simply output raw help text, i.e if i want to include a simple link <a></a> tag? This could be really helpful. Or an alternative?

Thank you for this amazing work.

**Comment by justin-schroeder** [comment]
Howdy @jdcifuentes.

Checkout #158 which asked the same question. Basically yes you can do this, but you'll just need to expose a slot component on for `errors` since using `v-html` is a threat vector we don't want to open in the primary core. Best of luck 👍
