### ISSUE TITLE
I want to use the label value in the error message.

### ISSUE THREAD

**Issue by ahndohun** [wearebraid/vue-formulate#255]
I want to use label value instead of name value in error message.

In the case of a non-English speaking country, the language of that country is used for the actual input form, but English is used for the actual code (schema, etc.)
The error message is displayed awkwardly.

name:'email',
label:'이메일,

Email 필수 항목 입니다. -> 이메일 필수 항목 입니다.

Note: 이메일 is the same word as email in Korean.

**Comment by justin-schroeder** [comment]
There is a 'validation-name' prop available to all inputs that lets you give the field a more legible name for use in validation messages:

```js
<FormulateInput
  name="xflwwr"
  validation="required"
  validation-name="secret code"
/>
```

**Comment by ahndohun** [comment]
I had to take a closer look at the documentation. Thank you!

**Comment by Pondake** [comment]
I know this is an old issue but for anyone having the same issue; you can use this to globally select the label for your validation messages.

```
Vue.use(VueFormulate,  {
    validationNameStrategy: ['label']
})
```
