### ISSUE TITLE
Optional validation inside FormulateForm doesn't work as expected

### ISSUE THREAD

**Issue by joaquinwojcik** [wearebraid/vue-formulate#256]
**Describe the bug**
Validation message of optional fields that are inside a FormulateForm doesn't hide right after field is cleared. It waits until next render.

**To Reproduce**
1. Go to CodeSandbox
2. Click on Email or WhatsApp
3. Type anything you want and delete it.
4. Validation message still appear until you change other field inside the form.

### CodeSandbox

https://codesandbox.io/s/bug-with-optional-fields-inside-formulateform-ubdis?file=/src/components/Reproduction.vue

**Expected behavior**
Validation message should disappear when optional field is empty.

**Screenshots**
![image](https://user-images.githubusercontent.com/3205737/93778179-f8567480-fbfb-11ea-8d04-3778f2e90efd.png)

I clear email field. Message changed to "Please enter a valid email address"
![image](https://user-images.githubusercontent.com/3205737/93778190-fee4ec00-fbfb-11ea-8ef2-ac3dec3cb245.png)

I clear WhatsApp Phone field. Email's validation disappear.
![image](https://user-images.githubusercontent.com/3205737/93778203-04dacd00-fbfc-11ea-88bf-d89e44c31137.png)

**Device information:**
 - Device: Desktop PC
 - OS: Windows 10
 - Browser: Chrome
 - Version: 85.0.4183.102 (official build) (64 bits)

**Comment by joaquinwojcik** [comment]
(continuing discussion from #126)

@justin-schroeder 
I was creating the sandbox when I realized that the problem was related to optional fields inside formulate form and not to custom validation rules.

**Comment by justin-schroeder** [comment]
Great reproduction, I think I know what's going on here but I'll dig into it 👍

**Comment by joaquinwojcik** [comment]
I think I found the problem.

I'm calling `performValidation` on FormulateForm `input` event to check form validity and based on it, disable a button.
In the first render I'm getting `Cannot read property 'hasValidationErrors' of undefined`, and this breaks the validation.

```
<FormulateForm v-model="account" @input="performValidation" ref="form">
<!-- [all form fields] -->
</FormulateForm>

[...]
data() {
    return {
      account: {},
      hasErrors: false,
    };
},
methods: {
    async performValidation() {
      // following line is breaking validation
      this.hasErrors = await this.$refs.form.hasValidationErrors();
    }
  }
[...]
```

If I stop listening to `input` event or if I remove that line, the validation works fine.

So `input` event is being fired before Vue register the `$refs`. Is that even possible?
