### ISSUE TITLE
Select input with array options buggy

### ISSUE THREAD

**Issue by willans** [wearebraid/vue-formulate#258]
As originally highlighted in #250 - the hope was it was related to #244; I've updated to 2.4.4, but the bug still persists.

<formulate-input
	v-model="test"
	type="select"
	:options="[
		{ value: 0, label: 'First name' },
		{ value: 1, label: 'Last name' },
		{ value: 2, label: 'Middle Initial' },
	]"
/>

Adding IDs doesn't make a difference. Changing the values to text rather than numbers does, but it's not practical.

- If I select an option, the data updates.
- If I then select an option that isn't 0, it doesn't update.

However

- If I select an option, the data updates. 
- If I then select 0, it updates.
- If I then select another option, it updates. But only if the previous value was 0.

**Comment by justin-schroeder** [comment]
Values need to be strings. HTML doesnt support non-string values. Can you provide a reproduction of it not working with string values?

**Comment by justin-schroeder** [comment]
And/Or if we think we should support raw numeric values how can we do that properly? Should we re-cast all values to strings?

**Comment by willans** [comment]
In hindsight, you're correct. One of those things that are so forgettable. This can probably be closed now.

**Comment by justin-schroeder** [comment]
Ok, ill close for now, but if anyone has suggestions on how we can betters support numeric keys, im all ears, just not quite sure what the best way to do this will be. When we end up supporting Vue 3 we could do this potentially with a custom v-model modifier.

**Comment by lsbyerley** [comment]
@justin-schroeder seeing this when using a Form Schema with a group of text inputs too, the warning is: 

`[Vue warn]: Duplicate keys detected: 'el-1-undefined'. This may cause an update error.`

Am I missing something in the group schema? It looks something like this..

```
{
  type: 'group',
  name: 'directions',
  validation: 'min:1,length',
  repeatable: true,
  'add-label': '+ Add Direction',
  value: [{}],
  children: [
    {
      component: 'div',
      class: 'flex directions',
      children: [
        {
          type: 'text',
          name: 'text',
          label: 'Text',
          validation: 'required',
        },
        {
          type: 'hidden',
          name: 'completed',
          value: false,
        },
      ],
    },
  ],
},
```

**Comment by justin-schroeder** [comment]
@lsbyerley what version of Vue Formulate are you using? There was a fix for that exact bug just published last week `v2.4.4`. If you upgrade and still have an issue, create a reproduction and file a new issue and I'll definitely take a look. Thanks!

**Comment by lsbyerley** [comment]
@justin-schroeder i'm actually on v2.4.4 and I copy pasted the wrong schema, but it's pretty much the same, however this one actually has two text inputs instead of one like I posted a few minutes ago

```
{
  type: 'group',
  name: 'ingredients',
  validation: 'min:1,length',
  repeatable: true,
  'add-label': '+ Add Ingredient',
  value: [{}],
  children: [
    {
      component: 'div',
      class: 'flex ingredients',
      children: [
        {
          type: 'text',
          name: 'amount',
          label: 'Amount',
          validation: 'required',
        },
        {
          type: 'text',
          name: 'item',
          label: 'Item',
          validation: 'required',
        },
        {
          type: 'hidden',
          name: 'completed',
          value: false,
        },
      ],
    },
  ],
},
```

**Comment by justin-schroeder** [comment]
Got it. Would you mind creating a new bug report issue for this then with a reproduction of this on code sandbox? That will help make sure it doesnt get lost in the shuffle. The reproduction template is here:

https://codesandbox.io/s/vue-formulate-reproduction-template-p5c1i?file=/src/components/Reproduction.vue

Thanks!

**Comment by lsbyerley** [comment]
@justin-schroeder sure will do, thank you!

**Comment by lsbyerley** [comment]
https://github.com/wearebraid/vue-formulate/issues/275

**Comment by merijnponzo** [comment]
Same problem here. When i switch my select dropdown, the value changes back to it's original state.
And the model is not not synced

My formfields are based on a json file (not from the vue-formulate form generator, this is still on my todo list)
The options are generated async

1. I have a component called FormFields.vue
2. on mounted my FormData synced with all of the model and option fields from  the json file
with async await, for the providers
added with 
```
 this.$set(field, 'options', options)
```
3. Then the FormFields template renders the fields once

```
<FormulateInput
    v-bind="field"
    v-model="field.model"
    :name="i"
    :options="field.options"
    :label="field.translatedLabel"
    @validation="setValidation"
    :class="{ required: field.required }"
    />
```

```
 breeds: {
      model: [],
      options: [],
      type: 'select',
      provider: {
        type: 'api',
        endpoint: `${process.env.strapi.uploads}/breeds.json`,
      },
      map: { value: 'id', label: 'name' },
      mutate: {
        create: { handler: 'dataToModal' },
        post: { handler: 'modaToData', prop: 'value', type: 'array' },
      },
      validation: 'required',
      label: 'breed',
      help: 'max2breeds'
    },
```

When i try the (not async) examples from https://vueformulate.com/guide/inputs/types/select/#select-2
it works

- Should i create a custom form field for async options?

With the checkbox field and the same approach as above it's working. With the radio fields it's also not working

**Comment by merijnponzo** [comment]
Okey, i see that i should add a value attribute to my formfield object, which refers to the value field within the options.

For me, that wasnt clear within the documentation, only the example with options as an object

```
<template>
  <main>
    <FormulateInput
      type="select"
      v-model="formfield.value"
      :options="formfield.options"
    />
    <pre>
      {{ formfield.value }}
    </pre>
  </main>
</template>
<script>
export default {
  data() {
    return {
      formfield: {
        value: 'first',
        options: [
          { value: 'first', label: 'First name' },
          { value: 'last', label: 'Last name' },
          { value: 'initial', label: 'Middle Initial', id: 'name-initial' },
        ],
      },
    }
  },
}
</script>
```
