### ISSUE TITLE
Events list in docs for file upload (especially removeFile)

### ISSUE THREAD

**Issue by titusdecali** [wearebraid/vue-formulate#259]
**Describe the new feature you'd like**

I didn't see any reference to an events list in regards to the fileUpload box.
I'm trying to access the `remove file` event.

If it exists, please let me know how to access it, otherwise I'd love to see this feature. 

For my specific use case, I'm parsing an uploading PDF file and displaying the file details to the user (pdfSize, pdfName, etc). If I can get the removeFile event, I'd be able to remove that parsed info when they remove the file so that there is no confusion for the user as to what is currently uploaded.

I've tried `@remove` / `@removeFile`, etc. but no dice.

**Comment by justin-schroeder** [comment]
Hmm, i dont think we have events for those right now. Good feature request though, i'll tag it for 2.5

**Comment by justin-schroeder** [comment]
@titusdecali these events are now a thing on the `release/2.5.0` branch with cypress backing tests (finally added a way to test the file inputs). Early docs here:

https://vueformulatecom-git-release-250.braid.vercel.app/guide/inputs/types/file/#events

**Comment by titusdecali** [comment]
Did I mention that you are the man? Cause you are _the_ man!

**edit:** in light of recent social changes, please don't take this comment as a statement that men are better than women.
