### ISSUE TITLE
Schemas: Possible to have two repeatable groups with one group split width and the other group full width?

### ISSUE THREAD

**Issue by lsbyerley** [wearebraid/vue-formulate#260]
This seems like more of a question than a feature, but I'm not sure because I've tried multiple ways to do this in the schema (without adding any custom css, currently using tailwlindcss)

I'm working on a form that will have two repeatable groups. The first group will have two inputs side-by-side at 50% width, the second group will be one input at 100% width. I'd like to display both groups in a column with each column being 50% width. 

The desired outcome is below (ingredients being the first group, and directions the second group:

![Screen Shot 2020-09-24 at 9 52 31 PM](https://user-images.githubusercontent.com/3066258/94217578-5dd28b80-feb0-11ea-971e-6e776d0c48dc.png)

Based on the schema I have, the screenshot below is all I can accomplish:

![Screen Shot 2020-09-24 at 9 52 44 PM](https://user-images.githubusercontent.com/3066258/94217613-7478e280-feb0-11ea-986e-776f19c0b40c.png)

As you can see, I can't get the inputs in group 1 (ingredients) to be side-by-side and in group 2 (directions), i can't get the input to fill the width. Adding individual classes to children inputs doesn't seem to work

My schema code is below, any help is appreciated!

```
{
  component: 'div',
  class: 'grid grid-cols-2 gap-6',
  children: [
    {
      component: 'div',
      class: 'flex',
      children: [
        {
          type: 'group',
          name: 'ingredients',
          validation: 'min:1,length',
          repeatable: true,
          'add-label': '+ Add Ingredient',
          value: [{}],
          children: [
            {
              type: 'text',
              name: 'amount',
              label: 'Amount',
              validation: 'required',
            },
            {
              type: 'text',
              name: 'item',
              label: 'Item',
              validation: 'required',
            },
          ],
        },
      ],
    },
    {
      component: 'div',
      class: 'flex',
      children: [
        {
          type: 'group',
          name: 'directions',
          validation: 'min:1,length',
          repeatable: true,
          'add-label': '+ Add Direction',
          value: [{}],
          children: [
            {
              type: 'text',
              name: 'text',
              label: 'Text',
              validation: 'required',
            },
          ],
        },
      ],
    },
  ],
},
```

**Comment by justin-schroeder** [comment]
Howdy!

At a quick glance it seems like the flex wrapper is in the wrong place. Remember, anything you put inside a `group` input type will be part of the repeated elements, so in your case, you want the `flex` wrapper inside the group, not outside. For example:

```js
{
    type: 'group',
    name: 'ingredients',
    validation: 'min:1,length',
    repeatable: true,
    'add-label': '+ Add Ingredient',
    value: [{}],
    children: [
        {
            component: 'div',
            class: 'flex',
            children: [
                {
                    type: 'text',
                    name: 'amount',
                    label: 'Amount',
                    validation: 'required',
                },
                {
                    type: 'text',
                    name: 'item',
                    label: 'Item',
                    validation: 'required',
                },
            ],
        },
    ],
}
```

I'll leave the stylistic fine-tuning to you though 👍

**Comment by lsbyerley** [comment]
You were right, I wasn't considering: `Remember, anything you put inside a group input type will be part of the repeated elements` 

Thank you for the tip and response! I noticed there is a community on discord so I will try post questions on there next time!

Edit: looks like community is actually VueLand.. is that the best place to ask questions regarding vue-formulate?
