### ISSUE TITLE
Passing explicit errors to inputs inside a group

### ISSUE THREAD

**Issue by last-partizan** [wearebraid/vue-formulate#261]
**Describe the bug**
Passing errors to group does not work.

**To Reproduce**
```vue
<template>
    <FormulateForm :errors="errors" :schema="schema" />
</template>

<script>
export default {
  computed: {
    schema() {
      return [
        { type: "text", name: "name", label: "Name" },
        {
          type: "group",
          name: "address",
          children: [{ type: "text", name: "city", label: "City" }]
        }
      ];
    },
    errors() {
      return {
        name: ["Invalid name"],
        address: [{ city: ["This city does not exist."] }]
      };
    }
  }
};
</script>
```

### CodePen:

https://codepen.io/last-partizan/pen/poyBXWa

**Expected behavior**
In this example i expect errors to be show for city field, but form show no errors.

**Comment by justin-schroeder** [comment]
Dang it. You're right @last-partizan, thanks for the great reproduction. We have tests ensuring validation errors work at-depth in groups, but its missing logic for passing explicit errors down. Temporarily it might make sense for to just apply the error to the top most group (in your case `address`), but I'll tag this as a bug that needs to be addressed.

**Comment by last-partizan** [comment]
Thanks for suggestion, i'm temporary fixed it by passing errors to each field directly :+1: 

And thanks for a great library, it's awesome!

**Comment by justin-schroeder** [comment]
This is now a thing in the `release/2.5.0` branch. We're adopting dot notation to reference inputs at a given group index without needing to use empty objects in between, and so you can still place errors on the entire group as a whole (under all the groups). Checkout the preview docs of 2.5 here:

https://vueformulatecom-git-release-250.braid.vercel.app/guide/inputs/types/group/#settings-errors-on-groups

Example of the dot notation:

```vue
<FormulateInput
  type="group"
  :repeatable="true"
  name="invitees"
  :group-errors="{
    '0.email': 'This email is already in use',
    '1.name': 'Pretty sure Rensmold isn’t a real last name'
  }"
  :value="[
    { name: 'Todd Berkins', email: 'todd@example.com' },
    { name: 'Stella Rensmold', email: 'stella@example.com' },
  ]"
>
  <FormulateInput
    name="name"
    label="Invitee's name"
  />
  <FormulateInput
    name="email"
    label="What is this user's email?"
  />
</FormulateInput>
```

Also, the dot notation is supported on `FormulateForm`. Docs for that here:

https://vueformulatecom-git-release-250.braid.vercel.app/guide/forms/error-handling/#group-input-errors

**Comment by last-partizan** [comment]
Thanks.

Trying yo adapt my code to this approach.

Is there particular reason/benefits for using dot notation over Array for errors?

I'm using Django REST Framework, and it returns errors like this:

```js
{
  "nested_field": [
    {}, // valid field
    {"field": ["Error message"]},
  ],
}
```

I haven't used much other frameworks, but i suppose noone is using dot notation for errors. And every framework user must write conversion utilities for this format.

Or I am mistaken, and dot notation is pretty standard format for nested errors?

**Comment by justin-schroeder** [comment]
@last-partizan it's the default notation for laravel errors, but mostly it keeps errors in a flat list that is grokable.
