### ISSUE TITLE
Request: Ignore input

### ISSUE THREAD

**Issue by hmaesta** [wearebraid/vue-formulate#262]
Would be nice to have a parameter that indicated that an input should be ignored on the v-model (not created automatically on the returned form data).

```vue
<formulate-input name="search-query" type="text" ignored />
```

##### Example:

A form that has an inline search ("**Search for an icon**"). That input is used just for the search and the selected item is an `input type=hidden` (because the user doesn't have to know the actual icon name, just see it).

![Screen Shot 2020-09-29 at 09 29 30](https://user-images.githubusercontent.com/741969/94558482-4a1f8000-0236-11eb-82a4-6a7e82635d92.png)

I know that the "icon search" is not usual, but it's real here.
Better examples would be "Search for a user" or "Search for a country".

.

### Why not just use an `<input>`?

As a Tailwind user it's easier to just use `<formulate-input>` to keep form standardisation.
My vue-formulate config files has ~150 _really-long_ lines and it's just better to keep the classes there. 
When using `<input>` I have to manually copy all classes – or use `@apply` on my CSS, that I would prefer to avoid at all costs.

**Comment by justin-schroeder** [comment]
@hmaesta I swear you and @gahabeen should go get a beer together 😀 🍻. You two have both been super helpful for the library and often have the same ideas for how to use the it :) He filed the same issue a while ago here #225. Thanks for the great write up on the issue, per usual — i'll close this one in favor of that one because it's already on the roadmap for `v2.5` 🎉

**Comment by hmaesta** [comment]
I am willing to do it, @gahabeen 😂

Sorry for the duplicated. I swear I searched all possible strings, but `#225` has a very technical title and I didn't make the connection.

**Comment by justin-schroeder** [comment]
Yeah good point ill change the title
