### ISSUE TITLE
Add ability to preview TIFF files with file input type

### ISSUE THREAD

**Issue by dosstx** [wearebraid/vue-formulate#263]
Please add ability to upload and get preview of TIFF files when using the FILE input type. I know the browsers can't render these natively, so may require a polyfill. If it's out of scope of this project, then I understand. Thank you.

**Comment by justin-schroeder** [comment]
Howdy @dosstx.

So tiff support would definitely fall outside the scope of this library _however_ the ability to use tiffs in your own inputs should not.


## Proposal

Currently the logic for the image preview is pretty simple:

```js
  loadPreviews () {
    this.files.map(file => {
      if (!file.previewData && window && window.FileReader && /^image\//.test(file.file.type)) {
        const reader = new FileReader()
        reader.onload = e => Object.assign(file, { previewData: e.target.result })
        reader.readAsDataURL(file.file)
      }
    })
  }
```
https://github.com/wearebraid/vue-formulate/blob/master/src/FileUpload.js#L186-L194

We could possibly expose this to user-land to allow people to define their own preview result for each file. The API could perhaps be something like:

**Globally:**

```js
import Vue form 'vue'
import VueFormulate from '@braid/vue-formulate'

Vue.use(VueFormulate, {
  imagePreviews (files) {
    // do whatever you want to the FileList and return with `previewData` property.
  }
})
```

**Props:**

```vue
<FormulateInput
  type="image"
  :imagePreviews="someFunction"
/>
```

In that case, you could use a TIFF parser to return a browser-supported image format for the upload preview. I think my question for you @dosstx is, if this was a feature, would you **_actually_** take the time to implement it in your own forms or is the barrier still too high?

**Comment by justin-schroeder** [comment]
Not seeing a whole lot of community enthusiasm about this, so I'm going to close this. Someone feel free to resurrect it should it gain significant importance at some point.
