### ISSUE TITLE
The computed property "errors" is already defined as a prop

### ISSUE THREAD

**Issue by mbalandis** [wearebraid/vue-formulate#268]
**Describe the new feature you'd like**

If you have vee validate installed it conflicts with 'errors' bag prop. I don't want to rename errors for VeeValidate, can you add a way to configure an error bag name for vue-formulate please? I need to use both packages.

Example how VeeValidate doing:
```
Vue.use(VeeValidator, {
  errorBagName: 'vee_validator_errors',
});
```

How yours could be:
```
Vue.use(VueFormulate, {
  errorBagName: 'formulate_errors',
});
```

Unlike https://github.com/wearebraid/vue-formulate/issues/264, I actually need it.

**Comment by justin-schroeder** [comment]
We dont use any error bags. can you show reproduction of how you are using (or trying to use) vee validate with vue formulate?

**Comment by mbalandis** [comment]
> We dont use any error bags. can you show reproduction of how you are using (or trying to use) vee validate with vue formulate?

A bit tough to show any code as it is private.

To reproduce, simply gonna throw lots of console logs if you have veevalidate installed: i have "vee-validate": "^2.0.3" (latest whichever by ^ ), and "@braid/vue-formulate": "^2.4.4". Vee validate is enabled globally so assigns errors as a bag where it stores the errors. When you make a form with some validation with vue-formulate and it just squacks in console.

Screenshot: https://share.getcloudapp.com/rRuoPeoP

Any workaround if you cannot do the option like I suggested? I want to avoid renaming 50 pages of errors to verrors or something for vee-validate

**Comment by justin-schroeder** [comment]
Could you create a trivialized reproduction example on code sandbox?

https://codesandbox.io/s/vue-formulate-reproduction-template-p5c1i?file=/src/components/Reproduction.vue

**Comment by mbalandis** [comment]
@justin-schroeder 

https://codesandbox.io/s/vue-formulate-reproduction-template-forked-ws7xd?file=/src/components/Reproduction.vue

Didn't even add a validation to formulate. See "problems" tab

**Comment by justin-schroeder** [comment]
@mbalandis, thanks for the example. In it you're using VeeValidate 2.x which auto-injects properties. I believe that's the issue. You can (and probably should) disable that feature, i believe its been removed in version 3 anway. Here's your example uses VeeValidate 2 which has auto injection disabled:

https://codesandbox.io/s/vue-formulate-reproduction-template-forked-4tddz?file=/src/components/Reproduction.vue

And the version 2 docs about that feature: https://vee-validate.logaretm.com/v2/concepts/injections.html

Either way, not much I can do on the VueFormulate side to prevent this from happening, so I'll close out this issue.
