### ISSUE TITLE
Input file triggers the upload multiple times on form submit

### ISSUE THREAD

**Issue by acemir** [wearebraid/vue-formulate#270]
**Describe the bug**
When the user tries to submit a form while uploads from a `formulate-input type=file upload‑behavior=live` are in progress, a serious of questions happen, like: new attempts of uploads of the same file happen simultaneously, the progress bar starts flashing, the form submit is fired several times at the end of the uploads.

**To Reproduce**
**1.** Go to the [pen](https://codepen.io/acemir/pen/LYNKexE) and open the console.
**2.** In the first form, select or drag one or more files on the input. The upload of the selected files will start.
**3.** While the files are submitted, click the submit button one or more times.
**4.** Notice the following behaviors:
**- 4.1** See the strange behavior of the file progress bars.
 **- 4.2** In the console, see the record of file upload attempts. Notice that an additional attempt occurs with each click on the submit button.
**- 4.3** When you finish the uploads, see an alert informing you, for each attempt, the completion of the form submissions. In the console, see the record of form submit attempts. Notice that each form submission was done with the results of the last upload attempt.

The second form implements a function with `@submit-raw` that disables the submit button at each attempt.
Assuming that the file upload is in progress, when an attempt is made to submit the form, two additional attempts are made to upload each file. At the end the form is submitted with the results of the last attempt. 

In addition, the first attempt to upload a file with the name README.md will intentionally fail in order to trigger the `Promise` reject behavior. If you try to submit the form after this failure, you will be able to see in the console that a new upload attempt will be triggered (for all files, even those that were successful previously) and completed successfully, but note that the progress bar is not displayed and the error message does not disappear. Lastly the behavior 4.3 happens.

**Reproduction**
https://codepen.io/acemir/pen/LYNKexE

**Expected behavior**
**1.** Assuming the file upload is in progress, when an attempt to submit the form occurs, it should not attempt to upload the file again, but wait until the attempt in progress is completed.
**2.** When all uploads have been successfully completed, the attempt to submit the form should be made only once, even if several clicks on the submit button had occurred previously.
**3.** If at least one of the uploads fails, the form will not be submitted. When trying to re-submit the form, a new upload attempt should be performed only for the files that failed previously.

**Comment by justin-schroeder** [comment]
Thanks for the good report
