### ISSUE TITLE
Image preview behind next image on hover

### ISSUE THREAD

**Issue by acemir** [wearebraid/vue-formulate#272]
**Describe the bug**
When a `formulate-input type=image multiple` has multiple images in and the user hovers over the images further up, the scale preview appears behind the subsequent images.

**To Reproduce**
**1.** Go to the [pen](https://codepen.io/acemir/pen/xxVovow)
**2.** In the first form, select or drag multiple images on the input.
**3.** Hovers over the images further up.

**Reproduction**
https://codepen.io/acemir/pen/xxVovow

**Expected behavior**
The scaled image preview should appear in front of the others.

**Screenshots**
![HoverBug](https://user-images.githubusercontent.com/1908061/94989899-d94ad180-056f-11eb-979b-a06188974eca.gif)

**Device information:**
 - Desktop browsers

**Comment by justin-schroeder** [comment]
Thanks for a good report!
