### ISSUE TITLE
How do I edit the Date input icon? 

### ISSUE THREAD

**Issue by emforem** [wearebraid/vue-formulate#276]
How do I edit calendar icon? for the date input. Calendar only opens if icon is clicked not when input. Please fix :)

**Comment by justin-schroeder** [comment]
That icon and interaction is your browser's not Vue formulate. Checkout mdn for date inputs:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

**Comment by hacknug** [comment]
> How do I edit calendar icon? for the date input. Calendar only opens if icon is clicked not when input. Please fix :)

@mudassirmaqbool something like this should let you _customize it_ while preserving the functionality. Should work on webkit/chromium, not sure about other browsers (make sure you test before shipping).

The idea is you use a bg-image for the icon and position it with the other specific pseudo elements so they behave as one (to some extend).

```pcss
input[type="date"] {
  @apply relative pr-40 bg-right bg-no-repeat bg-contain;

  background-size: 16px;
  background-position: calc(100% - 12px - 1px);
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' aria-hidden='true' focusable='false' width='1em' height='1em' preserveAspectRatio='xMidYMid meet' viewBox='0 0 24 24'%3E%3Cg fill='none' stroke='%23626262' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Crect x='3' y='4' width='18' height='18' rx='2' ry='2'/%3E%3Cpath d='M16 2v4'/%3E%3Cpath d='M8 2v4'/%3E%3Cpath d='M3 10h18'/%3E%3C/g%3E%3C/svg%3E");

  &::-webkit-datetime-edit-fields-wrapper { @apply p-0; }
  &::-webkit-calendar-picker-indicator { @apply absolute right-14 w-16 h-16 m-0 p-0 opacity-0; }
}
```
