### ISSUE TITLE
Add slots to file inputs (Original use case: download links)

### ISSUE THREAD

**Issue by ahndohun** [wearebraid/vue-formulate#277]
You need to implement a feature that allows you to download files that have already been uploaded.
I want to map a file link to FormulateFiles but it fails.

Currently the FormulateFiles.vue component doesn't seem to have a way to extend it.

Could this be implemented in the future?

**Comment by justin-schroeder** [comment]
The `file` slot and slotComponent are now available in the `release/2.5.0` branch. Early docs available here:

https://vueformulatecom-git-release-250.braid.vercel.app/guide/inputs/types/file/#slots
