### ISSUE TITLE
Unable to set checkbox default value to false

### ISSUE THREAD

**Issue by uwufops** [wearebraid/vue-formulate#278]
**Describe the bug**
`true` is accepted as default value for checkbox, but `false` produces an empty string.

**To Reproduce**
1. Go to [the codepen](https://codepen.io/n-kim/pen/XWKrqpq)
2. See that `bar` is an empty string

**Reproduction**
https://codepen.io/n-kim/pen/XWKrqpq

**Expected behavior**
Checkbox input with `checked` and `value` property both set to `false` to produce `false` in the bound model.

**Screenshots**
<img width="215" alt="Снимок экрана 2020-10-06 в 12 00 30" src="https://user-images.githubusercontent.com/3971957/95181142-938a4500-07cb-11eb-84a3-a09e2165461f.png">

**Device information:**
 - Device: MBP 2019
 - OS: macOS 10.15.6
 - Browser: Google Chrome
 - Version: 85.0.4183.121

**Comment by justin-schroeder** [comment]
Yeah, this is a super common bug report. Unfortunately, HTML only supports string values. Vue sort of coerces the values to make it psuedo-work, but ultimately its not really supported with one exception — if you are doing a single checkbox, then the HTML is either "it has it" or "it does not have it" which is functionally equivalent to a boolean, so Vue casts those as bools. But for now, in general, use strings and you'll be in a good place.

**Comment by justin-schroeder** [comment]
Also, I think ill update the docs to help people with this, thanks for the quality report though!
