### ISSUE TITLE
Changing the locale of VueFormulate doesn't re-run the validations

### ISSUE THREAD

**Issue by atharva3010** [wearebraid/vue-formulate#282]
**Describe the bug**
On changing the locale of VueFormulate by using `$formulate.setLocale` method, it does not re-run the validations.
If I had an error returned out in another locale, it remains in that state if it’s ever triggered again.

**To Reproduce**
1. Set up internalization in VueFormulate, with i18n.
2. Run validations in the form.
3. Change the active locale using `$formulate.setLocale` method.
4. The errors are still in the old locale.

**Expected behavior**
The validations should be re-run on the form and the errors should be displayed in the appropriate locales.

**Device information:**
 It isn't a device specific issue.

**Comment by justin-schroeder** [comment]
@atharva3010 this is now implemented in the `release/2.5.0` branch. In order for inputs to have their locale automatically changed when `setLocale` is called, 2 things must be true:

1. The input must be nested inside a `FormulateForm`
2. The the `FormulateForm` must have a `name` attribute.

Other than that, no other changes are required in userland.

**Comment by atharva3010** [comment]
Thank you @justin-schroeder!
