### ISSUE TITLE
Clear the file input will cause "this.results.filter is not a function"

### ISSUE THREAD

**Issue by tlyau62** [wearebraid/vue-formulate#288]
**To Reproduce**
1. Go to 'https://vueformulate.com/guide/inputs/types/file/#file-2'
2. Choose a non-pdf file
3. Now, remove the file
4. You will see "TypeError: this.results.filter is not a function"

**Screenshots**
![image](https://user-images.githubusercontent.com/24647774/96328720-b7c20d80-1078-11eb-9242-18bb1cd340f1.png)

**Comment by justin-schroeder** [comment]
This is a bummer @tlyau62 I think it's a regression in `2.4.5`. Thanks for pointing it out.

**Comment by chototoro** [comment]
Hi, just to add some details to this bug i encountered too:
- it seems to happen on every file input when uploadBehavior is set to "delayed"
- after the TypeError, it is possible to select another file, but selecting the same file that was previously deleted doesn't work (the file select system dialog closes, but the file input stays empty)

**Comment by mgnrfk** [comment]
Hi,
Same issue here in `2.4.4`, upload behavior set to "delayed" + single pdf file removed

**Comment by justin-schroeder** [comment]
This is now fixed in the `release/2.5.0` branch and has a backing test in the new cypress e2e suite 👍
