### ISSUE TITLE
How can I use group with radio inputs?

### ISSUE THREAD

**Issue by HawkeyePierce89** [wearebraid/vue-formulate#289]
This is minimum template with the problem https://codesandbox.io/s/vue-formulate-reproduction-template-forked-s3i4l?file=/src/App.vue

When I select same radio input I see `{ "attendees": [ { "radio": false }, { "radio": false } ] }`,
but I should to see `{ "attendees": [ { "radio": true }, { "radio": false } ] }`
or `{ "attendees": [ { "radio": false }, { "radio": true } ] }`.

What am I doing wrong?

**Comment by justin-schroeder** [comment]
Surprisingly fascinating question. The primary issue is that in native HTML all radios with the same `name` attribute are "linked" together. So even though they are in different groups and technically have different models, they HTML is "binding" them together. Really the only way around this is to make sure they have different names. If you leave off the `name` attribute, vue formulate will automatically do this for you. Alternatively you can use the default slot to extract the index of the group and append that to the name. Like so:

https://codesandbox.io/s/vue-formulate-reproduction-template-forked-ldrhe?file=/src/App.vue

**Comment by zerbash** [comment]
@justin-schroeder is it possible to use the alternate technique with a schema-based form?

**Comment by justin-schroeder** [comment]
> @justin-schroeder is it possible to use the alternate technique with a schema-based form?

@zerbash It's possible in schemas if you implement a `slotComponent`:

https://vueformulate.com/guide/inputs/slots/#slot-components
