### ISSUE TITLE
Field visibility dependant on other field

### ISSUE THREAD

**Issue by paulrosen** [wearebraid/vue-formulate#29]
**Describe the new feature you'd like**
A form I'm trying to make has many options that change the form, like:
```
<label><input type="checkbox">Show Input></label>
<label>Only shown when above is checked<input type="text"></label>
```
Is there a way to do that or is that a planned feature? I can certainly do that with `v-if` sprinkled everywhere and that might be just as clear, but before I do that I was wondering if there was a better recommendation.

I will also be creating the form with a JSON object, so I'm planning on using the https://vueformulate.com/guide/forms/#generating-forms method and probably just adding additional info about what fields are dependent on others.

**What percentage of vue-formulate users would benefit?**
I have no idea. It's a common case in the apps that I build.

**Comment by justin-schroeder** [comment]
@paulrosen great question. we currently haven't though of a cleaner API than just using `v-if` on the elements you want to be conditional. Here's a codepen example: https://codepen.io/boyd/pen/qBdpeRj

Now that being said, if you're using generative forms, I would suggest using a computed property as the `v-for` iterator and then filter values based on the conditional logic you want.

The only feature we've though of for the roadmap is a `removal-behavior` prop on the `<FormulateForm>` component that allows you to decide what you want to happen to the data when a field is removed (does it remove its values from the form data or not).

If you have any suggestions on a clean api for conditionals, please suggest them, we're open to it.

**Comment by paulrosen** [comment]
The computed property sounds like a clean solution.

My intuition says that no matter how flexible the logic is for hiding and showing fields the next user will have a case that doesn't fit. So I was thinking that you could have a prop passed in for visible, but at that point it is just a `v-if`.

We're still gathering requirements, but when I start implementing the form I'll see if an api occurs to me.

The one thing that does occur to me that might keep me from using the `v-for` approach anyway is that there will be non-form items sprinkled throughout. It doesn't look like there is a way to specify a `<p>` in between two inputs. (That might be a different feature request.)

There are lots of different ways the form will look that are specified by the server, so I'll be getting the info as a JSON object. So there will be some form of the `v-for` approach even if I write it out in my template.

**Comment by justin-schroeder** [comment]
You can take this approach one step further if you want to sprinkle in non-like types and add a `component` key to your json:

```js
[
  {
    component: 'FormulateInput',
    type: 'text',
    name: 'name',
    label: 'What is your name?',
    placeholder: 'Your name...',
    validation: 'required'
  },
  {
    component: 'MyParagraphComponent',
    prop: ...
  },
  {
    component: 'FormulateInput',
    type: 'text',
    name: 'address',
    label: 'What is your street address?',
    placeholder: 'Your name...',
    help: 'Where would you like your product shipped?',
    validation: 'required'
  }
]
```

Then your `v-for` changes to:

```vue
<template>
  <component
    v-for="input in inputs"
    :is="input.component
    :key="input.name"
    v-bind="input"
  />
</template>
```

Also, I forgot to mention that repeater fields is something in the works too. Current syntax under consideration is:


```vue
<FormulateInput
  name="users"
  type="repeater"
>
    <FormulateInput
        name="email"
    />
   <FormulateInput
       name="name"
    />
    <!-- an add more button would be here -->
</FormulateInput>
```

The `<FormulateForm>` values submitted from such a repeater would be an array of values:

```js
{
  users: [
    { email: "email1@example.com", name: "justin" },
    { email: "email2@example.com", name: "paul" }
  ]
}
```

**Comment by justin-schroeder** [comment]
I'm going to close this for now, but create another one if you run into issues.
