### ISSUE TITLE
Label custom style when radio input is disabled

### ISSUE THREAD

**Issue by HawkeyePierce89** [wearebraid/vue-formulate#292]
Hello, how can I stylize `formulate-input-label--after` when radio input is disabled? For example, I want to set `opacity: 0.7;` for this label.

https://codepen.io/hawkeyepierce89/pen/mdErgjr

![image](https://user-images.githubusercontent.com/25603805/96712322-9ed29880-13a7-11eb-8b03-c30bfc761b47.png)

**Comment by justin-schroeder** [comment]
Howdy @HawkeyePierce89.

Checkout these docs on how to dynamically modify classes using class keys and class functions:

https://vueformulate.com/guide/theming/customizing-classes/#changing-classes-globally

Here's an example:
https://codepen.io/justin-schroeder/pen/GRqNoyZ

Good luck 👍
