### ISSUE TITLE
Should be able to place remove button after input in Repeatable Group

### ISSUE THREAD

**Issue by hbalenda** [wearebraid/vue-formulate#293]
I would like to propose the addition of a FormulateInput prop `removePosition` with possible values 'before' or 'after' that would determine the DOM element order of the repeated input and its remove button. The visual order of the elements of course can already be changed with CSS, but for greater accessibility for screen reader users it is more intuitive that the remove element follows the input element.

Happy to open a PR with this change, just wanted to invite any feedback before doing so.

**Comment by justin-schroeder** [comment]
Seems pretty reasonable to me, would love to see a PR for it. @hbalenda you seem to be making good suggestions in regards to accessibility in general. Is this something you're particularly well versed in? If so, I'd love a discriminating eye at the general state of accessibility across the board for VF. It is definitely something I'd like to see be a real value proposition.

**Comment by hbalenda** [comment]
@justin-schroeder I'm not going to claim to be an expert, but I am working on a project in which we would like to use vue-formulate where accessibility is a concern, and an accessibility consultant had pointed out these issues (and quite possibly there are more to come). I'm glad to hear you're interested in addressing accessibility across the board here, seems like we'll be able to work together to make some significant improvements.

**Comment by hbalenda** [comment]
Also @justin-schroeder I should add that if you are interested in an across the board review of vue-formulate's accessibility, you might get in touch directly with @sinabahram and @jscholes, who are experts in the field and have been providing my team with feedback. They are fantastic to work with and could provide real value to the library. I raised the issue with them, and @sinabahram mentioned they would be open to setting up a formal discussion.
