### ISSUE TITLE
Add aria labels to repeated inputs

### ISSUE THREAD

**Issue by hbalenda** [wearebraid/vue-formulate#294]
Proposing the ability to add aria labels to repeated inputs and remove elements to improve accessibility for screen reader users. The aria labels should include the index of the item, for example something like:

```
    <input aria-label="item 1"/><button aria-label="remove item 1"/>
    <input aria-label="item 2"/> <button aria-label="remove item 2"/>
```

Happy to work on a PR with these changes, just wanted to invite any feedback. Thank you!

**Comment by justin-schroeder** [comment]
@hbalenda Thanks for the ideas! Seems we should definitely have an aria-label for the remove. Are you specifically saying we should include the index in the labels? Also, from my (very limited) understanding, `aria-labels` are not desirable in the event that an input already has a `<label>`. I'd be really interested in any suggestions you have on how this can work in a more accessible way.

For what it's worth, you can always add your own `aria` attributes by just specifying them on the `<FormulateInput>`. For example:

```vue
<FormulateInput
  type="select"
  aria-label="My label here"
/>
```

So to do this on a group you could:

```vue
<FormulateInput
  type="group"
  :repeatable="true"
  #default="{ index }"
>
  <FormulateInput
    type="text"
    :aria-label="item ${index}"
  />
</FormulateInput>
```

That said, I'd really love to see accessibility level up "out of the box", so again, any suggestions you have would be very welcome.

**Comment by hbalenda** [comment]
@justin-schroeder I want to give this more thought before proposing an out-of-the-box solution. My additional concern is that repeatable groups of inputs will also need descriptive labels, and the repeated group itself will need a name (here, "Guest") e.g.:

```vue
<FormulateInput
  type="group"
  label="Guest List"
  :repeatable="true"
>
  <FormulateInput
    type="group"
    :aria-label="First Guest"
  >
    <FormulateInput label="First Name" />
    <FormulateInput label="Last Name" />
  </FormulateInput>
</FormulateInput>
```

In the meantime I'm creating PR to add index to the remove slot so that users can add their own remove button aria-labels with an index.
