### ISSUE TITLE
Add optional "name" property for file values

### ISSUE THREAD

**Issue by maksabuzyarov** [wearebraid/vue-formulate#296]
Hi! 

Could you please add an optional ```name``` property to display on the form?

```js
//from
[{url: '/uploads/file.pdf'}]

// to
[{url: '/uploads/file.pdf', name: '1000 varieties of avocado.pdf'}]
// name is not required
```

**Why is this needed?**

Because the values ​​that appear in the ```url``` are often unreadable in the form.

For example: 
```js
// from url
https://avatars2.githubusercontent.com/u/20745248?s=80&v=4

// using
url.substr((url.lastIndexOf('/') + 1) || 0)

// name result
20745248?s=80&v=4
```

![image](https://user-images.githubusercontent.com/20745248/97015849-b8fda980-1554-11eb-9273-926e80d4a48a.png)

**Thank you!**

**Comment by justin-schroeder** [comment]
Seems totally reasonable. We actually use a name property on initial upload, but I think we just don't use it when re-hydrating...

I'll tag this for inclusion.

**Comment by justin-schroeder** [comment]
Good news @maksabuzyarov this is now in the `release/2.5.0` branch. Early docs here:

http://localhost:8123/guide/inputs/types/file/#setting-initial-values

**Comment by maksabuzyarov** [comment]
Thank you very much!
