### ISSUE TITLE
Using "label" for validation messages, instead of "name" flag

### ISSUE THREAD

**Issue by sugoidesune** [wearebraid/vue-formulate#297]
The `validation-name` prop does exist, but would need to be updated seperately from the  Label.
It would be great if there was a flag type to set this behavior

`label_for_validation: true`

A step further would be to set this behavior globally during setup.
```
     Vue.use(VueFormulate, {
      options:{
         label_for_validation: true
       }
     })
```

with `validation-name` still available on a case by case.

**Comment by sugoidesune** [comment]
I missed it after reading through the docs left and right.
There is a `validation-name` prop.

https://github.com/wearebraid/vue-formulate/issues/255

**Comment by mashpie** [comment]
Looks like you could try plugin solution, see  #291

**Comment by sugoidesune** [comment]
haha yes just saw it. works like a charm.

**Comment by Pondake** [comment]
I know this is an old issue but for anyone having the same issue; you can use this to globally select the label for your validation messages.

```
Vue.use(VueFormulate,  {
    validationNameStrategy: ['label']
})
```
