### ISSUE TITLE
Accessibility: Make `label` mandatory && link help and error messages

### ISSUE THREAD

**Issue by ovlb** [wearebraid/vue-formulate#30]
Hello,

Thanks for creating this library. Looks refreshing. I did some testing and found some accessibility problems with your current structure:

- By default, `<label>`is disabled. A label is the only way for users of assistive technology to know what input they should enter; it should, therefore, be a required prop
- The help text needs to be associated with the input using [aria-describedby](https://developer.paciellogroup.com/blog/2018/09/describing-aria-describedby/). Otherwise, there is no way to know input and text belong together
- Same goes for error messages. 

I’m a maintainer of an inclusive component library (https://github.com/tournantdev/ui/). [This is our input component](https://github.com/tournantdev/ui/blob/master/packages/input/src/index.vue), in which these points are handled. If you like, I can help out with solving these issues. :) 

And a mostly unrelated question: Is it possible to conditionally display validation messages? E.g. if an e-mail is required can I only show the required message and not that is the wrong format? 

Best wishes,
Oscar

**Comment by justin-schroeder** [comment]
Hi @ovlb! These sound like great suggestions, and I would imagine we could dig up several other great accessibility additions too. I think what you're describing is pretty low hanging fruit too, so let’s knock it out!

Would you want to submit a PR to the `release/2.3.0` branch with some these adjustments? I've just added a roadmap "project" to this repository to track some of these changes/updates.

As for validation message "bailing" I think thats definitely something the project needs, I've added it to the roadmap for `2.3.0` too. Might be worth having its own issue thread, so I'll open one for that to continue the conversation here.

**Comment by ovlb** [comment]
Hey @justin-schroeder,

You are correct; these are kind of the low-hanging fruits regarding inputs. And pre-cautions that we, as UI library maintainers, can ensure, while a lot is beyond our control and requires educational effort, more than coding :) 

I will open a WIP PR over the next days!

Agreed that bailing is another discussion.

**Comment by justin-schroeder** [comment]
@ovlb any progress on that PR? You can target the `release/2.3.0` branch

**Comment by ovlb** [comment]
@justin-schroeder Sorry, the corona lockdown had me reeling a bit. I familiarised myself with the project over the last days and will add the PR until Sunday latest!

Best,
Oscar
