### ISSUE TITLE
Submit handler not picking up change in value

### ISSUE THREAD

**Issue by fire015** [wearebraid/vue-formulate#301]
Not sure if this is a bug or by design...

https://codepen.io/jason123456/pen/QWEpzxE

Choose a calendar size and then select 'yes' for print inside.

Setup charge quantity changes from 1 to 2 in the table (correct), but the data that comes through the handleSubmission event after clicking submit still sends the setup_charge_qty value as 1.

Using vue-formulate@2.4.5 and vue@2.6.12.

**Comment by justin-schroeder** [comment]
Hi @fire015,

Yeah, unfortunately this is a common gotchya. Basically you're setting the value of that input to a javascript `Number`, which is not a supported type for HTML inputs which only support strings. The good news — it's a quick fix:

https://codepen.io/justin-schroeder/pen/rNLmwjX?editors=1111
