### ISSUE TITLE
import only the modules that i need

### ISSUE THREAD

**Issue by merijnponzo** [wearebraid/vue-formulate#302]
First of all, great work- i couldn't do the user input without VueFormulate 👍 

I was wondering if it is possible, or in a later version to only import the fields I need.
Named by it's field types

```
import { Text, Button, Textarea } from 'vue-formulate'
```
Within my project I don't need the file uploader and the slider, i'm sure excluding them would save me a couple of kilobytes.

<img width="1250" alt="Screenshot 2020-10-27 at 09 25 20" src="https://user-images.githubusercontent.com/23075300/97279418-497d0800-183b-11eb-9a5c-0136d264e35f.png">

Best

**Comment by justin-schroeder** [comment]
It's possible we may do this someday, but most of the weight is not in the form of inputs so it wouldn't help all that much. Certainly this will not be a feature we roll out before version 3.

**Comment by merijnponzo** [comment]
Thanks, my guess is excluding the file-upload saves up to 10% filesize of the vue-formulate plugin.
It's good that it's there, but I use uploadcare for example, which has it's own file-uploader so i made a custom component for vue formulate.

But i can image more important things are on the roadmap :-)

Thanks again for this amazing plugin, and since my user forms are mostly behind the dashboard, i can async load the vue-formulate component wrapper as well

Best
