### ISSUE TITLE
Duplicate keys detected on select input

### ISSUE THREAD

**Issue by milos5593** [wearebraid/vue-formulate#305]
When using a select input I get duplicate keys error. I think it's the same as this issue for radio input #244

### Reproduction

https://codesandbox.io/s/vue-formulate-reproduction-template-forked-fsz69?file=/src/components/Reproduction.vue

**Comment by justin-schroeder** [comment]
![image](https://user-images.githubusercontent.com/1950463/97478867-ec12b500-1927-11eb-9bfb-a7362db4436e.png)

Could it be that there are 2 Alabama values here?

**Comment by milos5593** [comment]
@justin-schroeder You are right, I inherited that data from a client, and I didn't think it was wrong in any way.

I will mark as closed.
