### ISSUE TITLE
Extend the internal context object (specifically the attributes)

### ISSUE THREAD

**Issue by arjendejong12** [wearebraid/vue-formulate#306]
This feature request is specifically targetted towards 'aria-describedby' attribute in the attributes object of the context object, but I can imagine there are other use cases for other attributes or properties of the context object.

My use cases:
- Change the [default 'aria-describedby' ID](https://github.com/wearebraid/vue-formulate/blob/9d9509673bde58f1762b9ff1e2deeb896cdba594/src/libs/context.js#L195) when having a custom FormHelp component with a different ID.
- Append another ID when you have multiple elements that describe the input, for example: a custom FormError component that needs to be added to the 'aria-describedby' attribute of the input.

**Comment by justin-schroeder** [comment]
Thanks @arjendejong12. The `release/2.5.0` branch now allows you to override the `aria-describedby` attribute. If you do so, you'll be responsible for providing the full attribute which normally is automatically pointed at the id of the `.formulate-input-help` element.

As you noted, previously it was impossible to override this attribute. Most other attributes can already be overriden/specified directly on the outer element:

```vue
<FormulateInput
  aria-describedby="your-id"
/>
```

Good luck, and thanks for filing the issue!
