### ISSUE TITLE
Add a maximum property to FormulateInput with repeatable

### ISSUE THREAD

**Issue by hanneslehmann** [wearebraid/vue-formulate#310]
I would like to restrict the number of repeated inputs in group, for example:

```
<FormulateInput
            type="group"
            name="steps"
            label="Steps to be executed"
            add-label="+ Add Step"
            validation="required"
            :repeatable=step.addEnabled
            :maximum="2"
        >
```

Or is there any other way to restict adding an unbounded amount of additional inputs? I tried to work with enabling/disabling the repeatable flag, but that disables the option to remove items (which I would still need).

Is this somehow possible?

thanks!

**Comment by justin-schroeder** [comment]
Yep, you're looking for the `limit` prop, [documented on the group page](https://vueformulate.com/guide/inputs/types/group/#props). Good luck 👍

![image](https://user-images.githubusercontent.com/1950463/98009349-6e392880-1dc3-11eb-98f7-fcca6b2b0066.png)

**Comment by hanneslehmann** [comment]
Oh man, okay - I saw minimum, but not the limit ... would have been strange if there would not be any such feature ;)
Thanks a lot for your quick help!

**Comment by justin-schroeder** [comment]
Yeah understandable, you brain is looking for the word "maximum" but I choose to call it "limit" since "max" is already a common attribute on certain HTML inputs :) Glad i could be helpful!

**Comment by hanneslehmann** [comment]
Makes sense :) Bye and happy work!
