### ISSUE TITLE
Bind multiple inputs to one element

### ISSUE THREAD

**Issue by borisdayma** [wearebraid/vue-formulate#312]
**Describe the new feature you'd like**

I'm trying to create a component that is comprised of:
* an input text field
* a select element

![image](https://user-images.githubusercontent.com/715491/98641041-bd65e880-22f0-11eb-9b7d-9995985d4ca2.png)

I was thinking of a few ways to achieve it.

**Method 1: Custom input**
I would build a component similar to [FormulateInputText](https://github.com/wearebraid/vue-formulate/blob/master/src/inputs/FormulateInputText.vue) but I'm not exactly sure how I would use `v-model` since now I would have an object `{inputName: value, selectName, selectValue}`

**Method 2: wrapper with 2 FormulateInput**
I could wrap a custom element with:
* my own label
* 2 FormulateInput with no label and no classes (expect for the outer)

```javascript
<template>
  <div>
    <mylabel />
    <div class="my_wrapper">
      <FormulateInput type="text" />
      <FormulateInput type="select" />
    </div>
  </div>
</template>
```

With the correct classes I could probably achieve the expected outcome this way as well.

Any suggestions?

**Comment by borisdayma** [comment]
A bit hacky but it works with a custom input.

```javascript
<template>
  <div :class="context.classes.element" :data-type="context.type">
    <input
      :value="local.input"
      type="text"
      v-bind="attributes"
      @input="update('input', $event.target.value)"
      @blur="context.blurHandler"
      v-on="$listeners"
    />
    <div class="select_wrapper_class">
      <select
        aria-label="Country"
        class="select_class"
        :value="local.select"
        @input="update('select', $event.target.value)"
        v-on="$listeners"
        @blur="context.blurHandler"
      >
        <option
          v-for="option in options"
          :key="option"
          :value="option"
          v-text="option"
        />
      </select>
    </div>
  </div>
</template>

<script>
import FormulateInputMixin from './FormulateInputMixin'
export default {
  name: 'FormulateInputTextSelect',
  mixins: [FormulateInputMixin],
  data() {
    return {
      options: ['US', 'CA', 'EU'],
    }
  },
  computed: {
    local() {
      return this.context.model ? this.context.model : { select: 'US' }
    },
  },
  methods: {
    update(key, value) {
      this.context.model = { ...this.local, [key]: value }
    },
  },
}
</script>
```

Any suggestion of what can be improved?

**Comment by justin-schroeder** [comment]
This looks about right to me, not much i would change here. I might have gone with a v-modeled computed property with a `get` and `set` instead of `@input` events, but thats just a preference thing. I dont really think it looks that hacky honestly 👍

**Comment by borisdayma** [comment]
Thanks a lot for the feedback.
As I played with it over the past few days I realize how Vue-Formulate is powerful!
I think as it gets more examples it will be easier for users. Right now I get inspiration from the source files. 
Great project!

**Comment by handplant** [comment]
That looks good. Just what I need. Thx. 

Is there also a way to validate both fields?

**Comment by justin-schroeder** [comment]
@handplant validation rules are passed a `value` property in their context object. That value property would have both values so you could write a validation rule to check both items. Rules are intentionally easy to write:

https://vueformulate.com/guide/validation/#custom-validation-rules

**Comment by handplant** [comment]
@justin-schroeder Ok got it! Hier my rules:

```
validation="required|country|phonenumber"
:validation-rules="{
  country: ({ value }) => value.country,
  phonenumber: ({ value }) => {
    const regex = /^[0-9][0-9]{10}$/
    if (value) return !!value.number.match(regex)
    else return false
  }
}"
:validation-messages="{
  country: 'Please select a country',
  phonenumber: 'Please enter a valid number'
}"
```

But now I have another problem. The default setting "error-behavior" does not trigger the errors. Only `error-behavior="live"` works in my component. Any tip?

**Comment by justin-schroeder** [comment]
Did you rig up the `@blur` handler? `@blur="context.blurHandler"` on your inputs

**Comment by handplant** [comment]
@justin-schroeder That's it. Thank you very much!
