### ISSUE TITLE
Option to disable decorator in InputBox

### ISSUE THREAD

**Issue by arjendejong12** [wearebraid/vue-formulate#313]
I'd like the option to disable the rendering of the decorator in [the InputBox](https://github.com/wearebraid/vue-formulate/blob/1b6b3bc65fd93b9d6702aa0ac9f76baeee00a197/src/inputs/FormulateInputBox.vue#L37).
Some accessibility checking software flag it as an empty form label or that there are multiple form labels.

**Comment by justin-schroeder** [comment]
Makes sense @arjendejong12 any thoughts on how that should be done (from an API perspective)? Presumably if you did that you would want it to be global right? Something like:

```js
Vue.use(VueFormulate, {
  useInputDecorators: false
})
```

**Comment by arjendejong12** [comment]
That looks perfect to me!

**Comment by justin-schroeder** [comment]
@arjendejong12 this is now implemented in the `release/2.5.0` branch. Early preview docs available here:

https://vueformulatecom-git-release-250.braid.vercel.app/guide/inputs/types/box/#checkbox
