### ISSUE TITLE
pass on label,name as component props

### ISSUE THREAD

**Issue by sugoidesune** [wearebraid/vue-formulate#316]
Currently the `label` is not passed on to components even when set as prop.
Neither is the `name` prop.

```javascript
{
type: 'text', //not passed on
label: 'User Name', //not passed on
name: 'user_name' // not passed on
}
```
This would make integration easier as it doesn't require extra wrappers for thrd party components.
And unify the behavior

**Comment by justin-schroeder** [comment]
Can you provide a reproduction? Not sure I'm following. Specifically are you saying those are not passed as props to formulate inputs?

**Comment by sugoidesune** [comment]
So even though you might add `type, label and name` into the slotPorps of a custom component like so:
![image](https://user-images.githubusercontent.com/20317691/99137040-9547f380-2628-11eb-9793-cb7b9958e154.png)


They are undefined in the $attrs object, 
![image](https://user-images.githubusercontent.com/20317691/99137011-7b0e1580-2628-11eb-9bf5-0b319786fc03.png)


they are available in the context though, so its good enough for workarounds.
But nevertheless it is unexpected behavior.

I hope thats clear enough, otherwise ill make a reproduction.

**Comment by justin-schroeder** [comment]
Gotchya, yes, the base props are basically reserved words, but you can access their values in the `context` prop of your custom input.
