### ISSUE TITLE
@submit-raw triggered on normal button

### ISSUE THREAD

**Issue by JPortegijs** [wearebraid/vue-formulate#321]
I have a FormulateForm which contains collapsed elements, every click on a button to expand the collapsed section the event @submit-raw is fired. Is there a way to prevent this?

Thanks in advance.

**Comment by justin-schroeder** [comment]
Can you provide a reproduction please? Thank you!

**Comment by JPortegijs** [comment]
I hope this pen works: https://codepen.io/japortegijs/pen/rNLXLxq?editors=0010

Hope it helps :)

**Comment by justin-schroeder** [comment]
It very much does not work haha 😂 No worries, here's a codepen reproduction template to get going:

https://codepen.io/boyd/pen/YzyJPor

**Comment by JPortegijs** [comment]
Ha, sorry, mate. This should be better: https://codepen.io/japortegijs/pen/zYBgzQO

As you can see at initial load no red border is being shown. Once you click on "Click here" the checkValidation method is being called and adds a red border.

**Comment by justin-schroeder** [comment]
Ok, got it now.

This is default HTML behavior. [According to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button), here are the "rules" for the `type` attribute of a button:

```
The default behavior of the button. Possible values are:
- submit: The button submits the form data to the server. This is the default if the attribute is not specified for buttons associated with a <form>, or if the attribute is an empty or invalid value.
- reset: The button resets all the controls to their initial values, like <input type="reset">. (This behavior tends to annoy users.)
- button: The button has no default behavior, and does nothing when pressed by default. It can have client-side scripts listen to the element's events, which are triggered when the events occur.
```

When you don't define a `type` attribute on an HTML `<button>` element, and that button is inside a `<form>` (which it is in your case) then it defaults to `type="submit"`. So to "fix" your issues, just add `type="button"` to your control button and you should be good to go 👍

**Comment by JPortegijs** [comment]
How did I miss that... thank you!
