### ISSUE TITLE
Watch validation prop for changes to re-run validation

### ISSUE THREAD

**Issue by yeedle** [wearebraid/vue-formulate#322]
What a great library! Thanks!

I wasn't sure whether the following is a bug or maybe I'm missing something obvious.

**bug description**
Dynamically changing the validation of an input (by binding the `validation` prop) doesn't re-evalute the validation of that input. This leads to the some unexpected behavior like showing an error message even when the field is valid

**Reproduction**
In the following codepen I've created a required text input with a checkbox toggling a boolean. When you blur out of the text input, the error message shows up. Toggling the checkbox doesn't make the error message disappear although the validation for the text input changes.

### CodePen:

https://codepen.io/yeedle/pen/ExyBgKN

**Comment by justin-schroeder** [comment]
Yeah, I think this makes a lot of sense, ill tag it for 2.5.

**Comment by justin-schroeder** [comment]
@yeedle Thanks for the request — this update has been implemented in the `release/2.5.0` branch.
