### ISSUE TITLE
Disable checkboxes on "Multiple checkbox options"

### ISSUE THREAD

**Issue by tlyau62** [wearebraid/vue-formulate#324]
**Describe the new feature you'd like**

Add a disable config for certain options, such that the user can no longer disable it.

e.g.
[
  { value: 'first', label: 'First', id: 'my-first', disabled: true }, // this checkbox is disabled
  { value: 'second', label: 'Second' }
]

**Comment by justin-schroeder** [comment]
@tlyau62 it literally works exactly like that.

https://codepen.io/justin-schroeder/pen/KKgPGyV
