### ISSUE TITLE
Restrict time options

### ISSUE THREAD

**Issue by chadwtaylor** [wearebraid/vue-formulate#326]
Using `<formulate-input type="time">`, is it possible to restrict the available options of hours and/or minutes to the end-user.

For example, I want to restrict the minutes into 15-minute increments, eg `[0, 15, 30, 45]` instead of showing the whole range from `0 to 59`. 

One may want to restrict the hours as well, eg: `[4, 8, 12]`.

**Comment by justin-schroeder** [comment]
There is some ability to restrict controls with attributes, but I'll refer you to the excellent MDN documentation for the `time` input, which is what vue-formulate uses:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

Good luck 👍
