### ISSUE TITLE
How custom label checkbox group

### ISSUE THREAD

**Issue by yanielbf** [wearebraid/vue-formulate#329]
Hi, I need to create a checkbox group where the checkbox label has an image. Is this possible?. Regards

**Comment by justin-schroeder** [comment]
Sure, the easiest way to do this is just use a slot component to allow HTML in labels. For example, in your Vue Formulate config:

```js
const htmlCustomLabelComponent = {
  props: ["context"],
  template: `
    <label
      :class="context.classes.label"
      :for="context.id"
      v-html="context.label"
    />
  `
};

Vue.component("HTMLAllowedCustomLabel", htmlCustomLabelComponent);

Vue.use(VueFormulate, {
  slotComponents: {
    label: "HTMLAllowedCustomLabel"
  }
});
```

Then just use HTML on the label:

```vue
<FormulateInput
    type="checkbox"
    label="Checkboxes with images"
    :options="[
      { label: '<img src="your-image.png">', value: 'abc' }
    ]"
  />
```

Here's a working example:

https://codesandbox.io/s/vue-formulate-image-checkboxes-example-clbwf?file=/src/components/Reproduction.vue

Good luck 👍

**Comment by yanielbf** [comment]
Thank you for your help. This Library is amazing!!!
