### ISSUE TITLE
Input Text type of "month" doesn't render properly in Firefox

### ISSUE THREAD

**Issue by tomw07** [wearebraid/vue-formulate#330]
**Describe the bug**
In Firefox, the Input Text type of "month" doesn't open a month selector on click. Instead, it acts like a standard input field, which allows the user to input anything.

**To Reproduce**
1. Navigate to the Vue Formulate demo page in Firefox: https://vueformulate.com/guide/inputs/types/text/#month
2. Compare the month input to that of Chrome (which works correctly)

**Expected behavior**
Clicking on the input form should open the month selector

**Screenshots**
![image](https://user-images.githubusercontent.com/18583094/101193184-34f61180-362a-11eb-98a7-be137656c9ec.png)

**Browsers tested**
❌ Firefox: 78.5.0esr (64-bit)
✔️ Chrome 86.0.4240.198 (64-bit)

**Comment by justin-schroeder** [comment]
Thanks for the report, unfortunately you are correct that the `month` HTML input is not supported in firefox.

https://caniuse.com/?search=month

The time/datepicker inputs in general are the most poorly supported on different browsers although its improving over time. There's a note in the docs about this:

![image](https://user-images.githubusercontent.com/1950463/101194326-d7fb5b00-362b-11eb-9cb1-d99a32fde0c6.png)

Vue Formulate currently ships with all native HTML inputs, but is itself not a polyfill library. Best of luck, and feel free to report any progress you make back here for others.

**Comment by tomw07** [comment]
Thanks for the follow-up! We'll look into some possible solutions from our end.
