### ISSUE TITLE
Using value and model with required

### ISSUE THREAD

**Issue by merijnponzo** [wearebraid/vue-formulate#332]
Hello,

I'm building a autocomplete field with both v-model for textinput and :value for values

If i use validation required, I suppose it's validating on the v-model

Is it possible to point the validation to the value field instead of the v-model
Or by adding context or event handlers within my autocomplete component, but which one?

Thanks

**Comment by justin-schroeder** [comment]
Probably not, but can you provide an example? I'm not sure how/why you would need validation on something that isn't part of the form (v-model), so maybe you could help me understand by clarifying that further.

**Comment by merijnponzo** [comment]
thanks for the fast reply

So i created a component:
<img width="866" alt="Screenshot 2020-12-07 at 14 40 16" src="https://user-images.githubusercontent.com/23075300/101357798-388fcf80-389a-11eb-81a3-700b2cd7879a.png">

After each pick the model is cleared, since
```
setValue(val, label) {
      const name = this.context.attributes.name
      const option = {
        value: val,
        label: label,
        name: name,
      }
      // if array push, otherwise replace object
      if (this.$typy(this.context, 'value').isArray) {
        this.context.value.push(option)
      } else {
        // sentry
        console.log('this autocomplete should have a value array field')
      }
      this.selectedIndex = 0
      // behind blur modifier
      setTimeout(() => {
        this.context.model = null
      }, 250)
```
I bound the v-model to the context.model, thinking this trough this could be easily a data prop within my component, so I can leave out model in the form field scheme! :-)

```
   <input
          class="formulate-input-tag-input"
          type="text"
          v-model="context.model"
```

**Comment by merijnponzo** [comment]
Yes that's it. 
I guess it's a thing with autocompletes,
By typing and showing the options, the option value is often an ID instead of the v-model input value

I removed the model from my vue-formulate custom autocomplete, and only use the value field.
Now it's working

**Comment by justin-schroeder** [comment]
Hmm. you really shouldn't be pushing anythin ginto the `context.value` . I'm actually not sure how your input is working to tell you the truth. Inside a custom input you should only manipulate the `context.model`. You can put anything you want in there (array, object etc). The schema you choose is up to you, but a couple ways you could handle a tag input:

```js
// Array of ids that mean something in your database
context.model = [1, 2, 4]
```
or
```js
context.model = [
  { id: 1, label: 'French Spaniel' },
  { id: 1, label: 'French Poodle' },
]
```

Personally, I favor just storing an array of ids for my auto-completes, and then to re-hydrate the list i use a callback function to re-fetch the tags from the backend on load. That way the values are always up to date, the model represents what im storing on the backend, and its dead easy to use:

```vue
<FormulateInput
  type="autocomplete"
  name="tag"
  load-tags="loadFromBackendFn"
  v-model="tags"
/>

// where
// tags = [1, 2, 3]
```

It takes a bit to write that autocomplete really well, but once its done you have it in your repertoire forever. Ok, thats just my 2c, best of luck 👍

**Comment by merijnponzo** [comment]
That is some good advice Justin. Thank you for that.
I was planning to rebuild my vue-formulate extentsion soon :-)
