### ISSUE TITLE
Add or Allow 'name' prop/attribute to pass through to FormulateForm - Netlify Forms Support

### ISSUE THREAD

**Issue by brandiqa** [wearebraid/vue-formulate#333]
**Add `name` attribute in rendered `FormulateForm`**

Here's a simple example in Vue code:

```html
<FormulateForm
      name="contact-us"
    />
```

When I inspect the rendered HTML, the `name` attribute is missing. I believe this is what may be causing issues integrating with Netlify Forms

**Comment by justin-schroeder** [comment]
Hmm, you might be right about that causing issues for netlify @brandiqa, I think they do use the `name` attribute...

Ok, I'll tag this for the next release (2.5)

**Comment by brandiqa** [comment]
I believe the bots are using the `name` attribute to create a form submission "database". Thank you very much 🙌. Will look forward to the next release

**Comment by justin-schroeder** [comment]
@brandiqa this is now implemented in the `release/2.5.0` branch 👍

**Comment by pmcp** [comment]
@brandiqa , I'm having issues combining netlify forms and vueformulate. Form is detected by Netlify, but I can't get any submissions in.

Did you get it right? Do you have some code to share somewhere?

**Comment by brandiqa** [comment]
I encountered other issues with Netlify forms and so I completely gave up
on it. Currently using usebasin.com
