### ISSUE TITLE
Data is emitted to @input when FormulateForm is hidden with v-if

### ISSUE THREAD

**Issue by Rednas83** [wearebraid/vue-formulate#336]
**Describe the bug**
When FormulateForm is hidden with v-if multiple events are send for clearing the form.

**Expected behavior**
No emits are send after hiding FormulateForm. 

**Workaroud**
I used the beforeDestroy hook to disable the emitting of FormulateForm while being destroyed/hidden.

**Comment by justin-schroeder** [comment]
This sounds like a potentially legit issue, I'd really appreciate a codepen or codesandbox reproduction of the issue. Thanks!

**Comment by Rednas83** [comment]
I couldn't reproduce the issue with a codepen and I was able to fix the behaviour in my environment.
