### ISSUE TITLE
Validation max length (forced) with array syntax 

### ISSUE THREAD

**Issue by erkage** [wearebraid/vue-formulate#338]
Hi,

I have an input field where a phone number goes. I'm using the array syntax for the validation because it uses a complicated regex pattern. Also i'd like to add max length (forced) rule because i want to add a custom validation message to it. If i'm not forcing the length it just validates the value.

I've tried everything to achieve this with no luck.

Thanks in advance!

**Comment by justin-schroeder** [comment]
Do you want to limit the number of characters, or have a max length validation rule? Those are technically different things. You can [use the `maxlength` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/maxlength) to limit the number of characters on a given input.

You if you dont want to strictly limit the number of characters, but use a validation rule instead (wont submit, but allows a user to type in over-length values and shows an error message instead) you can do that [using the `max` rule](https://vueformulate.com/guide/validation/#max), something like:

```vue
<FormulateInput
  name="phone"
  :validation="[
    ['required'],
    ['matches', new RegExp(/\d+/)],
    ['max', 4, 'length']
  ]"
/>
```

Hope that resolves your question. If not, please make a reproduction of the issue and maybe we can work from that. Good luck 👍

**Comment by erkage** [comment]
Thank you Justin, looking exactly for this!
I've just haven't tried this 3 length array syntax thought it can be just 1 or 2. Tried `['max:5,length']`, `['max,4,length']` and `['max', '4,length']` 🙂 .

**Comment by justin-schroeder** [comment]
ah, gotchya. Yeah everything separated by a comma in the string notation is a new array item in the array notation. Build something great 🚀
