### ISSUE TITLE
Validation of individual groups within repeatable grouping

### ISSUE THREAD

**Issue by rbackert** [wearebraid/vue-formulate#339]
First off: great library!

The issue: My UI requires triggering validation on and getting the validation status of individual groups in a repeatable grouping. As far as I can tell, the context object's validation functions/values for a repeatable grouping and for all of its slots are relative to the entire repeatable grouping; none are relative to its individual groups.

Perhaps the context object in the repeatable slot could provide validation functions/values (e.g. performValidation(), hasValidationErrors()) for that individual group?

**Comment by justin-schroeder** [comment]
Agreed! This needs more work for sure. I believe this going to be addressed with resolution of issue #181. Mind taking a look at that and seeing if it meets your needs?

**Comment by justin-schroeder** [comment]
Closing this in favor of #181
