### ISSUE TITLE
Feature Request: array of strings as `:options` parameter in `type="select"` inputs

### ISSUE THREAD

**Issue by katerlouis** [wearebraid/vue-formulate#341]
It would improve DX immensely if the following would work:
`:options="['New York', 'Sydney', 'Berlin']"`

see #179 for discussion and workaround :)

**Comment by justin-schroeder** [comment]
Seems doable :) I'll tag this for 2.5 since there's a lot of quality of life improvements in there already.

**Comment by justin-schroeder** [comment]
Ok, this feature is implemented in the `release/2.5.0` branch.
