### ISSUE TITLE
Validation event only catering for the last FormulateInput field

### ISSUE THREAD

**Issue by MlamliLolwane** [wearebraid/vue-formulate#342]
**Describe the bug**
The validation event's hasErrors bool returns false when there are 2 or more FormulateInput fields and the first one is empty and the 2nd one has a value. 

**To Reproduce**
1. Html to reproduce 
![html](https://user-images.githubusercontent.com/53498225/102416648-e3bf2800-4002-11eb-833f-ae9554476c00.png)

2. JS to reproduce 
![js](https://user-images.githubusercontent.com/53498225/102416673-ef125380-4002-11eb-8a6f-4d4bd348e742.png)

3. Form before validation. See how it only picks up the last field. 
![before_validation](https://user-images.githubusercontent.com/53498225/102416693-fafe1580-4002-11eb-8548-46868edef199.png)

4. Form after validation. See how it only picks up the last field. 
![after_validation](https://user-images.githubusercontent.com/53498225/102416721-081b0480-4003-11eb-8d41-de72f8afa3e6.png)

5. See error... Even though the first name field was not provided but validation seems to pass. 
![actual_error](https://user-images.githubusercontent.com/53498225/102416737-123d0300-4003-11eb-8a63-a46036b3a5c4.png)

**Expected behavior**
I expect the validation object to have errors for both fields as they are both required but it seems to display an error only for the last FormulateInput field.

**Comment by justin-schroeder** [comment]
This is actually the intended behavior. The validation event is firing multiple times, each with each field's validation state. it's just that you are overwriting the value of your `validation` local variable. If you change your `<FormulateForm @validation>` handler to:

```
<FormulateForm
  @validation="$event => validation.push($event)"
 ...
/>
...

<script>
 ...
 data () {
  ...
  validation: []
 }
</script>
```

You'll see it accumulating events for each input. `hasErrors` refers to the validation state of the individual input, not the form as a whole. For that kind of info, checkout the `release/2.5` branch and specifically the upcoming form context object:

https://github.com/wearebraid/vue-formulate/issues/127
