### ISSUE TITLE
Group item collapsible

### ISSUE THREAD

**Issue by nikolaysm** [wearebraid/vue-formulate#343]
Is there a possibility to make group item collapsible?

```
<FormulateInput type="group" name="employments" :repeatable="true" label="Employments"
    add-label="+ Add Employment" #default="groupProps">
	<!-- Clickable area -->
	<div class="group text-sm font-semibold py-2 cursor-pointer relative" @click="groupProps.showForm">
		....
	</div>
	<!-- Nested form: must be collapsible accordion -->
	<div class="nested-form" v-show="groupProps.showForm">
		....
	</div>
</FormulateInput>
```

I thought to add `showForm` property to the group context.

For this I need to do `Custom input types` or is there some other way?

If anyone has any other ideas?

Thanks

**Comment by nikolaysm** [comment]
Hi @justin-schroeder, thanks for the great work and excellent documentation.

I don't have so much experience in VueJs. Can you even point out that I am on the right way? Is there only one way to create the `Custom input ` or is there even more efficient way?

Thanks for your awesome work!

**Comment by justin-schroeder** [comment]
Hi @nikolaysm,

There's nothing specific to vue formulate here, just some simple Vue logic should suffice. Here's an example I whipped up for you:

https://codesandbox.io/s/vue-formulate-collapsable-group-accordion-style-g612o?file=/src/components/Reproduction.vue:371-379

Best of luck 👍

**Comment by nikolaysm** [comment]
Thanks @justin-schroeder for your awesome example!
