### ISSUE TITLE
Linking v-model directly to vuex store empties object on form destroy

### ISSUE THREAD

**Issue by dangrima90** [wearebraid/vue-formulate#345]
**Describe the bug**
I have a set up where I'm setting the `v-model` of the form via a computed property that is reading from the vuex store. To save the data I'm using a setter in the computed property so that any changes in the form are reflected in to the store straight away.

Example:

_Template_

```
<FormulateForm v-model="data">
  <FormulateInput
    label="First Name"
    name="firstName"
  />
  <FormulateInput
    label="Last Name"
    name="lastName"
  />
  <FormulateInput
    label="Age"
    name="age"
    type="number"
  />
</FormulateForm>
```

_Script_

```
import { mapActions, mapGetters } from 'vuex';
export default {
  computed: {
    ...mapGetters({
      formData: 'formData'
    }),
    data: {
      get() {
        return this.formData;
      },
      set(newData) {
        console.log(newData);
        this.saveData(newData);
      }
    }
  },

  methods: {
    ...mapActions({
      saveData: 'saveFormData'
    })
  }
}
```

With this set up, when navigating away from the page the model is set to an empty object and thus resulting in the data being saved in the store as an empty object.

**To Reproduce**
Bind a `FormulateForm` to computed property and make sure to have a setter so that any time the object passed to the `v-model` is updated an action or mutation is run to update the store.

You should notice that when changing pages for example will result in the bound object being emptied.

**Reproduction**
https://github.com/dangrima90/vue-formulate-test

I have created a repository where this behaviour can be tested I've set up a simple project - in the `About.vue` there's two forms - one with an empty object and another with pre-populated data.

When navigating away from the page you'll notice console logs from the `set()` function that show the objects being emptied. To be honest I don't know if this is a bug from the library or there's something wrong with my setup.

**Expected behavior**
I expect the bound object to be the same when the form is destroyed.

I know you may ask why someone may want this setup. But in the application where I'm trying this out we'd like to have a functionality where the form data is saved in the store so that navigating away from the page and coming back would still have the data you entered previously.

**Comment by justin-schroeder** [comment]
Try adding `:keep-model-data="true"` to your `<FormulateForm>`.

**Comment by dangrima90** [comment]
That seems to have fixed the issue. Many thanks! I must have missed it in the documentation.
