### ISSUE TITLE
Pass validation rules to context

### ISSUE THREAD

**Issue by karachungen** [wearebraid/vue-formulate#347]
I would like to know what rules were applied to particular input form.
For example:
- Have possibility to mark Label with asterisk(*) to form items that are required (passed "required" validation rule)

Currently i use FormLabel parent component to get validation rules: See [CustomLabel](https://codesandbox.io/s/vue-formulate-reproduction-template-forked-0hpgu?file=/src/components/CustomLabel.vue:288-349) component
But it looks like nasty workaround, i suppose accessing to `this.context.validation` would be better if it possible

[Playground](https://codesandbox.io/s/vue-formulate-reproduction-template-forked-0hpgu?file=/src/components/CustomLabel.vue)

**Comment by justin-schroeder** [comment]
Good feature request! It's already tagged and pending dev on 2.5. Here's the dupe: https://github.com/wearebraid/vue-formulate/issues/149

Thanks!
