### ISSUE TITLE
Initial field value uses v-model even when the value prop is set

### ISSUE THREAD

**Issue by daltonrooney** [wearebraid/vue-formulate#350]
**Describe the bug**
Attempting to set a default value on a field with a `value` prop when that field also has a v-model, the v-model value is used.

**Reproduction**
https://codepen.io/dalton/pen/LYRdbNj

**Expected behavior**
[From the documentation ](https://vueformulate.com/guide/inputs/#initial-value-with-value-prop)
>When using v-model and value on the same <FormulateInput> the initial value will use the value over the v-model, updating the v-model to match.

**Comment by justin-schroeder** [comment]
Hmmmmmmmmmmmmmmmmmmmmmm yep...shouldn't do that.

**Comment by justin-schroeder** [comment]
Ok, this issue is now fixed in the `release/2.5.0` branch with a backing test. Thanks for the report 👍

**Comment by daltonrooney** [comment]
@justin-schroeder Thank you for the fix and the great software. 👍
