### ISSUE TITLE
Only the First FormulateInput Element is Displayed, nothing thereafter... really weird

### ISSUE THREAD

**Issue by cdcv** [wearebraid/vue-formulate#351]
Very strange behavior: after the first input, remaining html content vanishes into the ether.

Just discovered that the problem goes away and the forms work when not using self-closing tags (?!?!?).

I have copied example formulate forms, but they are not working correctly.  Anything following the first FormulateInput is not rendered for some reason. Therefore, if a form has more than one field, only the first one is rendered.  Even if plain text is entered into the template immediately after the first input, it somehow disappears and is not displayed, and does not show up if searched in the developer console, or looking through the DOM hierarchy.

In the example template below, basically copied directly from the example in the readme with some small changes, the <input field (placed as a test) displays and works correctly, the first <FormulateInput displays correctly, but everything below it is absent from the DOM.  If the preceding <FormulateInput is uncommented, then it displays and everything below that one is absent.

No idea where to even start in what could be causing this.

This is an app being built using:
parcel serve src/index.html
from package.json:
    "vue": "^2.6.12",
    "vue-template-compiler": "^2.6.12"
    "@braid/vue-formulate": "^2.4.5",

Example template:
<template name="AppGetUserInputs">
  <div class="container">
    <input v-model="value" placeholder="edit me">
    <p>Message is: {{ value }}</p>
    <FormulateForm
        v-model="values"
        @submit="handleLogin"
    >
      <h2>Login</h2>
      <br>
      Testr
      <br>

      <FormulateInput type="text" name="password" label="Password" validation="required" />
      <FormulateInput name="terms" type="checkbox" label="I accept, just don't make me read the terms." validation="accepted" />
      <FormulateInput type="submit" label="Login" />
      <pre>{{ values }}</pre>
    </FormulateForm>
  </div>
</template>

**Comment by justin-schroeder** [comment]
Guessing that you're not compiling single file components but rendering directly in the DOM. Vue has 2 code styles, one is for DOM templates, it is kebab case, non-self closing tags. The other is PascalCase and self closing tags (that's the recommended code style anyway, you can still use kebab here if you want).

Good luck 👍
