### ISSUE TITLE
"TypeError: Illegal Constructor" when removing a file from file input in Safari

### ISSUE THREAD

**Issue by hbalenda** [wearebraid/vue-formulate#352]
**Describe the bug**
Error thrown when removing an item from the file input while using Safari. It looks like this is coming from the use of the `DataTransfer` constructor in [FileUpload.js Line #182](https://github.com/wearebraid/vue-formulate/blob/master/src/FileUpload.js#L182), which isn't supported in Safari (see: https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/DataTransfer). 

**To Reproduce**
1. In Safari, go to https://vueformulate.com/#well-considered-file-inputs
2. Upload an image
3. Remove the image
4. See "Illegal Constructor" error

**Device information:**
 - OS: MacOS 10.15.7
 - Browser: Safari
 - Version: 14.0

**Comment by justin-schroeder** [comment]
Bleh. yeah, we should guard that constructor. If people aren't using Vue Formulate's way of uploading files we wont be able to modify the actual FileList in unsupported browsers so if they use native `FormData` it won't include the modified values. We can still offer the fancy add/remove features if they do uploads via XHR like we recommend in the docs.

Or, maybe we should just remove the DataTransfer logic all together and make it clear in the docs that we wont modify the original FileList. Open to suggestions on this. I'm currently working through file related issues for 2.5 so i'll tag this as something that needs attention. Thanks for the report.

**Comment by justin-schroeder** [comment]
@hbalenda ok, this issue is resolved in the `release/2.5.0` branch. The docs will include a big fat warning for users who are not using the recommended approach to uploading. Early 2.5 docs here:

https://vueformulatecom-git-release-250.braid.vercel.app/guide/inputs/types/file/
