### ISSUE TITLE
Clearing validation error on a specific FormulateInput field?

### ISSUE THREAD

**Issue by bizcmd** [wearebraid/vue-formulate#353]
I have a need to clear a specific text input field (with a 'required' validation) back to its initial empty state of blank and no error messages (having been previously filled with some text by the user, or used and then cleared by the user, resulting in a validation error marking).

The use case is that this field is shown only when a previous radio field selection is made, and the user can then enter text into it.  If he then chooses to answer the radio selection with an alternative option instead of his original selection, I clear the text field he previously entered, but this does not remove the validation error (rightly).  I need to remove the validation error too, so that it is back to its initial state of blank and no error message showing.  If he then subsequently enters and deletes something in the text field, it should show the error message.

I see there is a `$formulate.resetValidation()` function which clears the whole form of values and resets error message states, for all input fields.  I would like to be able to reset validation on a specific input.  I've looked into properties of the `registry` Map but haven't been successful in finding anything useful there.

Could someone please point me in the right direction?

Here is a small example: I select Eggs, the text field is shown, I enter some text.  I then change my mind by selecting Sausages which clears the value and hides the field.  I then decide I do want Eggs after all, and when I select Eggs the text field is shown again, but because the field has been previously used and cleared, the old validation message still shows:

https://user-images.githubusercontent.com/75837683/103689866-c8a16180-4f8b-11eb-80f8-c2605a085580.mov

**Comment by justin-schroeder** [comment]
@bizcmd it sounds to me like you're attempting to have the validation rule itself be reactive, which is a supported feature. Consider `v-bind`ing the `validation` prop itself.

```
<FormulateInput
  type="text"
  :validation="condition ? 'required' : 'optional'"
/>
```

Keep in mind that the visibility of an error message is not the same as the presence of the error message. So even if there was a way to hide the error message on that one input, the error would still be there and prevent form submission, so in the case changing the validation state itself seems better in my opinion.

**Comment by bizcmd** [comment]
Hi Justin,

Thanks so much for your reply.  Your idea of using the reactive validation prop is a good one, but what I actually need is to end up with the exact same "state" of the field as when it first shows: the validation is still required, but I don't want the validation message or styling to appear just yet.  When a form is first shown with a text field with a validation of 'required', the field is shown but the error message/styling is not shown until either (a) you focus the input and then blur away from it, or (b) you enter something and then delete the string so the field is empty again.  In either of those 2 cases, the error string of "Sauce is required" is shown (correctly).

For my case, I'd specifically like to revert the state of this field, programatically when I hide the field, to the state it was at first showing, that is: validation message/styling hidden but still "requiring" an input (so that the form cannot be submitted until this field is set).  I only wish the validation message and styling to appear in either case (a) or (b) like it normally would.

In other words, I'd like to do the equivalent of resetValidation on this specific field (not the whole form).  Is that possible to achieve?  That would then allow my text field to show again to the user, as if it had not been used at all yet.  Presently, as you can see from the example video above, the second time the field is shown it retains its validation message and styling from its first use.  I don't want that, so I need a way of clearing just this field but still "requiring" its input, from a validation perspective, and still retaining the ability to show the validation error message and styling when (a) or (b) takes place subsequently.

(I can't use `v-if` on the FormInput which might help achieve this by re-creating the component on show/hide, because I'm using animation to show/hide the field - for this I'm using v-show to retain the component in the DOM so that the animation can work.  Hence why I need a specific method to clear just this field.  Without animation it would be easier because the field could just be freshly instantiated each time on show, but that's not an option for me in this case, I think).

Many thanks.  Your library is a fantastic implementation and much needed!  Thank you.

**Comment by justin-schroeder** [comment]
@bizcmd ok, thanks I appreciate you strengthening the case for why you need the specific kind of behavior. The only way to achieve what you're wanting would be to use a `ref`.

```
<template>
<div>
  // ....
  <FormulateInput
    ref="yourSauce"
  />
  // ...
</div>
</template>

<script>
export default {
  methods: {
    resetSauceErrors () {
      this.$refs.yourSauce.behavioralErrorVisibility = false
    }
  }
}
</script>
```

This isnt really a "public api", but should do what you're looking to do 👍
