### ISSUE TITLE
Date Validation

### ISSUE THREAD

**Issue by ghost** [wearebraid/vue-formulate#354]
Hi. I'm still an intern and new to a lot of this stuff so I am not sure this correct way to ask my question.

I am using the Vue Formulate date input. I am also using "required" and "after" validation. 

Firstly, when using the after validation without a set date I noticed that the current day is invalid. Is there an easy way to validate the date to allow for the current day (i.e. after-1)? 

Secondly, I noticed that when entering an invalid date (e.g. 31 February), both my validation messages display ("Date is required" and "Date has to be after today"). So is there a way to choose what message is displayed when invalid date is entered?

Thanks in advance and sorry if this is not the correct way to go about this.

Thank you for this library! It is amazing!

**Comment by justin-schroeder** [comment]
Hi @NicCTI.

1. As for your first question, I would need some kind of example to know what was invalid about the current day. I'd recommend using the codepen or codesandbox template links on the [community page of the docs](https://vueformulate.com/guide/community/).
2. If you're concerned about both messages showing instead of only one, then I would suggest a bit further reading on the validation documentation, specifically in [stopping validation](https://vueformulate.com/guide/validation/#stopping-validation).

Again, by far, the best way to get help is to provide a "reproduction" of the issue you're having, that lets maintainers and other community members quickly identify if something is a bug, or give you helpful advice on how to resolve your roadblock. Keep at it 👍

**Comment by ghost** [comment]
Hi @justin-schroeder.

Thanks for getting back to me. Sorry I didn't word my question well. 

1. The problem I'm having with selecting the current day (when using "after"), is that that doesn't allow me to select today. In other words, when choosing today from the date picker, the validation kicks in and the form can't be submitted. 
Basically the user must only be able to choose dates from today (included) onwards.
I realise that I could go and get todays date in a function and then use that with "after" but I wondering if there is a better way of doing it.
  
  I will try reproducing what I mean in the codepen or codesandbox and share the link.

2. Sorry this was terribly worded. I know how to use only one validation message at a time. My problem is that when typing in a invalid date (for example 2021/02/31), the "required" validation message is being displayed. So I was wondering whether it is possible to choose the message that is displayed for a date that doesn't exist  (for example 31st of April).

Thanks again.

**Comment by ghost** [comment]
https://codesandbox.io/s/vue-formulate-reproduction-template-forked-kmpgq?fontsize=14&hidenavigation=1&theme=dark

I may have done this wrong.

**Comment by justin-schroeder** [comment]
@NicCTI

1. Yeah, we should change the default validation message to make it more clear, but the `after` rule is exclusive of the date. If I say, I'll give you your gifts `after` christmas, the assumption is sometime on the 26th of december or later. so the same logic holds here. if you want it to include today, youll need to give it yesterday's date. An argument could be made to change the default date to yesterday, but at this point that would be a breaking change so it probably wont happen, at least on the 2.x versions.
2. It looks like you got this working using `bail` properly 👍 Nice!

Hey! Intern or not, you've got good suggestions here and your code looks fine — be confident! You're kicking ass!

**Comment by ghost** [comment]
@justin-schroeder 

Yeah the logic makes complete sense with ```after```  and definitely holds. Was mainly just wondering if I had my logic right and that I heading down the right path.

Thanks again so much for getting back to me and for this library! 

Also thanks for saying that, always good to know that you're on the right path!
