### ISSUE TITLE
Model changes not reflected in form

### ISSUE THREAD

**Issue by timsayshey** [wearebraid/vue-formulate#355]
**Describe the bug**

Take a look at the Codepen below. You can see that when the form model is changed after Formulate has rendered the form, it doesn't reflect the change to the model. Please advise.

**CodePen:**

https://codepen.io/timsayshey/pen/poEKENp

**Expected behavior**
Expect the form to reflect changes to the model.

**Device information:**
 - Device: any

**Comment by justin-schroeder** [comment]
Hey 👋 

Your callback is using the `function` keyword which re-contexts lexical `this`. Swap that for an arrow function and you'll be good to go:

https://codepen.io/jpschroeder/pen/PoGabYJ

**Comment by timsayshey** [comment]
@justin-schroeder Ah, got it. Looks like my codepen example didn't reflect the actual issue. I was trying to condense it down for the sake of brevity. However my actual issue still persists. In my code I load in an empty schema and an empty model, then an axios call is triggered to retrieve the schema from the API. After the API call completes, the schema is set to the response, which loads in the form as expected. Then the model is populated from local storage, I can see the model looks correct in Vue Devtools, however the data is not reflected in the displayed form. Is there a way to refresh the VueFormulate form? How should I troubleshoot this? According to the docs what I'm doing should work.

**Comment by justin-schroeder** [comment]
What you're saying sounds like it should work, but there's really no way for me to help debug your particular use case without seeing the code. Obviously that is a well tested feature on this end so I imagine it's something to do with the way the data is being set in your form 🤷‍♂️

If you can reproduce is let me know and I'll take a look.
