### ISSUE TITLE
pass context to component

### ISSUE THREAD

**Issue by alsemyannikow** [wearebraid/vue-formulate#365]
I'm sorry for my bad english.
I am creating a new component box, for form layout.

```vue
<template>
    <div class="{{ class }}">
         <div class="text">{{ text }}</div>
         
        <div class="children">
             //how to display descendants correctly 
       </div>
    </div>
</template>

<script>
    export default {
        props: ['context'],
        mounted() {
            console.log(this.context); // undefined
        }
    }
</script>
```

And create plugin

```js
import FormulateBigFomBox from "./box.vue";

export default function (formulateInstance) {
    formulateInstance.extend({
        components: {
            FormulateBigFomBox
        },
        library: {
            formulateBigFormBox: {
                classification: "FormulateBigFomBox",
                component: "FormulateBigFomBox",
            }
        }
    })
}

```

and main component 

```vue
<template>
    <div class="container">
        test form
        <FormulateForm
            v-model="values"
            :schema="schema"
        />
    </div>
</template>

<script>

    export default {
        name: "itt",
        data(){
            return {
                values: {},
                schema: [
                    {
                        component : "h3",
                        children: "pizza",
                    },
                    {
                        component: "div",
                        class: "flex-wrapper",
                        children: [
                            {
                                component: "div",
                                children: [
                                   {
                                      type: "text",
                                      name: "test"
                                  }
                                ]
                            }
                        ]
                    },
                    {
                        component: "FormulateBigFomBox",
                        children: [{
                            type: "text",
                            name: "test"
                        }]
                    }
                ]
            }
        }
    }
</script>
```
the problem is that in my component `FormulateBigFomBox` , props `context` = `undefinde`.

i want to make my component work like HTML { component: "div", ... }, but with my layout

**Comment by justin-schroeder** [comment]
When using a schemas you only need to define the `component` property if the element being rendered is not a `FormulateInput`. All schema nodes are the component `FormulateInput` by default, so in your example you are directly mounting your component instead of using it as a `FormulateInput`. To use your custom input, just specify the props you would pass FormulateInput to use it (including the "type"):

```json
{
  type: 'formulateBigBoxFom'
}
```

**Comment by alsemyannikow** [comment]
> При использовании схем вам нужно определить `component`свойство только в том случае, если отображаемый элемент не является `FormulateInput`. Все узлы схемы являются компонентами `FormulateInput`по умолчанию, поэтому в вашем примере вы монтируете компонент напрямую, а не используете его как файл `FormulateInput`. Чтобы использовать свой собственный ввод, просто укажите реквизиты, которые вы должны передать FormulateInput, чтобы использовать его (включая «тип»):
> 
> ```json
> {
>    type : 'formulateBigBoxFom' 
> }
> ```

formulateBigBoxFom is not `FormulateInput`

```
<div class="box"> // component formulateBigBoxFom
    <div class="number">{{ number }}</div> // props formulateBigFomBox
    <div class="rows"> // 
        <div class="row"> // component formulateBigFomRow
            <div class="text>{{ text }}</div>  // props formulateBigFomRow
                <div class="items">
                    <div class="item">
                        <FormulateInput/>
                    </div>
                </div>
        </div>
     </div>
</div>
```
schema: [
  {
      component : "h3",
      children: "pizza",
  },
  {
      component: "FormulateBigFomBox",
      children: [
        {
             component: "FormulateBigFomRow"
             children: [
                 {
                      type: "text",
                      name: "test1"
                 }
             ]
        }
      ]
  },
  {
      component: "FormulateBigFomBox",
      children: [
        {
             component: "FormulateBigFomRow"
             children: [
                 {
                      type: "text",
                      name: "test2"
                 },
                 {
                      type: "text",
                      name: "test3"
                 }
             ]
        }
      ]
  }
]

**Comment by alsemyannikow** [comment]
> When using a schemas you only need to define the `component` property if the element being rendered is not a `FormulateInput`. All schema nodes are the component `FormulateInput` by default, so in your example you are directly mounting your component instead of using it as a `FormulateInput`. To use your custom input, just specify the props you would pass FormulateInput to use it (including the "type"):
> 
> ```json
> {
>   type: 'formulateBigBoxFom'
> }
> ```

formulateBigBoxForm is not `FormulateInput`

```html
<div class="box"> // component formulateBigBoxForm
    <div class="number">{{ number }}</div> // props formulateBigFormBox
    <div class="rows"> // children formulateBigBoxForm
        <div class="row"> // component formulateBigFomRow
            <div class="text>{{ text }}</div>  // props formulateBigFormRow
                <div class="items">// children formulateBigFomRow
                    <div class="item">
                        <FormulateInput/>
                    </div>
                </div>
        </div>
     </div>
</div>
```
```js
schema: [
  {
      component : "h3",
      children: "pizza",
  },
  {
      component: "FormulateBigFormBox",
      children: [
        {
             component: "FormulateBigFormRow",
             children: [
                 {
                      type: "text",
                      name: "test1"
                 }
             ]
        }
      ]
  },
  {
      component: "FormulateBigFormBox",
      children: [
        {
             component: "FormulateBigFormRow",
             children: [
                 {
                      type: "text",
                      name: "test2"
                 },
                 {
                      type: "text",
                      name: "test3"
                 }
             ]
        }
      ]
  }
]

```

**Comment by justin-schroeder** [comment]
I'm not sure if these are just typos, but you're declaring your component as a custom input here:

```js
formulateBigFormBox: {
                classification: "FormulateBigFomBox",
                component: "FormulateBigFomBox",
}
```

That declares `formulateBigFormBox` as a formulate input and uses the `FormulateBigFomBox` ("Fom?" typo?). You cannot receive a context object thout being a formulate input, the context object _is_ for inputs. If you're not trying to use a formulate input, then you can treat each node as it's own component declaration, these do not need to be formulate inputs, you can use anything you want. the `children` property render inside it just as you would with a normal slot. For example if I had a component named: `MyCustomComponentThatHasNothingToDoWithVueFormulate` I would declare it like this:

```vue
<template>
<div class="my-custom-component">
  <p>This is a custom component and here are the contents:</p>
  <slot />
</div>
</template>
```

Then I would register it with Vue:

```js
import Vue from 'vue'
import MyCustomComponentThatHasNothingToDoWithVueFormulate from 'MyCustomComponentThatHasNothingToDoWithVueFormulate.vue'

Vue.component(MyCustomComponentThatHasNothingToDoWithVueFormulate)
```

Then I would use it like this:

```vue
<template>
  <MyCustomComponentThatHasNothingToDoWithVueFormulate>
    <span>Hello world!</span>
  </MyCustomComponentThatHasNothingToDoWithVueFormulate>
</template>
```

That would render:

```html
<div class="my-custom-component">
  <p>This is a custom component and here are the contents:</p>
  <span>Hello world!</span>
</div>
```

If I wanted to use that component with Vue Formulate's schema. I would do everything the same, except use it like this:

```json
[
  {
    "component": "MyCustomComponentThatHasNothingToDoWithVueFormulate",
    "children": [
      {
        "component": "span",
        "children": "Some Text"
      }
    ]
  }
]
```

That is the exact same. The `context` object is part of `FormulateInput` elements. So not sure if it's the language barrier but some wires seem crossed here about what a schema does vs what inputs do. Hopefully this helps clear it up.

Since there is no feature request here, im going to close this issue. Best of luck 👍

**Comment by alsemyannikow** [comment]
Yes, thanks, this is what I needed, I think it is worth making a small block in the documentation on this matter with examples. It may seem logical to VUE pros, but for beginners like me it was difficult to understand.

**Comment by justin-schroeder** [comment]
@alsemyannikow feel free to submit a PR to the docs with a suggested addition.
