### ISSUE TITLE
Add an option to disable certain select options

### ISSUE THREAD

**Issue by rabih9780** [wearebraid/vue-formulate#366]
**Describe the new feature you'd like**

I Looked through the documentation but couldn't find a way to disable certain select options.

One way to implement this is by adding "disabled" tag in the object 
{ value: 'initial', label: 'Middle Initial',  id: 'name-initial',  **disabled: true** }

**Comment by Esgaroth77** [comment]
I'd like that feature. I have various fields in my forms that only need to be filled (and therefore visible) if certain inputs have been made before (i.e. I don't need a VAT-number if it's a private customer).

**Comment by XGhozt** [comment]
+1

**Comment by justin-schroeder** [comment]
Seems pretty doable. FWIW, this already works like this for `box` type inputs. I'll tag for future release.

**Comment by justin-schroeder** [comment]
This is now added in the `release/2.5.1` branch 👍. Also, technically you could do this already using the `attributes` property which is `v-bind` on each option. However, 2.5.1 will add a `disabled: Boolean` property to the option list.
