### ISSUE TITLE
Subtype for custom input

### ISSUE THREAD

**Issue by nordentwickler** [wearebraid/vue-formulate#368]
Hello,

lets say we have a custom input via:

```
customRadioGroup: {
  classification: "customRadioGroup",
  component: "FormulateInputCustomRadiogroup",
  slotProps: {}
}
```

and we use the FormulateGroup.vue for our FormulateInputCustomRadiogroup.vue. No we could use the schema 

```
{
  type: "customRadioGroup",
  label: "Custom Group Label",
  name: "custom_radio_group",
  options: {
    "recently": "Seit kurzer Zeit",
    "6-12-mont": "6 - 12 Monate",
    "1-3-years": "1 - 3 Jahre",
    "3-5-years": "3 - 5 Jahre"
  },
}
```

for outputting a custom radio group. But there is one problem, we haven't the subtype for the options, so they think, they are from type customRadioGroup. There schould be a possibility to define the subtype for children / options in the library declaration. Like so:

```
customRadioGroup: {
  classification: "customRadioGroup",
  component: "FormulateInputCustomRadiogroup",
  subType: "radio",
  slotProps: {}
}
```

Am i missunderstanding something or isn't this possible right now?

**Comment by justin-schroeder** [comment]
Would you mind providing the code of `customRadioGroup`, or even better a reproduction on codesandbox?

**Comment by nordentwickler** [comment]
We thought, if we copy the FormulateGroup.vue file and change the name, it should output at least the normal group output. So we haven't changed anything special on the markup of the original FormulateGroup.vue file. But we realized, that we need the subtyp, so the Inputs are rendered as a radio and therefore, it would be great to use the normal notation for defining a custom input.

In fact, our main goal is to make radio group with all the nice thinks vue formulate offers but as a template with predefined option values. Maybe you now a better way to do this?

We are using vue formulate pretty heavily on a health web app and need to write like 100 schemas for this in 7 languages. If we are able to write this with predefined options

```
{
  "type": "occurrence",
  "label": "Seit wann?",
  "name": "step.1.symptom.{{symptom.id}}.occurrence",
  "validation": "required",
  "visible": "step.1.symptom.{{symptom.id}}.presence:yes",
 },
```
instead of this:

```
{
  "type": "radio",
  "label": "Seit Wann",
  "name": "step.1.symptom.{{symptom.id}}.occurrence",
  "validation": "required",
  "visible": "step.1.symptom.pressence:yes",
  "options": {
    "recently": "Seit kurzer Zeit",
    "6-12-month": "6 - 12 Monate",
    "1-3-years": "1 - 3 Jahre",
    "3-5-years": "3 - 5 Jahre"
  }
},
```

makes a big difference and helps us to have less typo errors :D So our first approach was defining a custom input with default options.

**Comment by justin-schroeder** [comment]
@nordentwickler since you're using a custom input I would recommend using `slotProps` to allow the collection of any additional information you need, like a `subType`.

https://vueformulate.com/guide/inputs/slots/#declaring-slot-props

That's probably the best we can do though since the library cannot solve for every possible edge case, but we do want to provide developers with the tools necessary to build virtually anything with custom inputs.
