### ISSUE TITLE
Validation errors with empty value even if the input is not required

### ISSUE THREAD

**Issue by bacc91** [wearebraid/vue-formulate#370]
Some validation rules throw the error with an empty value even if the input is not required. It happened to me on "alphanumeric" and "matches". 
The docs states instead: "[...] all validation rules will pass with an empty value unless they include the required rule"

CodePen: https://codepen.io/bacc/pen/XWNWMdj

Expected behaviour: any validation rule passes with empty value, if not required.

Version: 2.5.0
 
PS: thanks for this great library!

**Comment by justin-schroeder** [comment]
If the field is optional, use the `optional` rule and you'll be good to go. 👍
