### ISSUE TITLE
File: set new value after initialization

### ISSUE THREAD

**Issue by maksabuzyarov** [wearebraid/vue-formulate#371]
Hey! Help please, how can I update the value of the file field after initialization?

I tried:
1. ```v-model```
2. ```:value```
3. ```form.setValues```
4. ```form.setFieldValue```

The value was updated only by re-creating the field element itself (v-if)

```vue
<template>
  <FormulateInput
    v-if="fieldMounted"
    name="file"
    type="image"
    :value="file"             
  />
</template>

<script>
export default {
  data() {
    fieldMounted: true,
  },

 //  ...

  methods: {
    afterUpdate() {
      this.fieldMounted = false;
      this.$nextTick(() => { this.fieldMounted = true });
    }
  }
}
  
</script>
```

## Codepen with my attempts

The value will update after 3 seconds

https://codepen.io/maksabuzyarov/pen/gOLOxJN

**Comment by justin-schroeder** [comment]
@maksabuzyarov admitedly the DX on this could be a bit better, but once initialized, the value of a `file` input is [an instance of `FileUpload`](https://github.com/wearebraid/vue-formulate/blob/master/src/FileUpload.js). So you can do this:

https://codepen.io/justin-schroeder/pen/XWNKjwO
