### ISSUE TITLE
File: Type Error when using "Add image" with a predefined value

### ISSUE THREAD

**Issue by maksabuzyarov** [wearebraid/vue-formulate#372]
**To Reproduce**
1. Go to [https://codepen.io/maksabuzyarov/pen/gOLbOox](https://codepen.io/maksabuzyarov/pen/gOLbOox)
2. Click on '+ Add image'
3. Select file and press 'Ok'
4. See error in the console

### CodePen:

https://codepen.io/maksabuzyarov/pen/gOLbOox

![image](https://user-images.githubusercontent.com/20745248/106364604-fa011900-630e-11eb-9634-d0ad4940cfc5.png)

![image](https://user-images.githubusercontent.com/20745248/106364616-05544480-630f-11eb-80d1-9412d9150246.png)

**Comment by justin-schroeder** [comment]
Interesting. Thanks for the report. Ironically, it doesn't happen on browsers that dont support the `DataTransfer` constructor because we have a backdoor for them. grrr. ok. tagging.

**Comment by justin-schroeder** [comment]
This is fixed in the `release/2.5.1` branch 👍
