### ISSUE TITLE
Chrome: file input with "multiple" and initial "value" causes DataTransferItemList error when adding more files

### ISSUE THREAD

**Issue by bizcmd** [wearebraid/vue-formulate#373]
**Describe the bug**
A FormulateInput of type `file` and property `multiple` with an initial `value` set holding a length 1 array will generate an error in Chrome when adding another file to the list via the Add File button:

```
Failed to execute 'add' on 'DataTransferItemList': parameter 1 is not of type 'File'."

found in

---> <FormulateFiles>
       <FormulateInputFile>
         <FormulateInput>
           <FormulateForm>
             <Root>
```

In Safari, it works without error.

**To Reproduce**
Use CodePen below and click to add a new file.  Chrome will immediately add it to the list visually (without the normal faux loader animations) and will produce console error as above.
### CodePen:
https://codepen.io/flyfoxuk/pen/QWGwggm

**Expected behavior**
The selected file to be added without error to the file list.

**Device information:**
 - Mac
 - OS: 10.15.5
 - Browser [Chrome 88.0.4324.96]

**Further info**
Seems to be related to `mergeFileList` function in FileUpload.js  ??

**Comment by zgurea1** [comment]
same issue.
