### ISSUE TITLE
Custom Slot with FormulateForm

### ISSUE THREAD

**Issue by vicenterusso** [wearebraid/vue-formulate#375]
Can I have and example to use custom inputs with FormulateForm and JSON schema?

Or even better, a way to extend builtin components template. For example, add error classes to input

**Comment by justin-schroeder** [comment]
Glad you're experimenting with Vue Formulate! Both of these are very doable, but let me kindly ask you redirect how to questions away from GitHub. The community page on the docs has suggestions for other places to pose open ended questions. Thanks 🙏😊

If you're asking to improve the docs, you can submit a PR to that repo directly 👍
