### ISSUE TITLE
Datetime and Select PLUGINS

### ISSUE THREAD

**Issue by EO2875** [wearebraid/vue-formulate#377]
I was looking for Formulate plugins but I couldn't find many, so I wrote two very small and simple plugins myself:
[vue-formulate-select](https://www.npmjs.com/package/@cone2875/vue-formulate-select) and [vue-formulate-datetime](https://www.npmjs.com/package/@cone2875/vue-formulate-datetime), which are wrappers for the [vue-select](https://vue-select.org/) and [vue-datetime](https://github.com/mariomka/vue-datetime) packages respectively. I've tested them to work for my needs, but they're still on the beta stage. 

I see that you have a Plugins project, and I would like to add mine in there (or wherever we're gonna place plugins).

**Comment by justin-schroeder** [comment]
Awesome! We'd be happy to add these to the docs page 👍

**Comment by CalvinWalzel** [comment]
@EO2875 Thanks a lot for those plugins, they look great! Are you planning to also put a repository online?

**Comment by EO2875** [comment]
Here's my repos:

- https://github.com/EO2875/vue-formulate-select
- https://github.com/EO2875/vue-formulate-datetime

**Comment by justin-schroeder** [comment]
These are now linked from the plugins docs. Thanks!
