### ISSUE TITLE
When using label slot, the original label tag is still rendered

### ISSUE THREAD

**Issue by LukasHirt** [wearebraid/vue-formulate#378]
**Describe the bug**
If a `FormulateInput` is used with the scoped slot for label, the original label tag is still rendered next to the input.

**To Reproduce**
1. Create checkbox input:
```vue
<FormulateInput
  name="terms"
  type="checkbox"
>
  <template v-slot:label="{ id }">
    <label :for="id">
      Accept
      <router-link
        to="terms-and-conditions"
        v-text="'terms and conditions'"
      />
    </label>
  <template>
</FormulateInput>
```

**Expected behavior**
I would expect that the original label is gone. Instead I end up with two labels, one empty and one with the content from the slot.

**Screenshots**
![image](https://user-images.githubusercontent.com/25989331/107123700-43b5aa80-689f-11eb-988c-ac43014d1697.png)

**Device information:**
 - Device: MacBook
 - OS: MacOS Big Sur
 - Browser: Chrome
 - Version: 88

**Comment by justin-schroeder** [comment]
This is actually working as intended. Your slot is replacing the label, but checkboxes have 2 labels, one as a label and one as an input decorator. More details here:

https://vueformulate.com/guide/inputs/types/box/#styling-box-inputs

(You can disable the second one too if you want, but it's generally needed for custom checkbox styling)
