### ISSUE TITLE
Vue-formulate error translations require a page refresh to detect language changed.

### ISSUE THREAD

**Issue by Evaldas-B** [wearebraid/vue-formulate#379]
Not like other translations, Vue-formulate error translations require a page refresh to switch to a different language.

Using [nuxt-i18n](https://github.com/nuxt-community/i18n-module)

**Reproduction**
Created a tiny repo that reproduces  the error
https://github.com/Evaldas-B/vue-formulate-i18n

**Expected behavior**
The validation errors should be translated after the language is switched and should not require a page refresh

How should I explicitly set the new language so that vue-formulate immediately picks up the change?

**Comment by justin-schroeder** [comment]
@Evaldas-B if your inputs are inside a FormulateForm and you call `$fomulate.setLocale('lt')` they should automatically update. Unfortunately, that's the only way to automatically have the language swap on error messages.

I'd be open to PRs though 👍
