### ISSUE TITLE
Programmatic save enhancements

### ISSUE THREAD

**Issue by TrendyTim** [wearebraid/vue-formulate#380]
Is there a reason programmatic submit shouldn't return the promise from formSubmitted method

I am implementing a paging system, spoon feeding the schema and values objects based on the page number, and thats all fine but i need to submit before navigate and the programmatic save doesn't return a promise so i cant (in a nice way) know when its saved as a result of a page navigation then complete when thats done (best i can think of would be to set `this.actionOnSaveComplete = "back"` and then test that in the save handler, which gives me the heebie-jeebies .

I modified the min.js (added the return where it would be if added to)
https://github.com/wearebraid/vue-formulate/blob/94520091c36889a925fdc3bdd1f850f82ac39689/src/Formulate.js#L406

and it all seems to work ok (although doesn't return the values in the promise), but I only have windows dev environment and am unable to figure out how to get vue-formulate to build in order to make the change and build/test.

Similarly, I was wondering if instead of having to rely on the programmatic submit() method and event, what if there was a method that just did most of the same work and just returned the data instead of raising the events, with an optional validate param (so we can save a draft for example, as im resorting to the model data for that which you recommended against), once again, it looks relatively easy to do but i wouldn't be able to build/test in order to submit a PR.

**Comment by justin-schroeder** [comment]
Seems like a reasonable idea @TrendyTim. I'd definitely look at a PR for this functionality.

**Comment by TrendyTim** [comment]
Thanks @justin-schroeder, love the work you're doing with this.

**Comment by TrendyTim** [comment]
I figured i can just invoke the instance directly, but i submitted a PR anyway might help someone and its only a return

**Comment by TrendyTim** [comment]
I figured i can just invoke the instance directly, but i submitted a PR anyway might help someone
