### ISSUE TITLE
Regex for 'D' date validation is incorrect.

### ISSUE THREAD

**Issue by rbackert** [wearebraid/vue-formulate#381]
**Describe the bug**
The regular expression for date format 'D' for the date validation rule incorrectly marks days equal to 10 or 20 as invalid.

**To Reproduce**
1. Go to below codepen.
2. The 10 or 20 in the date field.
3. Click submit.

### CodePen:
https://codepen.io/racabac/pen/wvogavM

**Comment by justin-schroeder** [comment]
Thanks for the bug report, this is fixed in the `release/2.5.1` branch 👍
