### ISSUE TITLE
"Cannot read property 'en' of undefined" when loading from CDN

### ISSUE THREAD

**Issue by paulrosen** [wearebraid/vue-formulate#382]
I'm trying to use Formulate using a traditional html file.

This is my entire page:
```
<html lang="en">
<head>
<meta charset="utf-8">
<title>Formulate demo</title>
<script src="https://unpkg.com/vue"></script>
<script src="https://cdn.jsdelivr.net/npm/@braid/vue-formulate@2.5.0/dist/formulate.umd.min.js"></script>
</head>
<body>
</body>
</html>
```

This is printed in the browser's console:
```
formulate.umd.js:1 Uncaught TypeError: Cannot read property 'en' of undefined
    at new le (formulate.umd.js:1)
    at formulate.umd.js:1
    at formulate.umd.js:1
    at formulate.umd.js:1
```

I'm sure I'm initializing the page wrong but I couldn't find a complete example, so this might just be documentation bug.

**Comment by paulrosen** [comment]
I'm guessing it has something to do with this line in Formulate.js:
```
import { en } from '@braid/vue-formulate-i18n'
```
That is what is undefined.

**Comment by justin-schroeder** [comment]
Hey paul, I'd suggest using the min instead of the UMD, should be good to go with that

**Comment by paulrosen** [comment]
Ok.

One other thing is I see it breaks between version 2.1.1 and 2.2.0.

I'll try the min.

**Comment by paulrosen** [comment]
Yes, using the min version works.
