### ISSUE TITLE
Can't use directive in schema generated forms.

### ISSUE THREAD

**Issue by sugoidesune** [wearebraid/vue-formulate#392]
**Describe the bug**
I wanted to use v-mask for an input but it doesn't work when using schema generated forms.

**To Reproduce**
1. Install directive like https://www.npmjs.com/package/v-mask
2.    Add Schema     
```js
{
          name: 'Card Number',
          text: 'Card Number',
          'v-mask': "'####-##-##'",
        }
```
3. Type '12345678'
4. The Input is not formatted according to the directive.

**Reproduction**
The only way it works through schema is setting directive on `<FormulateForm>` but that only formats the first input. But setting it through the schema does nothing:
https://codepen.io/timar/pen/eYBxvJg

**Expected behavior**
Being able to set custom directives through schema

**Device information:**
 - OS: Windows
 - Browser chrome

**Comment by justin-schroeder** [comment]
Unfortunately, masking is not supported. You would need to write a custom one, but it's in the docket for version 3. See #67
