### ISSUE TITLE
VueFormulate Issue two FormulateForm in a same page

### ISSUE THREAD

**Issue by InfoSysRodener** [wearebraid/vue-formulate#393]
I have two vueformulate on a single page. when I tried to submit a sign-in form. the validation in other form is triggered.

`
        <div v-if="isSignin" class="mt-10">
          <FormulateForm
            name="signin"
            @submit="atSignIn"
          >
            
           
          
            <hr class="mt-10 mb-5 mx-10 p-2 border-gray-500" />

            <FormulateInput 
                label="Email " 
                name="email"
                type="email" 
                validation="^email"
            />
            <FormulateInput 
                label="Password" 
                name="password"
                type="password" 
            />
            <p class="text-gray-700 cursor-pointer text-sm hover:text-blue-900">Forgot Password ?</p>
            <FormulateInput 
              type="submit"
              label="Sign In"
            />
          
            
          </FormulateForm>
        </div>
       
        <div v-else class="mt-10">
          <FormulateForm
            name="signup"
            @submit="atSignUp"
            #default="{ isLoading }"
          >
            <FormulateInput
              type="group"
              name="signup"
            >
              <FormulateInput 
                  label="Email" 
                  name="email" 
                  type="email" 
                  validation="^required|email"
                  error-behavior="submit"
              />
              <FormulateInput 
                  label="Password" 
                  name="password"
                  type="password" 
                  validation="^required|min:5,length|matches:/[0-9]/"
                  :validation-messages="{
                    matches: 'Password must contain at least number.'
                  }"
                  error-behavior="submit"
              />
              <FormulateInput 
                  label="Confirm Password" 
                  name="password_confirm"
                  type="password"
                  help="Just re-type what you entered above"
                  validation="^required|confirm"
                  validation-name="Password confirmation"
                  error-behavior="submit"
              />
              <FormulateInput 
                  type="submit"
                  :disabled="isLoading"
                  :label="isLoading ? 'Loading...' : 'Create Account'"
              />
           
              <a class="pt-10 text-sm font-sans text-gray-900">
                Already have an account? <span class="text-blue-700 cursor-pointer"  @click="isSignin = true">  Sign in </span>
              </a>
           </FormulateInput>  
          </FormulateForm>
        </div>  `

also when I toggle the two forms the value of formulate input group is feed to my login value.

![image](https://user-images.githubusercontent.com/40452878/111078547-ff1dce80-8530-11eb-99b8-cf43672e55c6.png)

**Comment by justin-schroeder** [comment]
That doesn't sound right, we often use multiple forms on the same page. Can you please try to recreate this on a codepen or codesandbox? Happy to look at that 👍

**Comment by InfoSysRodener** [comment]
Hello sir. I recreate my problem to a code sandbox. 
there is it [https://codesandbox.io/s/sweet-clarke-ojc7v?file=/src/App.vue](url)
I don't know why. When I submit the sign-in form. the validation in the sign-up form is triggered. 
also why the data in a group feed the other form.

Thank you

**Comment by justin-schroeder** [comment]
@InfoSysRodener this is actually a Vue "issue", often in Vue if your wrapper elements on a `v-if` are the same it will re-use the DOM elements and just swap out the expressions being executed for them which can lead to issues like what you observed, basically Vue didn't see 2 `FormulateForm`, it only "saw" 1 with props changed. In order to tell vue, "nah, these really are different" you can just apply a `key`. I've done that on a fork of your example:

https://codesandbox.io/s/elastic-lamarr-88zum?file=/src/App.vue
