### ISSUE TITLE
Add image does not work on Nuxt 2.15.2

### ISSUE THREAD

**Issue by dwfee** [wearebraid/vue-formulate#396]
with my image upload everything works fine. But the add image button just does nothing.
Any ideas? Without it it is not usable for me.
                         <FormulateInput
                           name="images"
                            label="test"
                           :value="files"  
                           type="image"
                           add-label="+ Bilder dazu"
                           multiple
                            @file-removed="fileRemoved"
                            @file-upload-error="fileUploadErrror"
                            @file-upload-complete="uploadComplete"  
                            />

**Comment by justin-schroeder** [comment]
Can you please provide a reproduction on codepen or codesandbox?

**Comment by dwfee** [comment]
trying. I never did this before I must admit.

**Comment by dwfee** [comment]
I fixed the issue by disabling:
 &[data-has-files] {
        padding: 0;

        input {
          // display: none;
        }
      }
it seems that my tailwind interferred.
