### ISSUE TITLE
Passing classes in createElement does not work

### ISSUE THREAD

**Issue by jaulz** [wearebraid/vue-formulate#399]
**Describe the bug**
Passing a class via props in `createElement` does not work and the class is not added to the element.

**Reproduction**
Check the CodePen below. There are two buttons rendered. The first one is a wrapper in `FormButton` which creates `formulate-input` via `createElement`:
![image](https://user-images.githubusercontent.com/5358638/111779093-fa04aa80-88b5-11eb-989a-36fb3ebf6424.png)

which incorrectly turns into:
![image](https://user-images.githubusercontent.com/5358638/111779156-0d177a80-88b6-11eb-8ac1-08d81eaff933.png)

The second is rendered like this:
![image](https://user-images.githubusercontent.com/5358638/111778866-a2663f00-88b5-11eb-80ec-a3c2c5b17ef7.png)

which (correctly) turns into:

![image](https://user-images.githubusercontent.com/5358638/111778839-97abaa00-88b5-11eb-9fb2-f477c3373716.png)

### CodePen:
CodePen is perfect for simple reproductions. Vue Formulate is already loaded and ready to use:

https://codesandbox.io/s/tailwind-vue-formulate-2-password-reset-styled-forked-ux9x2?file=/src/components/FormButton.vue

**Expected behavior**
Rendered `formulate-input`s should respect the `input-class` (and similar classes).

**Device information:**
 - Device: [e.g. iPhone6, 1997 Dell] MBP15
 - OS: [e.g. iOS8.1] macOS
 - Browser: [e.g. stock browser, safari] Chrome
 - Version: [e.g. 22]

**Comment by justin-schroeder** [comment]
@jaulz if you're using render functions you the `*-class` data should be passed via attributes:

```js
attrs: {
  inputClass: 'my-pizza-class'
}
```

Thanks!

**Comment by jaulz** [comment]
@justin-schroeder thanks a lot for the quick help! 😊
