### ISSUE TITLE
Have FormulateForm only show errors on submit

### ISSUE THREAD

**Issue by Ivan-Velickovic** [wearebraid/vue-formulate#4]
Currently FormulateForm will show errors on the blur event as well as on submitting the form with errors. I was wondering if it would be/is possible to set error-behavior such that errors are only shown when submitting a FormulateForm.

**Comment by justin-schroeder** [comment]
Great question. Currently there isn’t a way to do this, but I agree there should be. Ideally a way to set it per-field or for all sub fields of a form too. I’ll see if I can get to this over the weekend.

Thanks!

**Comment by Ivan-Velickovic** [comment]
Thank you. I was wondering if the documentation was also a repository?

**Comment by justin-schroeder** [comment]
It sure is, PRs welcome.

In fact at the bottom of every documentation page there is a “help improve this page” link that takes you to the repository file for that specific page.

Repo is here: https://github.com/wearebraid/vueformulate.com
