### ISSUE TITLE
'date' validator fails validation on valid 'date' fields

### ISSUE THREAD

**Issue by barry-mckay** [wearebraid/vue-formulate#417]
**To Reproduce**
1. Go to [CodeSandbox](https://codesandbox.io/s/vue-formulate-reproduction-template-forked-v335r?file=/src/components/Reproduction.vue)
2. Enter a valid date in the input
3. Trigger validation by blurring input
4. Observe the validation error

### CodeSandbox
https://codesandbox.io/s/vue-formulate-reproduction-template-forked-v335r?file=/src/components/Reproduction.vue

**Expected behavior**
I'd expect the validation to pass with a valid date. It might seem a bit redundant to use the 'date' validator on `input[type="date"]`. The reason for this is that Safari/IE don't natively support this input type and will fallback to `input[type="text"]`. In these scenarios the validation works fine (matches the example in your [documentation](https://vueformulate.com/guide/validation/#date)), but it'll cause the aforementioned issue in other browsers.

**Comment by justin-schroeder** [comment]
This can be confusing, but vue formulate uses the [HTML spec date input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date) which _always_ outputs the format as `YYYY-MM-DD` even though the input is shown in the localized format of the user's browser. So for a date format, specifying `MM/DD/YYYY` will always produce an error.

I agree it is a bit confusing, although this is mostly an HTML spec issue, but still happy to accept a PR for the docs on this.

Thanks! 👍
