### ISSUE TITLE
Nuxt.js delayed file upload (with error) cause redirect to error page 

### ISSUE THREAD

**Issue by vitaliy-sk** [wearebraid/vue-formulate#420]
**Describe the bug**
Nuxt.js delayed file upload (with error) cause redirect to error page 

**To Reproduce**
1. Configure nuxt project (https://vueformulate.com/guide/installation/#nuxt). 
2. Use Axios uploader (as URL you can use some dummy host)
3. Create a form with delayed file upload input
4. See nuxt error layout

At the same time live upload working as expected

**Reproduction**
https://codesandbox.io/s/stupefied-sun-d3udt?file=/pages/index.vue

**Expected behavior**
Error is rendering on the form

**Comment by justin-schroeder** [comment]
Hey @vitaliy-sk looking at your example the axios upload is not actually pointing to a valid upload route. This is throwing an exception which looks like it's making its way all the way up.

**Comment by vitaliy-sk** [comment]
@justin-schroeder exactly, but it's throwing an unhandled exception.
At the same time if I'm using not delayed upload it showing an error on the form, so the behavior is not consistent here. 

[https://i.ibb.co/qYfT25H/Screenshot-2021-04-29-at-16-46-34.png](url)
