### ISSUE TITLE
Required validation and custom validation issue when value/model is boolean

### ISSUE THREAD

**Issue by minasvisual** [wearebraid/vue-formulate#422]
**Describe the bug**
I created a custom input box that set Boolean to model context, works fine. When i add 'required' to validation, when "false" it does not recognize it as a valid field.
So, i tried to create a custom validation called "notNull" that compares (value === true || value === false), but the value of "value" never comes "false", only "" (empty string), when true, works.

**To Reproduce**
1. Set an input value as boolean
2. Add validation="required"
3. See validation behavior

And
1. Set an input value as boolean
2. Add custom validation
3. See validation behavior

Reproduction
https://codepen.io/minasvisual/pen/XWpwJje

**Expected behavior**
I expect validate if the field is a boolean (not null or not undefined) but value isnt the same as model.

**Device information:**
 - OS: Windows 10, 
 - Browser Google Chrome 
 - Version 90
 - Framework: Quasar

**Comment by justin-schroeder** [comment]
Unfortunately, HTML does not support boolean values, it only supports string values. Vue tries to patch these inconsistencies on the fly, but results are very unpredictable when using boolean values. You'll want to change your logic to use string values and then you should be good to go.
