### ISSUE TITLE
Multi Select Improvement

### ISSUE THREAD

**Issue by realnot** [wearebraid/vue-formulate#428]
Hi, what do you think of improving multi select with search input when you have thousands of choices and paginated results for example? Usually on data driven applications you have to deals with a lot tables and lot of FK, I spend my days in building grid / filtering / optimizing queries and having a select with an input search would be a great feature. Try to think for example when the user have to select a "city" without having "province" or "country". What do you do? Load 10/20 K records?

Example :

![Screenshot from 2021-05-13 09-07-54](https://user-images.githubusercontent.com/2405675/118091594-4a3a4d80-b3cb-11eb-88e4-f62093136594.png)

![Screenshot from 2021-05-13 09-08-19](https://user-images.githubusercontent.com/2405675/118091645-59b99680-b3cb-11eb-9570-3da0d27504f1.png)

Another improved would be allowing the user to change the template of options, for example concatenating object attributes or adding custom stuff, like here where you see the profile picture:

Example:

![Screenshot from 2021-05-13 09-08-40](https://user-images.githubusercontent.com/2405675/118091863-a1402280-b3cb-11eb-8363-6dc333ef4170.png)

The last one is not so important like input search, but could be an improvement.

**Comment by justin-schroeder** [comment]
Vue formulate makes it easy to write custom inputs and plugins. The core library is intended to cover all "native" inputs, but not "synthetic" inputs like this. However, you can pretty easily write your own, or wrap an existing option. You might checkout the plugins page, I believe someone already wrapped vue-select:

https://vueformulate.com/guide/plugins/
