### ISSUE TITLE
Improve / add input mask 

### ISSUE THREAD

**Issue by realnot** [wearebraid/vue-formulate#429]
Hi, on data driven applications (when you have a lot of forms) users move on input using tab to do data entry. There are some input  that could help the user when inserting data, providing a mask for that inputs.

Example:

![Screenshot from 2021-05-13 09-21-18](https://user-images.githubusercontent.com/2405675/118092719-bf5a5280-b3cc-11eb-976c-40e43b797cd9.png)

The [plugin]( https://igorescobar.github.io/jQuery-Mask-Plugin/) is don in jQuery, but maybe there's some wrapper for VueJS or an implementation or could be a suggestion to write it from scratch for vue formulate.

**Comment by justin-schroeder** [comment]
Yeah, it's on the roadmap! Masking is being tackled in the 3.0 version to allow for custom plugins to extend masking support. Closing this one in favor of https://github.com/wearebraid/vue-formulate/issues/67

Thanks 👍
