### ISSUE TITLE
t.split is not a function

### ISSUE THREAD

**Issue by datrinh** [wearebraid/vue-formulate#44]
**Describe the bug**
Whenever I try to add validation to an input, I get an error

**To Reproduce**
1. Add simple example to my code
```
<FormulateInput
              type="email"
              name="email"
              label="What is your email address"
              help="Where should we contact you?"
              validation="required|email"
            />
```
2. See Error `Uncaught (in promise) TypeError: t.split is not a function`

I'm running VueJS 2 with Typescript and Webpack using Single Files.

**Expected behavior**
Simple working example.

**Screenshots**
![image](https://user-images.githubusercontent.com/3518618/77175191-79ed0e80-6ac2-11ea-87ac-6f76b9a4331e.png)

**Device information:**
 - OS: Mac OS
 - Browser Chrome

**Comment by justin-schroeder** [comment]
@datrinh currently Vue Formulate does not support typescript (#36), but I'm looking for someone to help add it. If you could create a replicated repository for me to checkout or a codepen it would be helpful.

**Comment by justin-schroeder** [comment]
Closing in favor of #36

**Comment by datrinh** [comment]
This isn't about typescript. I just import it and call `Vue.use()` as per Getting Started. The displayed error is a runtime error in the browser console.

**Comment by justin-schroeder** [comment]
@datrinh ok, I'll re-open the issue then. I think this has something to do with the build environment you're in (and I suspect TS has something to do with it), but as im unable to duplicate the issue I cannot confirm. Could you share a repo or codepen with a reproduction? I'm able to get it working right away with vue-cli, nuxt, laravel mix, and from a cdn.

**Comment by justin-schroeder** [comment]
Closing this until there is some kind of reproduction, let me know if you're able to get one shared and i'll take a look.

**Comment by datrinh** [comment]
**Update:**
I fixed this with:
```
Vue.use(VueFormulate, {
  locale: 'en',
});
```
Apparently vue-i18n and vuex-i18n had some collision. Leaving this solution here in case someone struggles with something similar.
