### ISSUE TITLE
HTML in lable

### ISSUE THREAD

**Issue by keedle** [wearebraid/vue-formulate#442]
How can I make linked text in checkbox label ? 

    component: 'div',
    class: '',
    children: [
      {
        type: 'checkbox',
        label:
          'I consent to business storing my contact information and using it to contact me in the future. I\'ve read the <a href="https://www.seriousbusiness.com/risk-statement#privacy" rel="nofollow">Privacy Policy</a> and agree to the terms and conditions.',
      },
      {
        type: 'submit',
        class: '',
        label: 'Subscribe to pizza',
      },
    ],
  },

**Comment by justin-schroeder** [comment]
@keedle use a slot or a slot component to change the label to use `v-html`. This is not the default for security reasons. Best of luck 👍

Here's an example that is pretty close to what you want to do: https://codesandbox.io/s/vue-formulate-image-checkboxes-example-clbwf?file=/src/components/Reproduction.vue
