### ISSUE TITLE
generated forms field repeatable group props do not render

### ISSUE THREAD

**Issue by jerryfan** [wearebraid/vue-formulate#443]
**To Reproduce**
1. Go to 'https://vueformulate.com/guide/forms/generating-forms/#schemas'
2. Select 'Field group' under 'Interactive Playground'
3. Type '"remove-label: "remove", "remove-position": "after"'
4. Nothing changes

**Expected behavior**
Expected props to come through the UI.

**Screenshots**
![vue-formulate-generating-forms-repeatable-group-props-not-working](https://user-images.githubusercontent.com/2540814/122006515-7d686600-cde9-11eb-9d0a-7b05cbecc10b.png)

**Comment by justin-schroeder** [comment]
@jerryfan The `remove-label` is not shown in the snow theme, it's only there for accessibility reasons. Other themes can choose to show or not show it of course.

The `remove-position` prop changes the DOM position, but the snow theme uses flexbox order to ensure it always renders this way.

Hope that clears it up 👍

![image](https://user-images.githubusercontent.com/1950463/122066973-2fd80300-cdc1-11eb-8536-50f6da64f184.png)

**Comment by jerryfan** [comment]
@justin-schroeder Totally makes sense. However, in an environment where I don't have the snow theme included, with the following json being fed in:

{
      "type": "group",
      "repeatable": true,
      "name": "testGroup",
      "add-label": "+ Add Item",
      "remove-label": "- Remove Item",
      "remove-position": "after",
      "children": [ ... ]
}

I still get:

<div class="formulate-input-group-repeatable">
     <a role="button" class="formulate-input-group-repeatable-remove">Remove</a>
     <div>children</div>
</div>

Remove button is rendered with "_Remove_" _before_ the children.
