### ISSUE TITLE
vueformulate.com examples disappear on click of radio button/checkbox

### ISSUE THREAD

**Issue by saschwarz** [wearebraid/vue-formulate#445]
**Describe the bug**
Clicking any example radio button or checkbox in the examples causes that example to disappear.

**To Reproduce**
1. Go to https://vueformulate.com/#single-element-inputs
2. Click on radio button for 'It's good'
3. The example pane goes blank. 

This happens for any checkbox or radio button in any of the examples on the home page

**Expected behavior**
Shouldn't disappear 😄 

**Screenshots**

![image](https://user-images.githubusercontent.com/184171/122123447-98d86e80-cdf3-11eb-8d45-0687e5f6fcef.png)

**Device information:**
 - Device: Mac Book Pro 
 - OS: Big Sur 11.4 (20F71)
 - Browser Google Chrome 
 - Version 91.0.4472.77 (Official Build) (x86_64)

**Comment by andrew-boyd** [comment]
😅

Well, that's interesting. Thanks for the report!

**Comment by chrisnbattista** [comment]
Can replicate. Chrome v91 on Mac.

**Comment by justin-schroeder** [comment]
I think this if fixed now 🎉
