### ISSUE TITLE
:values with the same object key structure do not change when props do.

### ISSUE THREAD

**Issue by fenilli** [wearebraid/vue-formulate#451]
**Describe the bug**
Passing down props to a components where it uses those props inside :values and :schema props.  FormulateForm wont change values if the keys are the same of the :values props are the same.

**To Reproduce**
1. Have a ref array.
2. Put two obj values + schema inside it like [{ schema: [...], options: {id: 1, ...} }, { schema: [...], options: {id: 2, ...} }] with the same options keys, { component: 'h2', children: 'header' },  { component: 'h1', children: 'header' }
3. Have a selected component with a ref();
4. Set the selected to the first obj of the array.
5. Change value, using @submit, find the obj inside array using find, and change it.
6. Set the selected to the second item on the array.
7. Props inside the component that recieve selected changes, :values do not.

**Reproduction**

https://codesandbox.io/s/formulateform-not-changing-values-zlv4j

**Expected behavior**
It should change the values inside the inputs if the props change.

**Screenshots**

![](https://cdn.discordapp.com/attachments/656887891871531008/857680199080476682/Captura_de_ecra_de_2021-06-24_14-53-14.png)

![](https://cdn.discordapp.com/attachments/656887891871531008/857680214782771200/Captura_de_ecra_de_2021-06-24_14-53-18.png)

![](https://cdn.discordapp.com/attachments/656887891871531008/857680221956079636/Captura_de_ecra_de_2021-06-24_14-53-56.png)

**Device information:**
 -Google Chrome

**Comment by fenilli** [comment]
By changing the :values to v-model, it works as expected, but you're mutating a variable and using the @submit you get that mutated data to be passed as real data to the array, not the best solution as of right now.

**Comment by justin-schroeder** [comment]
Sounds like you figured it out, but `:values` is for setting initial values. `v-model` if you need external mutations. To get a de-bound object for submission, use the argument passed to your submit handler. This has been deeply cloned for you already 👍

**Comment by fenilli** [comment]
I changed and it seemed to work, but after some more testing v-model does "work" for some cases, but when changing between values it gives [Vue warn]: Erro in callback for watcher "formulateValue": "Typeerror: o.shallowEqualObjects is not a function"

Is there a correct way to change between schemas and v-models dynamically?

**Comment by fenilli** [comment]
if anyone is having similar problems I made it work with nextTick and :values instead of v-model, the idea is to deselect the value, and set the item in the nextTick, so vue has time to destroy and recreate the object, otherwise some bugs my happen.
