### ISSUE TITLE
Performance drop when typing ( generating forms in firefox )

### ISSUE THREAD

**Issue by merijnponzo** [wearebraid/vue-formulate#452]
If i start wildy typing within the VueFormulate generated form, the performance becomes really bad after typing let's say 20 seconds. It look's this only happens in Firefox, with chrome and safari i don't have issues.

Also with the example on https://vueformulate.com/guide/forms/generating-forms/
I don't see any performance drops.

I published a repo to make sure this also happens with a fresh nuxt installation:
git@github.com:merijnponzo/nuxt-formulate.git

Sorry i just added the form to the logo component ;-)
But just keeps typing in the textfield, and clear your field and type again, after let's say 20 seconds i clearly see a lagg.
and after let's say 30 seconds it takes seconds before my characters shows up in the textfields

![nuxtformulate](https://user-images.githubusercontent.com/23075300/123506849-89182000-d666-11eb-8c3a-8f813a082ac8.gif)

**Device information:**
MacBook Pro (Retina, 13-inch, Early 2015)
MacOS catalina
Firefox 89.2

**Comment by justin-schroeder** [comment]
@merijnponzo groups in particular can suffer from performance problems, although generally only with really large groups. These issues will largely be addressed in the next major version — for now you can add the `debounce` prop to not propagate an input's local changes to the rest of the tree until the user is done typing — this makes the form feel much more snappy. Also serializing data and outputting it (like in the gif) can sometimes cause it to slow waaay down. I haven't figured out why as it seems like it would be a "cheap" operation.

**Comment by merijnponzo** [comment]
I guess only a small percentage of my site visitors use firefox, but still, i find it curious why this problem is significant in firefox.
Success with the next major version, i'm very happy with vue-formulate

**Comment by develth** [comment]
Started a new Project with Formulate (really. thanks! fun to setup and a big support in coding) and also using the nuxt Plugin & testing on MacOs with Firefox.
The Form has around 15 Fields. As @merijnponzo mentioned, it the performance drops really fast. Even after removing all Groups ("Checkbox, FormInput type Group"). Debounce helps a little bit, but also starts having recognizable delays. 

Do you have any informations about the mentioned next major version @justin-schroeder ?

Thanks!

**Comment by luan-nk-nguyen** [comment]
@develth — FormKit, currently in private Beta — is a lot more performant than Vue Formulate. The FormKit public Beta and V1 should both be released this quarter (Q1 2022), but unfortunately will not support Vue 2 right away (it _may_ in the future).

Currently, we have no plans on significantly increasing performance of Vue Formulate beyond its current level. We'd probably sooner have FormKit support Vue 2, which should solve your problem.
