### ISSUE TITLE
Passing custom input data properties into :validation-rules params

### ISSUE THREAD

**Issue by BennaceurHichem** [wearebraid/vue-formulate#459]
### Discussed in https://github.com/wearebraid/vue-formulate/discussions/458

<div type='discussions-op-text'>

<sup>Originally posted by **BennaceurHichem** July  3, 2021</sup>
I'm implementing a phoneInput that contain two parts, the first is the flag of the country, with the countryCode and dialCode, the second is the phone input, I want to create a custom validation that validates the phone number using an external library which libphonenumber-js.
Th problem is that in the params passed into :validation-rules is the value only as I see in the doc : https://vueformulate.com/guide/validation/#custom-validation-rules

How can I pass the countryCode which is a data property in the custol input, to the params of the :validation-rules prop, to use it for validation with libphonenumber-js like this : 
```
 :validation-rules="{
        phoneValidation: ({ value,//here I shoul get the countryCode }) => {
          const pn = parsePhoneNumberFromString(value, //passcountryCode here for custom validation);
          return pn?.isValid() ? true : false;
        },
      }"
```</div>

**Comment by justin-schroeder** [comment]
@BennaceurHichem there are 2 arguments, for example:

```vue
<FormulateInput
  validation="phoneValidation:+1,usa"
/>
```

```js
phoneValidation: ({ value }, countryCode, countryName) {
 // do your validation here 🎉
}
```
