### ISSUE TITLE
Documentation typo: addMore label is improperly cased

### ISSUE THREAD

**Issue by rbeard0330** [wearebraid/vue-formulate#465]
**Describe the bug**
The documentation here:
https://vueformulatecom-git-release-250-braid.vercel.app/guide/inputs/types/group/#slots

gives the name of the `addMore` slot on group inputs as `addmore`.

**To Reproduce**
This seems to work fine for using the slot, but trying to override `addmore` as a slot component will not work--it needs to be `addMore`.

**Comment by justin-schroeder** [comment]
Thanks @rbeard0330 this should be fixed now!

**Comment by hisuwh** [comment]
Seems only `addmore` works for the slot name.  Seems to be an inconsistency here between the slot and the slot component?
