### ISSUE TITLE
Request: a method to apply classes globally to all inputs of a given type using class keys

### ISSUE THREAD

**Issue by Benjamin-Lee** [wearebraid/vue-formulate#469]
**Describe the new feature you'd like**

Please forgive me if this already implemented in the project: I am new but from reading the documentation can't seem to find what I'm looking for. I want to apply classes to my text inputs but not my submit inputs. I know I can write a custom function to do that but it would be really nice if I could do `textInputHasErrors` or simply `textInput`.

**Comment by justin-schroeder** [comment]
Hi @Benjamin-Lee.

Like you said, there's not way to infer that data directly with a single function, but it's pretty easy to do with a single global function.

```js
Vue.use(VueFormulate, {
  classes: {
    input (context) {
        if (context.classification === 'text) {
            return ['your additional classes go here']
            // return 'or replace all classes with these if you pass a string'
        }
    }
  }
})
```

Good luck 👍
