### ISSUE TITLE
Docs: Add info about date format

### ISSUE THREAD

**Issue by rowild** [wearebraid/vue-formulate#472]
I was just about to ask about how to reformat the date field, when I found this entry, which is already closed: #151 

How about adding this information to the documentation? I think this would help quite a lot, since many forms use date in some form and having this info at hand right away would save time on research (and therefore make VueFomulate even more user friendly).

**Comment by justin-schroeder** [comment]
Thanks for the suggestion! I'm happy to accept docs PRs over on (that repository)[https://github.com/wearebraid/vueformulate.com] — I think your suggestion sounds totally valid.
