### ISSUE TITLE
Adding atserics for text inputs when the required validation  is applied 

### ISSUE THREAD

**Issue by BennaceurHichem** [wearebraid/vue-formulate#478]
**Describe the new feature you'd like**

I want to add an atserisk to the inputs hat required validation is applied to distinguish between those inputs who are required from users and those who are optional

How can I do that please ? help wanted 
![image](https://user-images.githubusercontent.com/31354135/128884279-c3aac82d-2997-412d-8dfd-8e50f0acd4e3.png)

**Comment by justin-schroeder** [comment]
There are a number of ways to do this, but if this is a feature you want on all your inputs, use a `slotComponent` for the `label` slot, and then read the `rules` property on the context object that is passed in as a prop to that component.

https://vueformulate.com/guide/inputs/slots/#slot-components

Good luck 👍 If you make a nice plugin feel free to add it to the list here: https://vueformulate.com/guide/plugins/

**Comment by BennaceurHichem** [comment]
Thanks for your response sir @justin-schroeder , from my side I made a snippet for one element and it works to show asterisk with label, this is an example for a custom input called toggablePassword 

```
 <template #label="{ label, id,rules }">
            <label :for="context.id">
              {{context.label}}
              <span v-if="context.rules.filter(rule => rule.ruleName=='required').length" class="text-primary-600">* </span>
            </label>
       </template>


```

and it works globally, the only problem is that when I pass the `CustomLabel` into the slotComponents all inputs are working well except the radio and checkboxes where the styling applied on them globally changed like you see, because the checkbox and radio text is a label which is maybe affected with this customLabel, this behaviour is clearly unwanted, any hints about that 

![image](https://user-images.githubusercontent.com/31354135/129496660-81a452ce-05a6-4c54-aa96-a34c0eb4dded.png)
