### ISSUE TITLE
Schema not reactive with attributed computed properties 

### ISSUE THREAD

**Issue by BennaceurHichem** [wearebraid/vue-formulate#480]
I had a problem where I used to generate a form with a schema, what I want to achieve is the possibility of disabling inputs and changing label to Loading.. instead of submit when the async login request starts, to do that I tried to attribute isLoading variable from the context of the FormulateForm into the disabled attribute of the submit button like that : 
```
{
      type: 'submit',
      'outer-class': ['text-center w-full'],
      'input-class': ['w-full'],
      disabled: **this.isLoading**,
      loading: **this.isLoading**? true : false,
      label: **this.isLoading** ? 'Loading...' : this.$i18n.t('LAYOUT.logIn'),
      '@click': 'click-login',
    },
```

where both this.submited and isLoading are computed properties, where they reffere to the FormulateForm gotten using refs like that: 
```
/** FormulateForm instance **/
      <FormulateForm ref="vf_form" :schema="vfschema" @click-login="login" v-model="credentials" />
/** computed properties **/
 private get isValid(): boolean {
    console.log('ref: ');

    console.log(this.$refs.vf_form);
    return this.$refs.vf_form ? (this.$refs.vf_form as VueFormulate).isValid : false;
  }
  private get submited(): boolean {
    return this.isSubmitted;
  }

  private get vfschema() {
    return this.schema;
  }
```

isLoading and isValid are changing properly and they are accessed properly using the ref of FormulateForm,
### Problem: 
 the problem is that even if all these are computed, the attribution of computed properties like `this.isLoading ` to a specific formulateInput in the schema doesn't change at all, which mean that the behavior of any inputs couldn't be changed dynamically based on the validity or loading state of the form

How can I attribute a computed property to a specific FormulateInput in a schema, to change dynamically their behavior based on the change of formulateForm state?

**Comment by justin-schroeder** [comment]
This is generally true, there are ways to extract state from scoped slots and to use them in your computed schema, but it is hacky and not the way Vue is supposed to be used. We're working hard to make schemas much more useful with dynamic values in [FormKit](https://formkit.com/).

There are a number of issues pointing out the limited nature of schemas at the moment, but we'll track them all here: #230
