### ISSUE TITLE
Arrow toggle in select box

### ISSUE THREAD

**Issue by angeloatzicht** [wearebraid/vue-formulate#486]
We couldn't find this feature so we would like to request it.
When we have a selectbox (dropdown) with multiple options, it would be really helpful if we could have an arrow (as most dropdowns have) that would toggle between up and down (chevron up/ chevron down for example) when the dropdown is opened or closed.

This can be archieved with CSS, but only on a "focus" state meaning that after selecting an option from the dropdown, the icon will not toggle back to its original position. Only after clicking outside of the dropdown the icon will toggle back due to losing its focus.

If this is already possible, I hope someone can explain this to me. If not, I am sure that a lot of people would love to see this feature implemented with an option to provide your own icon to use.

**Comment by justin-schroeder** [comment]
Thanks for the suggestion @angeloatzicht. Vue Formulate uses native `select` inputs — which dont really have this kind of variation. Your best bet is to create a custom input that uses a "synthetic" dropdown.
