### ISSUE TITLE
Change language in Vuex, using Nuxt

### ISSUE THREAD

**Issue by pmcp** [wearebraid/vue-formulate#490]
What's the proper way to change i18n, using Vuex and Nuxt? I'm using the config file, but am confused how to change the language now. Any help is appreciated ❤️

**Comment by justin-schroeder** [comment]
I'm not sure how you have your project setup, but from Vue Formulate's perspective you just need to use `$formulate.setLocale('fr')`

**Comment by DeivisFelipe** [comment]
Your answer doesn't make sense because $formulate doesn't work on nuxt

**Comment by justin-schroeder** [comment]
@DeivisFelipe 🤔 want to elaborate?

**Comment by DeivisFelipe** [comment]
I made it
`buildModules: [
    // vue-formulate
    '@braid/vue-formulate/nuxt',
  ],`
But neither $formulate nor this $formulate exist, nuxt says it is undefined

**Comment by DeivisFelipe** [comment]
![image](https://user-images.githubusercontent.com/36674115/148146657-363759b9-1abe-4248-a26d-16220e0f7e10.png)

**Comment by DeivisFelipe** [comment]
In this file here
https://github.com/nuxt-community/axios-module/blob/main/lib/plugin.js
hás
// Inject axios to the context as $axios
  ctx.$axios = axios
  inject('axios', axios)

**Comment by DeivisFelipe** [comment]
in this file here
https://github.com/nuxt-community/vuetify-module/blob/master/templates/plugin.js
hás the same code
ctx.app.vuetify = vuetify
ctx.$vuetify = vuetify.framework
