### ISSUE TITLE
Is there a way to define a uploader function in the FormulateInput instance when you generate it from json ?

### ISSUE THREAD

**Issue by educanovas93** [wearebraid/vue-formulate#495]
You can do this correctly

`<FormulateInput
    type="file"  
    :uploader="uploadFile"  
  />`

`<script>
export default {
  methods: {
    async uploadFile (file, progress, error, option) {
      // ... perform upload
    }
  }
}
</script>`

But if i try to generate the form from json...

`{
                type: 'file',
                name: 'attached',
                label: 'Attach a file',
                value: null,
                uploader: 'uploadFile',
},`

that doesn't work, is there any way to do it ?

Thanks a lot!

**Comment by justin-schroeder** [comment]
You can define your uploader function globally, and that would also work for the schema:

```js
Vue.use(VueFormulate, {
  uploader: axiosInstance,
  uploadUrl: '/upload'
})
```

https://vueformulate.com/guide/inputs/types/file/#how-it-works

Good luck 👍

**Comment by educanovas93** [comment]
thank you so much! it works!
