### ISSUE TITLE
Can't target labels of checkboxes when using `Box` input with `options`

### ISSUE THREAD

**Issue by w00fz** [wearebraid/vue-formulate#497]
Hey there,
I'm trying to use multi-checkboxes where some options can end up disabled. On the styling side I would like those disabled options to look greyed out but I am finding no way possible to target via `label-class` prop or `#label` scope the checkboxes inputs label (not the decorator but the actual text label).

While looking at the tests I also noticed there is an example that doesn't seem right (https://github.com/wearebraid/vue-formulate/blob/master/test/unit/FormulateInputBox.test.js#L347-L377). The `type` is set to text instead of checkbox but more to the point, this seems to be trying to test exactly the behavior described above. Unfortunately that will only target the prefix/suffix of the group classified input and not the individual checkboxes.

Here I have a simple setup of what I'm trying to do in this codepen: https://codepen.io/w000fz/pen/JjJxzra

**Expected behavior**
Ideally it would be great to be able to target the checkboxes label via prop. Although because `label-class` will target the main label, this will have to be something else.
What makes this also trickier is that there is a second label, used as decorator, however this should not be impacting anything in regards to the input label.

Am I missing something or is this a missing feature? Any workaround for this? 

Thank you for the great project!

**Comment by justin-schroeder** [comment]
@w00fz agreed that it would be nice to be able to target more attributes of those options. We're working towards that goal with the [FormKit](https://formkit.com) re-write.

That said, the class system in Vue Formulate is pretty powerful, and is able to accomplish what you're looking for. What you want to do is extend the `wrapper` class key at the global options level:

```js
Vue.use(VueFormulate, {
  classes: {
    wrapper: (ctx, classes) => classes.concat(ctx.attrs.disabled ? ['is-disabled'] : [])
  }
})
```
Here's a fork of your codepen:

https://codepen.io/justin-schroeder/pen/rNwbxPR

**Comment by w00fz** [comment]
Thank you @justin-schroeder, with the wrapper approach, I might be able to achieve what I was trying to do via custom css. 

 I'm also excited to hear about FormKit, sounds very promising!
