### ISSUE TITLE
Display Radios or Checkboxes Input Horizontally

### ISSUE THREAD

**Issue by M457ERCH1EF** [wearebraid/vue-formulate#50]
**Describe the bug**
Hi guru,
Is there a way to display the radios or checkboxes input horizontally?
![image](https://user-images.githubusercontent.com/57579708/77414808-87750200-6dfc-11ea-9fed-343bd0632368.png)

Thanks on advance

**Comment by justin-schroeder** [comment]
@M457ERCH1EF fair question, `vue-formulate` isn't really a UI library (although admittedly the lines are blurred since it has a default theme) but it expects you to occasionally write some of your own styles to make things just the way you want.

```vue
<template>
<FormulateInput
  type="radio"
  :options="myOptions"
  class="horizontal"
/>
</template>

<style scoped>
.horizontal::v-deep .formulate-input-group {
 display: flex;
 flex-wrap: wrap;
}
.horizontal::v-deep .formulate-input-group > .formulate-input {
 margin-right: .5em;
}
</style>
```

Hope that helps

**Comment by M457ERCH1EF** [comment]
thanks, really appreciate it..
