### ISSUE TITLE
type="autocomplete"

### ISSUE THREAD

**Issue by hamzabawumia** [wearebraid/vue-formulate#500]
Could you kindly add type="autocomplete" as part of the default package, since it is a commonly used thing these days. Thank you. Vue-formulate is  awesome

**Comment by justin-schroeder** [comment]
Sorry @hamzabawumia, Vue Formulate does not include synthetic inputs in the core package and there are no plans to change that, but you’re welcome to create/publish a plugin for it! We'll even link to it from the [plugin docs page](https://vueformulate.com/guide/plugins/#community-plugins). That said the next major version of Vue Formulate is called [FormKit](https://formkit.com) and it will be released with a synthetic inputs like autocomplete for a small fee — currently accepting beta signups for a preview later this year.
