### ISSUE TITLE
Is there a way to disable all fields via a prop on the <FormulateForm /> component?

### ISSUE THREAD

**Issue by JackEdwardLyons** [wearebraid/vue-formulate#511]
I need to implement logic to disable all inputs once a specific criteria is met (ie) once the form is lodged.
I'm just wondering if it's possible to do this using a prop / event in VueFormulate.
If it's not possible, do you have any recommendations on how to do this (ie) querySelect all inputs and add `disabled` for each el?

Thanks for creating such an awesome library!

Jack

**Comment by justin-schroeder** [comment]
There is not a way to do this via prop (although there is a way to do this in [FormKit](https://www.formkit.com)).

It is possible to do this in Vue Formulate, but its not super reliable and requires using refs to manually reach-into the components. That said, something like this could work for you:

https://codepen.io/justin-schroeder/pen/NWaxVZN

**Comment by JackEdwardLyons** [comment]
Thank you so much! I really appreciate the help. I tried this with a group field and it doesn't make them disabled.
Is there a way to do it for all repeater / group fields too?

I guess I could just do some recursive fn checking the "type" and if it is of type `group`, call the fn again...? thoughts

Thanks in advance

**Comment by JackEdwardLyons** [comment]
If I just use vanilla JS I can do this and it'll work

```
   const els = Array.from(this.$refs.form.$el);
   els.forEach((el) => {
      el.setAttribute("disabled", true);
   });
```

Please let me know if this isn't a good idea ? @justin-schroeder

**Comment by justin-schroeder** [comment]
> I guess I could just do some recursive fn checking the "type" and if it is of type `group`, call the fn again...? thoughts

Yep! That should work — although like you I dont see anything strictly wrong with the direct DOM manipulation either. It's not normally I'd like to see things done, but we're already in "hacky" land with either solution.

Good luck 👍
