### ISSUE TITLE
vue-formulate nuxt-vite problem on nanoid

### ISSUE THREAD

**Issue by flavionn** [wearebraid/vue-formulate#514]
hey guys

im trying to use vue-formulate with nuxt and nuxt-vite but getting this error:

```Uncaught SyntaxError: The requested module '/node_modules/nanoid/non-secure/index.js?v=fa317317' does not provide an export named 'default'```

any workaround on this?

nuxt clean install and using yarn and
```json
"nuxt-edge": "^2.16.0-27226092.034b9901",
"@braid/vue-formulate": "^2.5.2",
"nuxt-vite": "0.2.4",
```

**Comment by f-llewellyn** [comment]
I'm getting this issue with regular vue. Anyone have a solution?

**Comment by justin-schroeder** [comment]
Hmm, I wonder if we should just remove nanoid entirely. We dont use it for very much and i think it could be replaced easily. I'll look into this.

**Comment by addidesign** [comment]
Also an error with a regular vue-vite app too

**Comment by justin-schroeder** [comment]
@addidesign can you provide a reproduction repository?

**Comment by maspio** [comment]
I also encountered this problem using vite. It crashes instantly on using VueFormulate.

**Comment by justin-schroeder** [comment]
@addidesign and @maspio are your vite apps setup for vue2? Vue Formulate is not compatible with vue3 which is the default vue setup with vite.

**Comment by justin-schroeder** [comment]
@flavionn this issue is now fixed. I've removed nanoid and is-url dependencies entirely, so everything should be fully esm compatible.

That does not mean Vue 3 compatible, [FormKit](https://www.formkit.com) is Vue 3 compatible and the spiritual successor to Vue Formulate (although Vue Formulate will continue to be developed/maintained).
