### ISSUE TITLE
Input type:date doesn't show default date placeholder on mobile chrome explorer

### ISSUE THREAD

**Issue by AbnirHencazs** [wearebraid/vue-formulate#515]
**Describe the bug**

When using a FormulateInput of date type, it is expected for the field to show a default locale date placeholder. This is met for Firefox explorer both desktop and mobile, but not for Chrome since mobile only shows a blank field (desktop Chrome works as expected).

**To Reproduce**

So this was first noticed by me on my application using vue-formulate, trying to reproduce on vue-formulate guide I found the same issue:
1. Open a Chrome browser on a mobile device (not device toolbar option from desktop Chrome).
2. Navigate to this link https://vueformulate.com/guide/inputs/types/text/#date
3. See blank space on date input where it should be a default date format placeholder.

**Expected behavior**

To see a default date format placeholder on a date type input.

**Screenshots**
![dateinput bug](https://user-images.githubusercontent.com/18602479/148304427-2afdbce4-3018-427b-be25-5b105a20d2e6.jpeg)

**Device information:**
 - Device: Xperia G3423
 - OS: Android 8.0
 - Browser Mobile chrome
 - Version 97.0.4692.70

**Comment by justin-schroeder** [comment]
@AbnirHencazs the date input uses the standard HTML date input so the features you are asking about are not actually part of Vue Formulate. However, the caniuse.com data for chrome mobile says the date input is supported, so im not sure why yours isnt working, but I'm confident it isnt something we are doing. I wonder if the standard MDN docs work on your phone: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

**Comment by AbnirHencazs** [comment]
@justin-schroeder Thank you for quick response!

Yes, standalone date type and MDN docs works just fine on my phone, that's what led me to believe the issue might be on the package. Also, I tried with multiple devices and seeing same result. So, maybe it is a chrome bug instead?

**Comment by justin-schroeder** [comment]
possibly 🤷‍♂️ I'm unable to duplicate this issue though :( I'll close it for now but you can re-open it if youre able to find a good reproduction
