### ISSUE TITLE
Validation doesn't update on language change

### ISSUE THREAD

**Issue by zerbash** [wearebraid/vue-formulate#523]
**Describe the bug**
If you switch languages, the validation message doesn't update to reflect the new language. 

**To Reproduce**
1. Go to https://codesandbox.io/s/vue-formulate-reproduction-template-forked-imt1l?file=/src/components/Reproduction.vue
2. Click on Spanish
3. Validation message doesn't change
4. Changing the _content_ of the field _does_ trigger the change (type 'a', delete 'a': the correctly translated message displays)

**Expected behavior**
Validation messages should reflect the selected language. The correct translations _do_ show on submit.

**Comment by justin-schroeder** [comment]
In order for the locale to be reactive on validation messages your inputs need to be inside a named form (`<FormulateForm>` that has the `name` attribute specified). Here's your example working:

https://codesandbox.io/s/vue-formulate-reproduction-template-forked-j0ccis?file=/src/App.vue

Good luck 👍
