### ISSUE TITLE
problem with first example from the doc with vue 3

### ISSUE THREAD

**Issue by lingtalfi** [wearebraid/vue-formulate#533]
Hi, sorry I'm a noob in Vue3, but I have a main.js file that looks like this:

```
import { createApp } from 'vue'
import router from '@/router'
import App from './App.vue'
import VueFormulate from '@braid/vue-formulate'



createApp(App)
.use(router)
.use(VueFormulate)
.mount('#app')
```

which leads to this message error: **Uncaught TypeError: t.prototype is undefined**

I also tried this:

```
import { Vue,createApp } from 'vue'
import router from '@/router'
import App from './App.vue'
import VueFormulate from '@braid/vue-formulate'


Vue.use(VueFormulate);

createApp(App)
.use(router)
.mount('#app')
```

which gives me: **Uncaught SyntaxError: import not found: Vue**.

In other words, I don't know how to get started with vue formulate.
I suppose I'm doing something wrong, could you help me with this please ? 

Ps: I was referencing to this page of the doc: https://vueformulate.com/guide/installation/#add-to-vue
which provides the following snippet:
```
import Vue from 'vue'
import VueFormulate from '@braid/vue-formulate'

Vue.use(VueFormulate)

```

**Comment by justin-schroeder** [comment]
@lingtalfi vue formulate does not support Vue 3. What you’re looking for is FormKit- the spiritual successor to Vue Formulate, built specifically for Vue 3 but with an improved architecture: https://formkit.com

good luck 👍

**Comment by lingtalfi** [comment]
thanks
