### ISSUE TITLE
Ability to custom validate type="image" for a {url:base64string}

### ISSUE THREAD

**Issue by mingyuen78** [wearebraid/vue-formulate#535]
I currently developing a project using formulate, specifically on the file image upload. I made a custom handleUpload based on the event uploader. Crop myself and compress a nice base64 of the image. I then, return it into the formValues {url: it's base64, name: filename.png}. i plan to upload it much later - giving the user chance to edit its image like attachment.

problem is, i cant seems to figure out how to custom validate the incoming base64 as it always returns invalid , i tried to use custom rule such like 

this :validation-rules="{
      customBase64Rule: ({ value }) => ['base64'].includes(value),
}"

im assuming it checks for the string base64 within value? but i cant seem to get it to validate properly.  is there a mime check specifically for base64?

**Comment by justin-schroeder** [comment]
have you checked the shape of that `value` object? The image type is an extension of the `file` type, which creates an instance of `FileUpload` to handle things like the images and what not — this is the "value" of that input — it is not just a string. Although I'm not really sure what specifically you are doing in your modification.

I might be able to help better if you create a reproduction on codepen or code sandbox (See community page for starters)
