### ISSUE TITLE
Add the ability to group and repeat fields.

### ISSUE THREAD

**Issue by justin-schroeder** [wearebraid/vue-formulate#56]
To address this, we should add something like a new `group` type that allows nesting of fields. Example API:

```vue
<FormulateInput
  type="group"
  name="users"
  repeatable="true"
  limit="2"
  #default="{ groupState }"
>
  <FormulateInput
     name="username"
  />
  <FormulateInput
    value="password"
    type="password"
  />
</FormulateInput>
```

The modeled data output for the above would be something like:

```js
{
  users: [
    {
      username: 'jane',
      password: 'secret'
    },
    {
      username: 'jill',
      password: 'shhh'
    }
  ]
```

**Comment by k-slash** [comment]
That would be awesome!
Beyond having fields, it would be nice to have other components such as images, fieldsets, titles, ...
So, we could create templates directly in json for example:
```
[
  {
    "name": "instrument_informations",
    "type": "fieldset",
    "label": "Instrument informations",
    "content": [
      {
        "name": "instrument_name",
        "type": "text",
        "label": "Instrument name",
        "validation": "required",
        "placeholder": "Enter something..."
      },
      {
        "help": "A serail number is also known as SNID",
        "name": "serial_number",
        "type": "text",
        "label": "What is the serial number ?",
        "validation": "required",
        "placeholder": "Enter serial number..."
      }
    ]
  },  
]
```

And that would be so wonderful!

**Comment by justin-schroeder** [comment]
Anything you placed inside a `group` would be repeatable too. I'm sympathetic to full JSON rendering I also want to avoid recreating HTML in JSON format. I have thought that some combination of Vue Formulate with a `<component :is v-for>` tag would be really powerful — in which case you could in theory recreate HTML almost entirely in JSON format.

That might be a nice Vue Formulate plugin! Although I don't think it’s directly related to this feature (wanna write a plugin 😉).

**Comment by k-slash** [comment]
Yeah, sorry, I should have created a new issue for this feature request. But, yeah, creating forms through JSON format is really useful and powerful. It will allow to users to create their own forms. I'd like to take this opportunity to thank you for your work. You are awesome ! :)
