### ISSUE TITLE
How to change the range slider dot color?

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [wearebraid/vue-formulate#581]
**Describe the bug**
We want to change the dot color from green to another custom color.

**To Reproduce**
We want to change the dot color from green to another custom color.

**Reproduction**
Have a range slider in the schema or form. We will see the slider dot in green color.

### CodePen:
https://codepen.io/rajeshwarpatlolla/pen/zYmEryP

**Expected behavior**
Color should be customizable to match the websites.

**Screenshots**
<img width="536" alt="Screenshot 2023-05-01 at 20 52 09" src="https://user-images.githubusercontent.com/9896335/235476367-5d2a96d7-ff48-4c2e-8a0d-e840ee373b86.png">

**Comment by justin-schroeder** [comment]
That is just styled with css. The existing selector is:

```
.formulate-input[data-classification=slider] input::-webkit-slider-thumb
```

**Comment by rajeshwarpatlolla** [comment]
This css class is not applying any color to slider or dot @justin-schroeder
