### ISSUE TITLE
Vue Formulate Fails to run with Inertia js 

### ISSUE THREAD

**Issue by tonyjemba** [wearebraid/vue-formulate#586]
I am running vue 3(script setup) with inertia(Laravel), After importing vue formulate and registering it in the inertia app. Accessing FormulateInput component in vue component(script setup) throws an error in the console:  Cannot set properties of undefined (setting '$formulate').
Here is my app.js
`import "./bootstrap";
import "../css/app.css";

import VueFormulate from "@braid/vue-formulate";

createInertiaApp({
    title: (title) => `${title} - ${appName}`,
    resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob("./Pages/**/*.vue")),
    setup({ el, App, props, plugin }) {
        const app = createApp({ render: () => h(App, props) });

        return app.use(plugin).use(VueFormulate).mount(el);
    },
    progress: {
        color: "#6bbaff",
    },
});
`

**Comment by andrew-boyd** [comment]
Vue Formulate does not support Vue 3 — you’ll want to check out its successor (also made by us),[FormKit](https://formkit.com)

**Comment by tonyjemba** [comment]
Okay thanks.
