### ISSUE TITLE
FormulateInput "checkbox" and "radio" options not working with validation as expected

### ISSUE THREAD

**Issue by andrew-boyd** [wearebraid/vue-formulate#6]
I'm putting together some homepage demos on vueformulate.com which is using `@braid/vue-formulate` at version `2.0.4` and in the process have noticed that the "checkbox" and "radio" input types do not validate as I expect.

## checkbox

When creating an input with type of `checkbox` the value is present without an interaction as an empty array rather than the key not existing in the returned object all.

![checkbox-empty-array](https://user-images.githubusercontent.com/2946356/75629166-9f66b680-5bad-11ea-915c-879b35ea8938.png)

My expectation would be to have it dropped from the modeled data entirely. Additionally, even though the demo has a validation rule of `required|min:1` it is not failing the check when I submit the form.

![checkbox-empty-array-validation](https://user-images.githubusercontent.com/2946356/75629204-de950780-5bad-11ea-9607-ab3284cf9a97.png)

## radio

A similar issue exists when the input is set to `radio`. The Initial value without any user interaction to the form appears to be the last option in the array of choices.

![radio-initial-selected-value](https://user-images.githubusercontent.com/2946356/75629220-0c7a4c00-5bae-11ea-8672-7c995aed8880.png)

This means that it also does not fail the validation rule check because there's a mapped value by default in the v-modeled `values` object.

![checkbox-initial-value-validation](https://user-images.githubusercontent.com/2946356/75629238-2d42a180-5bae-11ea-9fbc-11f7c23bad67.png)

**Comment by andrew-boyd** [comment]
Deployment exhibiting this behavior can be seen here: [https://vueformulatecom-obv6n2h7v.now.sh/](https://vueformulatecom-obv6n2h7v.now.sh/)

**Comment by justin-schroeder** [comment]
Yep, this is no bueno. Not sure why the tests haven’t caught this behavior, but we can write some against this specific issue and resolve.
