### ISSUE TITLE
Initialising FormulateInput type=select with options set to an empty array causes Range Error

### ISSUE THREAD

**Issue by ollieBaker** [wearebraid/vue-formulate#60]
**Describe the bug**
Initialising FormulateInput type=select with options set to an empty array causes a Range Error
`Error in render: "RangeError: Maximum call stack size exceeded"`

**To Reproduce**
Open page view console.

**Reproduction**
[View](https://olliebaker.github.io/vue-formulate-array-select-error/dist/)
[Code](https://github.com/ollieBaker/vue-formulate-array-select-error/blob/master/src/components/HelloWorld.vue)

**Expected behavior**
Passing an empty Array should should render the placeholder value in the select element. The same as passing an empty Object.

**Device information:**
Any browser

**Comment by justin-schroeder** [comment]
Thanks for the high quality report and reproduction. Definitely need to get this fixed asap.

**Comment by ollieBaker** [comment]
No problem, you're welcome, thanks for Vue Formulate!

**Comment by justin-schroeder** [comment]
@ollieBaker this is fixed in `2.2.8`
