### ISSUE TITLE
autocomplete prop

### ISSUE THREAD

**Issue by karahan** [wearebraid/vue-formulate#64]
Another one

**Describe the new feature you'd like**
autocomplete prop so browsers like chrome can automatically fill in the forms
https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill

**What percentage of vue-formulate users would benefit?**
80%

**Comment by justin-schroeder** [comment]
This should also be supported out of the box as a passed-down attribute. Same logic applies as to #63.

Good luck! 👍
