### ISSUE TITLE
Re-validate dependent fields on change

### ISSUE THREAD

**Issue by ollieBaker** [wearebraid/vue-formulate#68]
**Describe the bug**
Validation runs are only checked when the user changes field values. This breaks the confirm validation rules.

**To Reproduce**
[Docs Example](https://vueformulate.com/guide/validation/#available-rules)

Add a New password e.g "123"
Add matching password to Confirm password - Validation passes

Change New Password & Submit. The form will pass validation even though the values are not the same any more.

**Reproduction**
See docs example

**Expected behavior**
Validation should fail if the values are not the same.

**Comment by ollieBaker** [comment]
Thanks for the response to the problem. I agree it is more complex than it first seems and that option three appears the best solution but also the most complex.

Is there a reason that allowing running of validation programmatically isn't possible? That way it could be done optionally when the user attempts to submit a form.

**Comment by justin-schroeder** [comment]
@ollieBaker thats a good idea. In fact, it might be wise to re-run all validation rules on all submissions automatically. The submit event is relatively sparse, so “Expensive” operations at that point are totally acceptable. I'll tag this for `v2.3` as that has a fairly significant overhaul pending on the way the form registry works, so slipping this in shouldn't be a major issue.

**Comment by ollieBaker** [comment]
OK great, looking forward to trying out `v2.3`. Thanks again!

**Comment by pimhooghiemstra** [comment]
Just read this thread after opening the duplicate #72 which is closed now.

I also think that option 3 is the best, and indeed, running validation programmatically would be nice.

I don't have any new thoughts or ideas on this, but I am willing to test this once released for my usecase/scenario.

Great work, love the plugin already!

**Comment by justin-schroeder** [comment]
Also, it might be helpful to know you are able to explicitly run validation rules today, just not with a "public" API (small possibility it would be subject to breaking changes on non major version updates). To do it you just set a `ref` on an the `FormulateInput` in queston and call the `performValidation` function on it. So for the password confirmation example:

```vue
<template>
  <FormulateInput
    type="password"
    name="password"
    ref="password"
    @input="runValidation"
  />
  <FormulateInput
    type="password"
    name="password_confirm"
    ref="passwordConfirm"
    @input="runValidation"
  />
</template>

<script>
export default {
  methods: {
    runValidation () {
      [this.$refs.passwordConfirm, this.$refs.password]
        .forEach(input => input.performValidation())
    }
  }
}
</script>
```

**Comment by justin-schroeder** [comment]
I think this falls so out-of-line with a developer's expectation of how it should work, I would consider it a bug. This will be one of the first things to address _before_ `2.4.0`.
