### ISSUE TITLE
Inputs should deregister itself from forms when destroyed.

### ISSUE THREAD

**Issue by paulogr** [wearebraid/vue-formulate#69]
**Describe the new feature you'd like**
In my case I'm doing a form wizard, and when navigating from a step to another I can't go back and started again because some field, that aren't available anymore (destroyed) are still register and blocking the submit event.

**What percentage of vue-formulate users would benefit?**
50%

Here I see how the input register itself on form
https://github.com/wearebraid/vue-formulate/blob/master/src/FormulateInput.vue#L244

What about implement a `deregister` method on FormulateForm called from FormulateInput when destroyed?

Thanks!

**Comment by paulogr** [comment]
Besides that, keep destroyed fields registered is a memory leak, right?

**Comment by justin-schroeder** [comment]
100% this should be addressed. It’s both a memory leak, and a pain :)

The current progress on `2.3` includes a re-write of the registry, but the timeline on that release is uncertain because of size of feature additions.

Should be an easy enough PR though, any interest in submitting one as a 2.2 patch?

**Comment by paulogr** [comment]
Hi @justin-schroeder thanks for you reply.

Sure! I gonna look this issue on weekend and send you a PR for review.

**Comment by chrisladams** [comment]
Pull request: https://github.com/wearebraid/vue-formulate/pull/71

**Comment by justin-schroeder** [comment]
This is now merged and fix thanks to @chrisladams. Deployed in `2.2.9`, and the test case will ensure we have it implemented in `2.3.x` as well.
