### ISSUE TITLE
Allow extending css classes with custom classes

### ISSUE THREAD

**Issue by mario-minati** [wearebraid/vue-formulate#70]
**Describe the new feature you'd like**
We need to set custom css classes on the different html elements. This could be most likely get done by adding options.

**What percentage of vue-formulate users would benefit?**
100%

**Comment by justin-schroeder** [comment]
This is a solid idea, and is effectively a duplicate of #66, which is currently has a proposed solution for this and is open for suggestions. I'd really welcome your thoughts over on that thread 👍
