### ISSUE TITLE
Can't deploy site due to node engine requirements in package.json

### ISSUE THREAD

**Issue by gilesbutler** [wearebraid/vue-formulate#73]
**Describe the bug**
Whilst trying to deploy to Netlify we get the following error:
```
4:52:53 PM: error @braid/vue-formulate@2.2.9: The engine "node" is incompatible with this module. Expected version ">=11". Got "10.20.1"
4:52:53 PM: error Found incompatible module.
```

**Reproduction**
Your [package.json](https://github.com/wearebraid/vue-formulate/blob/master/package.json) is set as the following:
```
"engines": {
    "node": ">=11"
  },
```

**Expected behavior**
To be able to deploy on node versions less than 11 as it works fine on my local machine using node v10.18.1.

Is there a reason the engine requirement is 11+?

**Comment by justin-schroeder** [comment]
This is dumb on my part 😔. The engine is in there as an artifact of some SSR testing I believe. I’ll get this adjusted today.

**Comment by justin-schroeder** [comment]
ok @gilesbutler, engine has been removed and `v2.2.10` released as a patch for this. Thanks for pointing it out.

**Comment by gilesbutler** [comment]
Awesome, thanks for the super quick turnaround @justin-schroeder 👍
