### ISSUE TITLE
Horizontal line of the slider is not shown in Firefox

### ISSUE THREAD

**Issue by Verhoeckx** [wearebraid/vue-formulate#79]
**Describe the bug**
While reading the documentation about how to add a slider I noticed that the horizontal line of the slider isn't visible when you are using Firefox.

**To Reproduce**
1. Start Firefox (75). 
2. Open the following page: https://vueformulate.com/guide/inputs/sliders/.
3. Result: no horizontal line in the slider widget.

**Expected behavior**
I expect to see a horizontal line (like in Google Chrome/Chromium 80).

**Screenshots**

**Firefox 75**

![Vue Formulate - Slider - Firefox](https://user-images.githubusercontent.com/64807887/81009381-cdd66b80-8e54-11ea-9046-47263e9abbf3.png)

**Chromium 80**

![Vue Formulate - Slider - Google Chrome](https://user-images.githubusercontent.com/64807887/81009378-cd3dd500-8e54-11ea-9962-7f0fcde59bec.png)

**Device information:**
 - Device: Dell XPS 13 
 - OS: Fedora 32 (Silverblue)
 - Browser: Firefox
 - Version: 75

**Comment by Verhoeckx** [comment]
The border around the green circle should also not be shown.

**Comment by Verhoeckx** [comment]
That's quick!! Thank you very much!!

**Comment by Verhoeckx** [comment]
I think the version that the website uses should also be updated?

**Comment by justin-schroeder** [comment]
Thats right @Verhoeckx. Being pulled into master is not the same as being published. There's more involved, creating distribution files, tagging, publishing to npm, updating the documentation site, making a changelog...

But those things are done now. It's generally available in the now published `v2.2.13` (and the documentation site).

**Comment by Verhoeckx** [comment]
I understand! I will start making forms with Vue Formulate this week!
