### ISSUE TITLE
IE 11 error: Multiple definitions of a property not allowed in strict mode

### ISSUE THREAD

**Issue by OussamaFadlaoui** [wearebraid/vue-formulate#81]
**Describe the bug**
When running my Vue x Nuxt.js application on Internet Explorer 11, I get the following error:
![image](https://user-images.githubusercontent.com/59295517/81085139-1ba3b000-8ef7-11ea-848f-c4ad3b94aa81.png)
**Translation:** `Multiple definitions of a property not allowed in strict mode`

I have tried desperately to fix this issue myself, but I'm not that deep into programming yet, unfortunately.

**To Reproduce**
1. Install basic nuxt application
2. Install vue-formulate
3. Use vue-formulate in the application and run in IE 11

**Expected behavior**
Running everything without the error which is causing the entire Nuxt application to crash

**Screenshots**
When trying to trace back where the multiple definitions have been defined, I came across this line
![image](https://user-images.githubusercontent.com/59295517/81085634-c1efb580-8ef7-11ea-9400-10280b6ca85b.png)
I strongly believe this is causing the error..

**Device information:**
 - Device: PC
 - OS: Windows 10
 - Browser: IE11, works good on Edge, Chrome and others
 - Version 11

**Comment by justin-schroeder** [comment]
Hmm, this sounds like the longstanding Vue bug (https://github.com/vuejs/vue/issues/8379) again, but we fixed that way back in `v2.2.5` (#17). Are you using the latest version of Vue Formulate?

**Comment by OussamaFadlaoui** [comment]
Yes, I'm using the latest version! It's driving me crazy..
Also, I'm not using a dynamic input field type like the one in the issue you've linked.
Actually, this issue also shows whenever there's no input element on the page whatsoever. All I did was inject the components globally, without using them. When I did use the elements, it's all copied and pasted from the examples.

**Comment by justin-schroeder** [comment]
Are you doing npm run dev, or is this a built version of your app? Can you send a reproduction url? Currently the vueformulate.com website works in ie11 (some styling issues, but functional)

**Comment by OussamaFadlaoui** [comment]
I have tried building the app as well as running dev server.
I deployed it so you can take a look for yourself:
https://vue-formulate-sandbox.herokuapp.com/account/inloggen

**Noteworthy**
I added extremely simple changes to the vue formulate source (added option to have icons added by adding a custom prop):
![image](https://user-images.githubusercontent.com/59295517/81092709-50b50000-8f01-11ea-88d9-c68f2cefbcd2.png)
`/node_modules/@braid/vue-formulate/src/inputs/FormulateInputText.vue`

**Comment by justin-schroeder** [comment]
Thanks for deploying a reproduction.

First off: your edit shouldn't have anything to do with your IE11 error...but did you fork the package? You should never directly modify things in `node_modules`. I assume you know that and are just experimenting, but editing anything in node_modules is a recipe for many bad things.

Looking at your site, I'm not entirely sure the version of Vue Formulate it is using, but it definitely is not the latest one. Please try updating to the latest and I bet that fixes the issue for you.

**Comment by OussamaFadlaoui** [comment]
> Thanks for deploying a reproduction.
> 
> First off: your edit shouldn't have anything to do with your IE11 error...but did you fork the package? You should never directly modify things in `node_modules`. I assume you know that and are just experimenting, but editing anything in node_modules is a recipe for many bad things.
> 
> Looking at your site, I'm not entirely sure the version of Vue Formulate it is using, but it definitely is not the latest one. Please try updating to the latest and I bet that fixes the issue for you.

Thanks a lot for the quick replies and helpful lessons. I will follow your instructions and post a follow-up tomorrow.
:)

**Comment by justin-schroeder** [comment]
Great! I'm going to close this for now, but if feel free to continue using this thread, and if we discover a reproducible issue with newer versions we'll re-open the issue.
