### ISSUE TITLE
Question: how do I create a hidden input field?

### ISSUE THREAD

**Issue by Verhoeckx** [wearebraid/vue-formulate#83]
The documentation says:
While technically Vue Formulate does support hidden input fields, the use case is pretty minimal since you can easily inject your own "hidden" values into submitted data with your a [form submission](https://vueformulate.com/guide/forms/).

But when I look at that page I can't find something that answers the question (or I don't understand the code/text very well).

I guess the code for a hidden input element is:
```
<formulate-input
  type="hidden"
  name="secretInputField">
</formulate-input>
```

I'm I correct?

**Comment by justin-schroeder** [comment]
Thats correct!

**Comment by Verhoeckx** [comment]
That's very quick again :-)!
Thanks!!

I think you have to remove the word 'your' in the last part of the sentence in the documentation (see above). And I see that I forgot the property/attribute 'value' in my code.

**Comment by justin-schroeder** [comment]
Good catch. Would you mind submitting a PR for that over on the documentation repository? It's super easy, just hit the edit (pencil) icon here: https://github.com/wearebraid/vueformulate.com/tree/master/docs/guide/inputs/text
