### ISSUE TITLE
Improved form generation to support grouped / repeating inputs and structure styles

### ISSUE THREAD

**Issue by martinval** [wearebraid/vue-formulate#89]
**Describe the new feature you'd like**
Right now, you can't generate a form from a schema-like json file with several fields on the same line, as they are full width by default. Fields on the same line have to be put in a flex div by hand.

Not sure if this could be achieved, but maybe fields could by default by in a flex div and have a "group" (e.g. group=namefields) and "width" (1/3, 1/2, etc.) attribute so they could _automagically_ be assembled into a more complex layout.

Thanks in advance for the consideration.
 

**What percentage of vue-formulate users would benefit?**
80% ?

**Comment by Garito** [comment]
Check vue-portal for this issue

**Comment by andrew-boyd** [comment]
@martinval I agree that there's a need for more support in generating forms. Right now basic use-cases are supported but new (`2.3.0+`) options like groups are not supported because the expectation is that a user would use a `v-for` on a single `FormulateInput`, so we're only accounting for one level of depth.

I could see more complex form generation in the future being plugin-based and adding a new (and optional) `FormulateGenerator` element that was able to handle groups and repeating groups. #66 also discusses class maps would also be useful during form generation, as you'd be able to apply utility classes to inputs as props.

**Comment by martinval** [comment]
Thanks for the info @andrew-boyd #66 goes into the same direction indeed. 
I agree that simplicity is key and I appreciate this plugin for that.
I'll wait to see how thing s develop...

**Comment by andrew-boyd** [comment]
@martinval I'm re-naming and keeping this issue open so that we can track improved form generation independent of #66 class maps (which this will likely depend on)

**Comment by justin-schroeder** [comment]
Just weighing in here too — I agree we need a more robust form-generation mechanism. I'd like to see something better in VueFormulate core that is very lightweight — effectively just a json map of attributes/properties to pass that would be passed into a `<component :is>`, but with support for recursion as well so we could nest inputs pretty easily.

This would make the implementation really lightweight (we need to very carefully consider bytes shipped), and if you know how to code a Vue Formulate form, you know how to code the requisite JSON format — by hand even! For example, when coding a group with nested children and a custom div wrapper *could* look like this:

```js
{
  "type": "group",
  "name": "attendees",
  "label": "Add your attendees",
  "repeatable": true,
  "validation": "min:1,length",
  "children": [
    {
      "is": "div", // "is" indicates a non FormulateInput element
      "class": "my-class-for-a-flex-container",
      "children": [
        {
          "type": "text",
          "name": "name",
          "label": "Attendee’s name",
          "validation": "required"
        },
        {
            "type": "email",
            "name": "email",
            "label": "Attendee’s email address",
            "validation": "required|email"
        }
      ]
    }
  ]
}
```

This is open to discussion! Would love feedback!

**Comment by justin-schroeder** [comment]
Getting close to finalizing the spec for the form generation schema coming to 2.4. 

Open to any feedback before it’s released:

https://vueformulatecom-git-feature-generator.braid.now.sh/guide/forms/generating-forms

**Comment by justin-schroeder** [comment]
The new schema format is now live in `2.4`. More docs about it available here:

https://vueformulate.com/guide/forms/generating-forms/
