### ISSUE TITLE
Create Quiksheet for a quick overview of all the diferent possibilites

### ISSUE THREAD

**Issue by Rednas83** [wearebraid/vue-formulate#93]
Just started yesterday with this framework and already decided to use it for my further projects. The current documentation is good for learning the basics. But is not ideal for during programming.

For example something like this
![image](https://user-images.githubusercontent.com/25219229/82896949-1c0ff380-9f57-11ea-8ff1-37d3b30fda9e.png)

If needed I can of course share this document

**Comment by justin-schroeder** [comment]
Glad you're finding success with Vue Formulate 🎉

I'm not opposed to a cheat-sheet like this at all. Awesome work 👍 I think other people could find it helpful too. When you feel like it is ready for prime time feel free to submit a pull request to the documentation repository:

https://github.com/wearebraid/vueformulate.com

If you do so, please consider using the hex colors on the documentation site so it can all stay consistent. I'll close this here and wait for the PR on the docs repo.
