### ISSUE TITLE
Using field type select with options from database. Help me understand how to 

### ISSUE THREAD

**Issue by joshfom** [wearebraid/vue-formulate#94]
First of all, I really want to thank you all for coming up with this, 
I deeply appreciate it is saving me a lot of hours

Just 4 days ago I stumble on this and I am loving it, 
I seek help to understand form field **Select**[ :options,](https://vueformulate.com/guide/inputs/types/select/#select-2) 
My data is coming from  database, as an Object/Array/JSON 
everything shows up as the first option only, 

`
Illuminate\Support\Collection {#1647 ▼
  #items: array:3 [▼
    1 => "Restaurant"
    2 => "Social Media"
    3 => "Shopping"
  ]
}
`
JSON
`"{"1":"Restaurant","2":"Social Media","3":"Shopping"}"`

this is what I get
![image](https://user-images.githubusercontent.com/23559469/82951283-e94a1780-9fb7-11ea-8392-bebd3abe5776.png)

Please appreciate any heads up or better way to do it

**Comment by justin-schroeder** [comment]
I'm guessing that the value you're binding into the select list is a string value on the front end and not actually an object.

Try console logging your value and see if it is a JSON string, or a javascript object. You want it to be an object

**Comment by joshfom** [comment]
@justin-schroeder thank you so much, you got me through 

`  <FormulateInput type="select"
                                                                    label="Category"
                                                                    placeholder="Choose Category"
                                                                    :options="JSON.parse(this.data.categories)"
                                                    >`
I really appreciate
