### ISSUE TITLE
Allow to show image returned by API response

### ISSUE THREAD

**Issue by mohit-vora** [wearebraid/vue-formulate#97]
While all other input fields have way to display already saved data using v-model, its not possible to display image returned by API response. It would help to let users communicate that their image is already saved

**What percentage of vue-formulate users would benefit?**
I don't know how many percent of users use Image input type in this lib.

**Comment by justin-schroeder** [comment]
Hi @mohit-vora.

Good news, it is possible. In fact the documentation covers it here:

https://vueformulate.com/guide/inputs/types/file/#setting-initial-values

Here's a code pen example too:

https://codepen.io/justin-schroeder/pen/KKdOBvX
