### ISSUE TITLE
Css outer element selector

### ISSUE THREAD

**Issue by paulogr** [wearebraid/vue-formulate#99]
It's a question indeed.

How to change an outer element when input[type="radio"]:checked ?

For example I want to change the background color of `. formulate-input-wrapper` when an inner input[type="radio"] is checked ?

Do you see a way to accomplish that?

Thank you!

**Comment by justin-schroeder** [comment]
Hmm....you're right @paulogr. The old (very old) version of vue-formulate used to have a `data-has-value` attribute on the outer wrapper (`.formulate-input`). The 2.0 rewrite hasn't included that feature. That's an oversight for sure. I'm working to add that feature back in right now. Should have a new release shortly.

**Comment by justin-schroeder** [comment]
@paulogr ok the new `v2.3.4` now includes a new data attribute `data-has-value` that will be applied to inputs with values. That includes radio inputs too. That should let you do some simeple css:

```css
[data-classification="box"][data-has-value] .formulate-input-wrapper {
// custom styles
}
```

**Comment by justin-schroeder** [comment]
@paulogr if it's helpful here's a codepen I worked:

https://codepen.io/justin-schroeder/pen/xxZbVNd
